// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// Equipment Class Mappings queries
	AddEquipmentToClass(ctx context.Context, arg *AddEquipmentToClassParams) (*EquipmentClassMapping, error)
	// Equipment queries
	CreateEquipment(ctx context.Context, arg *CreateEquipmentParams) (*Equipment, error)
	// Equipment Classes queries
	CreateEquipmentClass(ctx context.Context, arg *CreateEquipmentClassParams) (*EquipmentClass, error)
	// Equipment Class Properties queries
	CreateEquipmentClassProperty(ctx context.Context, arg *CreateEquipmentClassPropertyParams) (*EquipmentClassProperty, error)
	// Equipment Properties queries
	CreateEquipmentProperty(ctx context.Context, arg *CreateEquipmentPropertyParams) (*EquipmentProperty, error)
	DeleteEquipment(ctx context.Context, id uuid.UUID) error
	DeleteEquipmentClass(ctx context.Context, id uuid.UUID) error
	DeleteEquipmentProperty(ctx context.Context, id uuid.UUID) error
	GetEquipmentByExternalID(ctx context.Context, externalID string) (*Equipment, error)
	GetEquipmentByID(ctx context.Context, id uuid.UUID) (*Equipment, error)
	GetEquipmentClassByExternalID(ctx context.Context, externalID string) (*EquipmentClass, error)
	GetEquipmentClassByID(ctx context.Context, id uuid.UUID) (*EquipmentClass, error)
	ListAllEquipmentClasses(ctx context.Context, arg *ListAllEquipmentClassesParams) ([]*EquipmentClass, error)
	ListChildEquipment(ctx context.Context, parentEquipmentID uuid.NullUUID) ([]*Equipment, error)
	ListEquipment(ctx context.Context, arg *ListEquipmentParams) ([]*Equipment, error)
	ListEquipmentByClass(ctx context.Context, equipmentClassID uuid.UUID) ([]*Equipment, error)
	ListEquipmentByStatus(ctx context.Context, arg *ListEquipmentByStatusParams) ([]*Equipment, error)
	ListEquipmentClassProperties(ctx context.Context, equipmentClassID uuid.UUID) ([]*EquipmentClassProperty, error)
	ListEquipmentClassesForEquipment(ctx context.Context, equipmentID uuid.UUID) ([]*EquipmentClass, error)
	ListEquipmentProperties(ctx context.Context, equipmentID uuid.UUID) ([]*EquipmentProperty, error)
	RemoveEquipmentFromClass(ctx context.Context, arg *RemoveEquipmentFromClassParams) error
	UpdateEquipmentClass(ctx context.Context, arg *UpdateEquipmentClassParams) (*EquipmentClass, error)
	UpdateEquipmentProperty(ctx context.Context, arg *UpdateEquipmentPropertyParams) (*EquipmentProperty, error)
	UpdateEquipmentStatus(ctx context.Context, arg *UpdateEquipmentStatusParams) (*Equipment, error)
}

var _ Querier = (*Queries)(nil)
