// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
	"net/url"
	"strings"

	"github.com/ogen-go/ogen/uri"
)

func (s *Server) cutPrefix(path string) (string, bool) {
	prefix := s.cfg.Prefix
	if prefix == "" {
		return path, true
	}
	if !strings.HasPrefix(path, prefix) {
		// Prefix doesn't match.
		return "", false
	}
	// Cut prefix from the path.
	return strings.TrimPrefix(path, prefix), true
}

// ServeHTTP serves http request as defined by OpenAPI v3 specification,
// calling handler that matches the path or returning not found error.
func (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	elem := r.URL.Path
	elemIsEscaped := false
	if rawPath := r.URL.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
			elemIsEscaped = strings.ContainsRune(elem, '%')
		}
	}

	elem, ok := s.cutPrefix(elem)
	if !ok || len(elem) == 0 {
		s.notFound(w, r)
		return
	}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/"

			if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case 'b': // Prefix: "batches"

				if l := len("batches"); len(elem) >= l && elem[0:l] == "batches" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "GET":
						s.handleBatchesGetRequest([0]string{}, elemIsEscaped, w, r)
					case "POST":
						s.handleBatchesPostRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, "GET,POST")
					}

					return
				}

			case 'e': // Prefix: "equipment"

				if l := len("equipment"); len(elem) >= l && elem[0:l] == "equipment" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "GET":
						s.handleEquipmentGetRequest([0]string{}, elemIsEscaped, w, r)
					case "POST":
						s.handleEquipmentPostRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, "GET,POST")
					}

					return
				}

			case 'm': // Prefix: "materials"

				if l := len("materials"); len(elem) >= l && elem[0:l] == "materials" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "GET":
						s.handleMaterialsGetRequest([0]string{}, elemIsEscaped, w, r)
					case "POST":
						s.handleMaterialsPostRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, "GET,POST")
					}

					return
				}

			case 'p': // Prefix: "person"

				if l := len("person"); len(elem) >= l && elem[0:l] == "person" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'n': // Prefix: "nel-"

					if l := len("nel-"); len(elem) >= l && elem[0:l] == "nel-" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'c': // Prefix: "classes"

						if l := len("classes"); len(elem) >= l && elem[0:l] == "classes" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "GET":
								s.handlePersonnelClassesGetRequest([0]string{}, elemIsEscaped, w, r)
							case "POST":
								s.handlePersonnelClassesPostRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, "GET,POST")
							}

							return
						}

					case 'i': // Prefix: "information"

						if l := len("information"); len(elem) >= l && elem[0:l] == "information" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch r.Method {
							case "GET":
								s.handlePersonnelInformationGetRequest([0]string{}, elemIsEscaped, w, r)
							case "POST":
								s.handlePersonnelInformationPostRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, "GET,POST")
							}

							return
						}

					}

				case 's': // Prefix: "s"

					if l := len("s"); len(elem) >= l && elem[0:l] == "s" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "GET":
							s.handlePersonsGetRequest([0]string{}, elemIsEscaped, w, r)
						case "POST":
							s.handlePersonsPostRequest([0]string{}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, "GET,POST")
						}

						return
					}

				}

			}

		}
	}
	s.notFound(w, r)
}

// Route is route object.
type Route struct {
	name        string
	summary     string
	operationID string
	pathPattern string
	count       int
	args        [0]string
}

// Name returns ogen operation name.
//
// It is guaranteed to be unique and not empty.
func (r Route) Name() string {
	return r.name
}

// Summary returns OpenAPI summary.
func (r Route) Summary() string {
	return r.summary
}

// OperationID returns OpenAPI operationId.
func (r Route) OperationID() string {
	return r.operationID
}

// PathPattern returns OpenAPI path.
func (r Route) PathPattern() string {
	return r.pathPattern
}

// Args returns parsed arguments.
func (r Route) Args() []string {
	return r.args[:r.count]
}

// FindRoute finds Route for given method and path.
//
// Note: this method does not unescape path or handle reserved characters in path properly. Use FindPath instead.
func (s *Server) FindRoute(method, path string) (Route, bool) {
	return s.FindPath(method, &url.URL{Path: path})
}

// FindPath finds Route for given method and URL.
func (s *Server) FindPath(method string, u *url.URL) (r Route, _ bool) {
	var (
		elem = u.Path
		args = r.args
	)
	if rawPath := u.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
		}
		defer func() {
			for i, arg := range r.args[:r.count] {
				if unescaped, err := url.PathUnescape(arg); err == nil {
					r.args[i] = unescaped
				}
			}
		}()
	}

	elem, ok := s.cutPrefix(elem)
	if !ok {
		return r, false
	}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/"

			if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case 'b': // Prefix: "batches"

				if l := len("batches"); len(elem) >= l && elem[0:l] == "batches" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch method {
					case "GET":
						r.name = BatchesGetOperation
						r.summary = "Получить список батчей"
						r.operationID = ""
						r.pathPattern = "/batches"
						r.args = args
						r.count = 0
						return r, true
					case "POST":
						r.name = BatchesPostOperation
						r.summary = "Создать новый батч"
						r.operationID = ""
						r.pathPattern = "/batches"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}

			case 'e': // Prefix: "equipment"

				if l := len("equipment"); len(elem) >= l && elem[0:l] == "equipment" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch method {
					case "GET":
						r.name = EquipmentGetOperation
						r.summary = "Получить список оборудования"
						r.operationID = ""
						r.pathPattern = "/equipment"
						r.args = args
						r.count = 0
						return r, true
					case "POST":
						r.name = EquipmentPostOperation
						r.summary = "Добавить оборудование"
						r.operationID = ""
						r.pathPattern = "/equipment"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}

			case 'm': // Prefix: "materials"

				if l := len("materials"); len(elem) >= l && elem[0:l] == "materials" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch method {
					case "GET":
						r.name = MaterialsGetOperation
						r.summary = "Получить список материалов"
						r.operationID = ""
						r.pathPattern = "/materials"
						r.args = args
						r.count = 0
						return r, true
					case "POST":
						r.name = MaterialsPostOperation
						r.summary = "Добавить материал"
						r.operationID = ""
						r.pathPattern = "/materials"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}

			case 'p': // Prefix: "person"

				if l := len("person"); len(elem) >= l && elem[0:l] == "person" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'n': // Prefix: "nel-"

					if l := len("nel-"); len(elem) >= l && elem[0:l] == "nel-" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'c': // Prefix: "classes"

						if l := len("classes"); len(elem) >= l && elem[0:l] == "classes" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "GET":
								r.name = PersonnelClassesGetOperation
								r.summary = "Получить список классов персонала (PersonnelClass)"
								r.operationID = ""
								r.pathPattern = "/personnel-classes"
								r.args = args
								r.count = 0
								return r, true
							case "POST":
								r.name = PersonnelClassesPostOperation
								r.summary = "Добавить класс персонала"
								r.operationID = ""
								r.pathPattern = "/personnel-classes"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}

					case 'i': // Prefix: "information"

						if l := len("information"); len(elem) >= l && elem[0:l] == "information" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							// Leaf node.
							switch method {
							case "GET":
								r.name = PersonnelInformationGetOperation
								r.summary = "Получить информацию о персонале (PersonnelInformation)"
								r.operationID = ""
								r.pathPattern = "/personnel-information"
								r.args = args
								r.count = 0
								return r, true
							case "POST":
								r.name = PersonnelInformationPostOperation
								r.summary = "Добавить информацию о персонале"
								r.operationID = ""
								r.pathPattern = "/personnel-information"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}

					}

				case 's': // Prefix: "s"

					if l := len("s"); len(elem) >= l && elem[0:l] == "s" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "GET":
							r.name = PersonsGetOperation
							r.summary = "Получить список персон (Person)"
							r.operationID = ""
							r.pathPattern = "/persons"
							r.args = args
							r.count = 0
							return r, true
						case "POST":
							r.name = PersonsPostOperation
							r.summary = "Добавить персону"
							r.operationID = ""
							r.pathPattern = "/persons"
							r.args = args
							r.count = 0
							return r, true
						default:
							return
						}
					}

				}

			}

		}
	}
	return r, false
}
