// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// BatchesGet implements GET /batches operation.
//
// Получить список батчей.
//
// GET /batches
func (UnimplementedHandler) BatchesGet(ctx context.Context) (r []BatchType, _ error) {
	return r, ht.ErrNotImplemented
}

// BatchesPost implements POST /batches operation.
//
// Создать новый батч.
//
// POST /batches
func (UnimplementedHandler) BatchesPost(ctx context.Context, req *BatchType) error {
	return ht.ErrNotImplemented
}

// EquipmentGet implements GET /equipment operation.
//
// Получить список оборудования.
//
// GET /equipment
func (UnimplementedHandler) EquipmentGet(ctx context.Context) (r []EquipmentType, _ error) {
	return r, ht.ErrNotImplemented
}

// EquipmentPost implements POST /equipment operation.
//
// Добавить оборудование.
//
// POST /equipment
func (UnimplementedHandler) EquipmentPost(ctx context.Context, req *EquipmentType) error {
	return ht.ErrNotImplemented
}

// MaterialsGet implements GET /materials operation.
//
// Получить список материалов.
//
// GET /materials
func (UnimplementedHandler) MaterialsGet(ctx context.Context) (r []MaterialType, _ error) {
	return r, ht.ErrNotImplemented
}

// MaterialsPost implements POST /materials operation.
//
// Добавить материал.
//
// POST /materials
func (UnimplementedHandler) MaterialsPost(ctx context.Context, req *MaterialType) error {
	return ht.ErrNotImplemented
}

// PersonnelClassesGet implements GET /personnel-classes operation.
//
// Получить список классов персонала (PersonnelClass).
//
// GET /personnel-classes
func (UnimplementedHandler) PersonnelClassesGet(ctx context.Context) (r []PersonnelClassType, _ error) {
	return r, ht.ErrNotImplemented
}

// PersonnelClassesPost implements POST /personnel-classes operation.
//
// Добавить класс персонала.
//
// POST /personnel-classes
func (UnimplementedHandler) PersonnelClassesPost(ctx context.Context, req *PersonnelClassType) error {
	return ht.ErrNotImplemented
}

// PersonnelInformationGet implements GET /personnel-information operation.
//
// Получить информацию о персонале (PersonnelInformation).
//
// GET /personnel-information
func (UnimplementedHandler) PersonnelInformationGet(ctx context.Context) (r []PersonnelInformationType, _ error) {
	return r, ht.ErrNotImplemented
}

// PersonnelInformationPost implements POST /personnel-information operation.
//
// Добавить информацию о персонале.
//
// POST /personnel-information
func (UnimplementedHandler) PersonnelInformationPost(ctx context.Context, req *PersonnelInformationType) error {
	return ht.ErrNotImplemented
}

// PersonsGet implements GET /persons operation.
//
// Получить список персон (Person).
//
// GET /persons
func (UnimplementedHandler) PersonsGet(ctx context.Context) (r []PersonType, _ error) {
	return r, ht.ErrNotImplemented
}

// PersonsPost implements POST /persons operation.
//
// Добавить персону.
//
// POST /persons
func (UnimplementedHandler) PersonsPost(ctx context.Context, req *PersonType) error {
	return ht.ErrNotImplemented
}
