// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// BatchesGet implements GET /batches operation.
	//
	// Получить список батчей.
	//
	// GET /batches
	BatchesGet(ctx context.Context) ([]BatchType, error)
	// BatchesPost implements POST /batches operation.
	//
	// Создать новый батч.
	//
	// POST /batches
	BatchesPost(ctx context.Context, req *BatchType) error
	// EquipmentGet implements GET /equipment operation.
	//
	// Получить список оборудования.
	//
	// GET /equipment
	EquipmentGet(ctx context.Context) ([]EquipmentType, error)
	// EquipmentPost implements POST /equipment operation.
	//
	// Добавить оборудование.
	//
	// POST /equipment
	EquipmentPost(ctx context.Context, req *EquipmentType) error
	// MaterialsGet implements GET /materials operation.
	//
	// Получить список материалов.
	//
	// GET /materials
	MaterialsGet(ctx context.Context) ([]MaterialType, error)
	// MaterialsPost implements POST /materials operation.
	//
	// Добавить материал.
	//
	// POST /materials
	MaterialsPost(ctx context.Context, req *MaterialType) error
	// PersonnelClassesGet implements GET /personnel-classes operation.
	//
	// Получить список классов персонала (PersonnelClass).
	//
	// GET /personnel-classes
	PersonnelClassesGet(ctx context.Context) ([]PersonnelClassType, error)
	// PersonnelClassesPost implements POST /personnel-classes operation.
	//
	// Добавить класс персонала.
	//
	// POST /personnel-classes
	PersonnelClassesPost(ctx context.Context, req *PersonnelClassType) error
	// PersonnelInformationGet implements GET /personnel-information operation.
	//
	// Получить информацию о персонале (PersonnelInformation).
	//
	// GET /personnel-information
	PersonnelInformationGet(ctx context.Context) ([]PersonnelInformationType, error)
	// PersonnelInformationPost implements POST /personnel-information operation.
	//
	// Добавить информацию о персонале.
	//
	// POST /personnel-information
	PersonnelInformationPost(ctx context.Context, req *PersonnelInformationType) error
	// PersonsGet implements GET /persons operation.
	//
	// Получить список персон (Person).
	//
	// GET /persons
	PersonsGet(ctx context.Context) ([]PersonType, error)
	// PersonsPost implements POST /persons operation.
	//
	// Добавить персону.
	//
	// POST /persons
	PersonsPost(ctx context.Context, req *PersonType) error
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
