// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	BatchesGetOperation               OperationName = "BatchesGet"
	BatchesPostOperation              OperationName = "BatchesPost"
	EquipmentGetOperation             OperationName = "EquipmentGet"
	EquipmentPostOperation            OperationName = "EquipmentPost"
	MaterialsGetOperation             OperationName = "MaterialsGet"
	MaterialsPostOperation            OperationName = "MaterialsPost"
	PersonnelClassesGetOperation      OperationName = "PersonnelClassesGet"
	PersonnelClassesPostOperation     OperationName = "PersonnelClassesPost"
	PersonnelInformationGetOperation  OperationName = "PersonnelInformationGet"
	PersonnelInformationPostOperation OperationName = "PersonnelInformationPost"
	PersonsGetOperation               OperationName = "PersonsGet"
	PersonsPostOperation              OperationName = "PersonsPost"
)
