// Code generated by xgen. DO NOT EDIT.

package b2mml

// WorkSchedule ...
type WorkSchedule *WorkScheduleType

// WorkRequest ...
type WorkRequest *WorkRequestType

// JobList ...
type JobList *JobListType

// JobOrder ...
type JobOrder *JobOrderType

// GetWorkSchedule ...
type GetWorkSchedule *GetWorkScheduleType

// ShowWorkSchedule ...
type ShowWorkSchedule *ShowWorkScheduleType

// ProcessWorkSchedule ...
type ProcessWorkSchedule *ProcessWorkScheduleType

// AcknowledgeWorkSchedule ...
type AcknowledgeWorkSchedule *AcknowledgeWorkScheduleType

// ChangeWorkSchedule ...
type ChangeWorkSchedule *ChangeWorkScheduleType

// RespondWorkSchedule ...
type RespondWorkSchedule *RespondWorkScheduleType

// CancelWorkSchedule ...
type CancelWorkSchedule *CancelWorkScheduleType

// SyncWorkSchedule ...
type SyncWorkSchedule *SyncWorkScheduleType

// GetJobList ...
type GetJobList *GetJobListType

// ShowJobList ...
type ShowJobList *ShowJobListType

// ProcessJobList ...
type ProcessJobList *ProcessJobListType

// AcknowledgeJobList ...
type AcknowledgeJobList *AcknowledgeJobListType

// ChangeJobList ...
type ChangeJobList *ChangeJobListType

// RespondJobList ...
type RespondJobList *RespondJobListType

// CancelJobList ...
type CancelJobList *CancelJobListType

// SyncJobList ...
type SyncJobList *SyncJobListType

// WorkScheduleType ...
type WorkScheduleType struct {
	ExtendedWorkSchedule []*WorkScheduleType
	ID                   *IdentifierType     `xml:"ID"`
	Description          []*DescriptionType  `xml:"Description"`
	Version              *IdentifierType     `xml:"Version"`
	PublishedDate        *DateTimeType       `xml:"PublishedDate"`
	StartTime            *DateTimeType       `xml:"StartTime"`
	EndTime              *DateTimeType       `xml:"EndTime"`
	HierarchyScope       *HierarchyScopeType `xml:"HierarchyScope"`
	WorkType             *OperationsTypeType `xml:"WorkType"`
	ScheduleState        *RequestStateType   `xml:"ScheduleState"`
	WorkScheduleChild    []*WorkScheduleType `xml:"WorkScheduleChild"`
	WorkRequest          []*WorkRequestType  `xml:"WorkRequest"`
}

// WorkRequestType ...
type WorkRequestType struct {
	ExtendedWorkRequest  []*WorkRequestType
	ID                   *IdentifierType     `xml:"ID"`
	Description          []*DescriptionType  `xml:"Description"`
	Version              *IdentifierType     `xml:"Version"`
	HierarchyScope       *HierarchyScopeType `xml:"HierarchyScope"`
	WorkType             *OperationsTypeType `xml:"WorkType"`
	StartTime            *DateTimeType       `xml:"StartTime"`
	EndTime              *DateTimeType       `xml:"EndTime"`
	Priority             *PriorityType       `xml:"Priority"`
	OperationsRequestID  *IdentifierType     `xml:"OperationsRequestID"`
	SegmentRequirementID *IdentifierType     `xml:"SegmentRequirementID"`
	RequestState         *RequestStateType   `xml:"RequestState"`
	WorkRequestChild     []*WorkRequestType  `xml:"WorkRequestChild"`
	JobOrder             []*JobOrderType     `xml:"JobOrder"`
}

// JobListType ...
type JobListType struct {
	ExtendedJobList []*JobListType
	ID              *IdentifierType     `xml:"ID"`
	Description     []*DescriptionType  `xml:"Description"`
	Version         *IdentifierType     `xml:"Version"`
	PublishedDate   *DateTimeType       `xml:"PublishedDate"`
	StartTime       *DateTimeType       `xml:"StartTime"`
	EndTime         *DateTimeType       `xml:"EndTime"`
	HierarchyScope  *HierarchyScopeType `xml:"HierarchyScope"`
	WorkType        *OperationsTypeType `xml:"WorkType"`
	JobOrder        []*JobOrderType     `xml:"JobOrder"`
}

// JobOrderType ...
type JobOrderType struct {
	ExtendedJobOrder         []*JobOrderType
	ID                       *IdentifierType                   `xml:"ID"`
	Description              []*DescriptionType                `xml:"Description"`
	Version                  *IdentifierType                   `xml:"Version"`
	PublishedDate            *DateTimeType                     `xml:"PublishedDate"`
	StartTime                *DateTimeType                     `xml:"StartTime"`
	EndTime                  *DateTimeType                     `xml:"EndTime"`
	HierarchyScope           *HierarchyScopeType               `xml:"HierarchyScope"`
	WorkType                 *OperationsTypeType               `xml:"WorkType"`
	WorkMasterID             *IdentifierType                   `xml:"WorkMasterID"`
	WorkMasterVersion        *IdentifierType                   `xml:"WorkMasterVersion"`
	Priority                 *PriorityType                     `xml:"Priority"`
	Command                  *JobOrderCommandType              `xml:"Command"`
	CommandRule              *JobOrderCommandRuleType          `xml:"CommandRule"`
	DispatchStatus           *JobOrderDispatchStatusType       `xml:"DispatchStatus"`
	JobOrderParameter        []*ParameterTypeType              `xml:"JobOrderParameter"`
	PersonnelRequirement     []*OpPersonnelRequirementType     `xml:"PersonnelRequirement"`
	EquipmentRequirement     []*OpEquipmentRequirementType     `xml:"EquipmentRequirement"`
	PhysicalAssetRequirement []*OpPhysicalAssetRequirementType `xml:"PhysicalAssetRequirement"`
	MaterialRequirement      []*OpMaterialRequirementType      `xml:"MaterialRequirement"`
	SegmentRequirementID     []*IdentifierType                 `xml:"SegmentRequirementID"`
}

// DataArea ...
type DataArea struct {
	Get          *TransGetType       `xml:"Get"`
	WorkSchedule []*WorkScheduleType `xml:"WorkSchedule"`
}

// GetWorkScheduleType ...
type GetWorkScheduleType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ShowWorkScheduleType ...
type ShowWorkScheduleType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ProcessWorkScheduleType ...
type ProcessWorkScheduleType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// AcknowledgeWorkScheduleType ...
type AcknowledgeWorkScheduleType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ChangeWorkScheduleType ...
type ChangeWorkScheduleType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// RespondWorkScheduleType ...
type RespondWorkScheduleType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// CancelWorkScheduleType ...
type CancelWorkScheduleType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// SyncWorkScheduleType ...
type SyncWorkScheduleType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// GetJobListType ...
type GetJobListType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ShowJobListType ...
type ShowJobListType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ProcessJobListType ...
type ProcessJobListType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// AcknowledgeJobListType ...
type AcknowledgeJobListType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ChangeJobListType ...
type ChangeJobListType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// RespondJobListType ...
type RespondJobListType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// CancelJobListType ...
type CancelJobListType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// SyncJobListType ...
type SyncJobListType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}
