// Code generated by xgen. DO NOT EDIT.

package b2mml

// ResourceRelationshipNetwork ...
type ResourceRelationshipNetwork *ResourceRelationshipNetworkType

// ResourceRelationshipNetworkInformation ...
type ResourceRelationshipNetworkInformation *ResourceRelationshipNetworkInformationType

// ResourceNetworkConnectionType ...
type ResourceNetworkConnectionType *ResourceNetworkConnectionTypeType

// GetResourceRelationshipNetwork ...
type GetResourceRelationshipNetwork *GetResourceRelationshipNetworkType

// ShowResourceRelationshipNetwork ...
type ShowResourceRelationshipNetwork *ShowResourceRelationshipNetworkType

// ProcessResourceRelationshipNetwork ...
type ProcessResourceRelationshipNetwork *ProcessResourceRelationshipNetworkType

// AcknowledgeResourceRelationshipNetwork ...
type AcknowledgeResourceRelationshipNetwork *AcknowledgeResourceRelationshipNetworkType

// ChangeResourceRelationshipNetwork ...
type ChangeResourceRelationshipNetwork *ChangeResourceRelationshipNetworkType

// RespondResourceRelationshipNetwork ...
type RespondResourceRelationshipNetwork *RespondResourceRelationshipNetworkType

// CancelResourceRelationshipNetwork ...
type CancelResourceRelationshipNetwork *CancelResourceRelationshipNetworkType

// SyncResourceRelationshipNetwork ...
type SyncResourceRelationshipNetwork *SyncResourceRelationshipNetworkType

// GetResourceRelationshipNetworkInformation ...
type GetResourceRelationshipNetworkInformation *GetResourceRelationshipNetworkInformationType

// ShowResourceRelationshipNetworkInformation ...
type ShowResourceRelationshipNetworkInformation *ShowResourceRelationshipNetworkInformationType

// ProcessResourceRelationshipNetworkInformation ...
type ProcessResourceRelationshipNetworkInformation *ProcessResourceRelationshipNetworkInformationType

// AcknowledgeResourceRelationshipNetworkInformation ...
type AcknowledgeResourceRelationshipNetworkInformation *AcknowledgeResourceRelationshipNetworkInformationType

// ChangeResourceRelationshipNetworkInformation ...
type ChangeResourceRelationshipNetworkInformation *ChangeResourceRelationshipNetworkInformationType

// RespondResourceRelationshipNetworkInformation ...
type RespondResourceRelationshipNetworkInformation *RespondResourceRelationshipNetworkInformationType

// CancelResourceRelationshipNetworkInformation ...
type CancelResourceRelationshipNetworkInformation *CancelResourceRelationshipNetworkInformationType

// SyncResourceRelationshipNetworkInformation ...
type SyncResourceRelationshipNetworkInformation *SyncResourceRelationshipNetworkInformationType

// GetResourceNetworkConnectionType ...
type GetResourceNetworkConnectionType *GetResourceNetworkConnectionTypeType

// ShowResourceNetworkConnectionType ...
type ShowResourceNetworkConnectionType *ShowResourceNetworkConnectionTypeType

// ProcessResourceNetworkConnectionType ...
type ProcessResourceNetworkConnectionType *ProcessResourceNetworkConnectionTypeType

// AcknowledgeResourceNetworkConnectionType ...
type AcknowledgeResourceNetworkConnectionType *AcknowledgeResourceNetworkConnectionTypeType

// ChangeResourceNetworkConnectionType ...
type ChangeResourceNetworkConnectionType *ChangeResourceNetworkConnectionTypeType

// RespondResourceNetworkConnectionType ...
type RespondResourceNetworkConnectionType *RespondResourceNetworkConnectionTypeType

// CancelResourceNetworkConnectionType ...
type CancelResourceNetworkConnectionType *CancelResourceNetworkConnectionTypeType

// SyncResourceNetworkConnectionType ...
type SyncResourceNetworkConnectionType *SyncResourceNetworkConnectionTypeType

// ResourceRelationshipNetworkInformationType ...
type ResourceRelationshipNetworkInformationType struct {
	ExtendedResourceRelationshipNetworkInformation []*ResourceRelationshipNetworkInformationType
	ID                                             *IdentifierType                      `xml:"ID"`
	Description                                    []*DescriptionType                   `xml:"Description"`
	HierarchyScope                                 *HierarchyScopeType                  `xml:"HierarchyScope"`
	ResourceRelationshipNetwork                    []*ResourceRelationshipNetworkType   `xml:"ResourceRelationshipNetwork"`
	ResourceNetworkConnectionType                  []*ResourceNetworkConnectionTypeType `xml:"ResourceNetworkConnectionType"`
}

// ResourceNetworkConnectionTypeType ...
type ResourceNetworkConnectionTypeType struct {
	ExtendedResourceNetworkConnectionType []*ResourceNetworkConnectionTypeType
	ID                                    *IdentifierType        `xml:"ID"`
	Version                               *IdentifierType        `xml:"Version"`
	Description                           []*DescriptionType     `xml:"Description"`
	PublishedDate                         *DateTimeType          `xml:"PublishedDate"`
	EffectiveStartDate                    *DateTimeType          `xml:"EffectiveStartDate"`
	EffectiveEndDate                      *DateTimeType          `xml:"EffectiveEndDate"`
	HierarchyScope                        *HierarchyScopeType    `xml:"HierarchyScope"`
	ConnectionType                        *IdentifierType        `xml:"ConnectionType"`
	ResourceNetworkConnectionSourceID     *IdentifierType        `xml:"ResourceNetworkConnectionSourceID"`
	RNCTypeProperty                       []*RNCTypePropertyType `xml:"RNCTypeProperty"`
}

// ResourceRelationshipNetworkType ...
type ResourceRelationshipNetworkType struct {
	ExtendedResourceRelationshipNetwork []*ResourceRelationshipNetworkType
	ID                                  *IdentifierType                      `xml:"ID"`
	Version                             *IdentifierType                      `xml:"Version"`
	Description                         []*DescriptionType                   `xml:"Description"`
	PublishedDate                       *DateTimeType                        `xml:"PublishedDate"`
	EffectiveStartDate                  *DateTimeType                        `xml:"EffectiveStartDate"`
	EffectiveEndDate                    *DateTimeType                        `xml:"EffectiveEndDate"`
	HierarchyScope                      *HierarchyScopeType                  `xml:"HierarchyScope"`
	RelationshipType                    *RelationshipTypeType                `xml:"RelationshipType"`
	RelationshipForm                    *RelationshipFormType                `xml:"RelationshipForm"`
	RRNProperty                         []*RRNPropertyType                   `xml:"RRNProperty"`
	ResourceNetworkConnection           []*ResourceNetworkConnectionTypeType `xml:"ResourceNetworkConnection"`
}

// ResourceReferenceType ...
type ResourceReferenceType struct {
	ExtendedResourceReference []*ResourceReference
	ID                        *IdentifierType                  `xml:"ID"`
	ResourceID                *IdentifierType                  `xml:"ResourceID"`
	ResourceClassID           *IdentifierType                  `xml:"ResourceClassID"`
	ResourceType              *ResourceReferenceTypeType       `xml:"ResourceType"`
	ResourceReferenceProperty []*ResourceReferencePropertyType `xml:"ResourceReferenceProperty"`
}

// ResourceReferencePropertyType ...
type ResourceReferencePropertyType struct {
	ExtendedResourceReferenceProperty []*ResourceReferenceProperty
	ID                                *IdentifierType                  `xml:"ID"`
	Description                       []*DescriptionType               `xml:"Description"`
	ResourcePropertyID                *IdentifierType                  `xml:"ResourcePropertyID"`
	ResourceClassPropertyID           *IdentifierType                  `xml:"ResourceClassPropertyID"`
	Value                             []*ValueType                     `xml:"Value"`
	ResourceReferencePropertyChild    []*ResourceReferencePropertyType `xml:"ResourceReferencePropertyChild"`
}

// RRNPropertyType ...
type RRNPropertyType struct {
	ExtendedRRNProperty []*RRNProperty
	ID                  *IdentifierType    `xml:"ID"`
	Description         []*DescriptionType `xml:"Description"`
	Value               []*ValueType       `xml:"Value"`
	RRNPropertyChild    []*RRNPropertyType `xml:"RRNPropertyChild"`
}

// RNCTypePropertyType ...
type RNCTypePropertyType struct {
	ExtendedRNCTypeProperty []*RNCTypeProperty
	ID                      *IdentifierType    `xml:"ID"`
	Description             []*DescriptionType `xml:"Description"`
	Value                   []*ValueType       `xml:"Value"`
	RNCTypePropertyChild    []*IdentifierType  `xml:"RNCTypePropertyChild"`
}

// RNCPropertyType ...
type RNCPropertyType struct {
	ExtendedRNCProperty []*RNCProperty
	ID                  *IdentifierType    `xml:"ID"`
	Description         []*DescriptionType `xml:"Description"`
	Value               []*ValueType       `xml:"Value"`
	RNCTypePropertyID   *IdentifierType    `xml:"RNCTypePropertyID"`
	RNCPropertyChild    []*RNCPropertyType `xml:"RNCPropertyChild"`
}

// DataArea ...
type DataArea struct {
	Get                         *TransGetType                      `xml:"Get"`
	ResourceRelationshipNetwork []*ResourceRelationshipNetworkType `xml:"ResourceRelationshipNetwork"`
}

// GetResourceRelationshipNetworkType ...
type GetResourceRelationshipNetworkType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ShowResourceRelationshipNetworkType ...
type ShowResourceRelationshipNetworkType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ProcessResourceRelationshipNetworkType ...
type ProcessResourceRelationshipNetworkType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// AcknowledgeResourceRelationshipNetworkType ...
type AcknowledgeResourceRelationshipNetworkType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ChangeResourceRelationshipNetworkType ...
type ChangeResourceRelationshipNetworkType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// RespondResourceRelationshipNetworkType ...
type RespondResourceRelationshipNetworkType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// CancelResourceRelationshipNetworkType ...
type CancelResourceRelationshipNetworkType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// SyncResourceRelationshipNetworkType ...
type SyncResourceRelationshipNetworkType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// GetResourceRelationshipNetworkInformationType ...
type GetResourceRelationshipNetworkInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ShowResourceRelationshipNetworkInformationType ...
type ShowResourceRelationshipNetworkInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ProcessResourceRelationshipNetworkInformationType ...
type ProcessResourceRelationshipNetworkInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// AcknowledgeResourceRelationshipNetworkInformationType ...
type AcknowledgeResourceRelationshipNetworkInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ChangeResourceRelationshipNetworkInformationType ...
type ChangeResourceRelationshipNetworkInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// RespondResourceRelationshipNetworkInformationType ...
type RespondResourceRelationshipNetworkInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// CancelResourceRelationshipNetworkInformationType ...
type CancelResourceRelationshipNetworkInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// SyncResourceRelationshipNetworkInformationType ...
type SyncResourceRelationshipNetworkInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// GetResourceNetworkConnectionTypeType ...
type GetResourceNetworkConnectionTypeType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ShowResourceNetworkConnectionTypeType ...
type ShowResourceNetworkConnectionTypeType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ProcessResourceNetworkConnectionTypeType ...
type ProcessResourceNetworkConnectionTypeType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// AcknowledgeResourceNetworkConnectionTypeType ...
type AcknowledgeResourceNetworkConnectionTypeType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ChangeResourceNetworkConnectionTypeType ...
type ChangeResourceNetworkConnectionTypeType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// RespondResourceNetworkConnectionTypeType ...
type RespondResourceNetworkConnectionTypeType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// CancelResourceNetworkConnectionTypeType ...
type CancelResourceNetworkConnectionTypeType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// SyncResourceNetworkConnectionTypeType ...
type SyncResourceNetworkConnectionTypeType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}
