// Code generated by xgen. DO NOT EDIT.

package b2mml

// OperationalLocationInformation is Operational locations define the logical or physical places in which resources are located or are expected to be located within a plant.
// Operational locations may be made up of smaller operational locations. An operational location may belong to one or more operational location classes.
// An operational location class may be a specialization of one or more operational location classes.
type OperationalLocationInformation *OperationalLocationInformationType

// OperationalLocationClass is A representation of a grouping of operational locations with similar characteristics for a definite purpose
// such as manufacturing operations definition, scheduling, capability and performance shall be presented as an
// operational location class. Any operational location may be a member of zero or more operational location classes.
type OperationalLocationClass *OperationalLocationClassType

// OperationalLocation is A logical or physical location where a material lot, material sublot, equipment, physical asset or person
// is located or expected to be located shall be presented as an operational location. Operational locations
// may be made up of other operational locations.
type OperationalLocation *OperationalLocationType

// GetOperationalLocation ...
type GetOperationalLocation *GetOperationalLocationType

// ShowOperationalLocation ...
type ShowOperationalLocation *ShowOperationalLocationType

// ProcessOperationalLocation ...
type ProcessOperationalLocation *ProcessOperationalLocationType

// AcknowledgeOperationalLocation ...
type AcknowledgeOperationalLocation *AcknowledgeOperationalLocationType

// ChangeOperationalLocation ...
type ChangeOperationalLocation *ChangeOperationalLocationType

// RespondOperationalLocation ...
type RespondOperationalLocation *RespondOperationalLocationType

// CancelOperationalLocation ...
type CancelOperationalLocation *CancelOperationalLocationType

// SyncOperationalLocation ...
type SyncOperationalLocation *SyncOperationalLocationType

// GetOperationalLocationClass ...
type GetOperationalLocationClass *GetOperationalLocationClassType

// ShowOperationalLocationClass ...
type ShowOperationalLocationClass *ShowOperationalLocationClassType

// ProcessOperationalLocationClass ...
type ProcessOperationalLocationClass *ProcessOperationalLocationClassType

// AcknowledgeOperationalLocationClass ...
type AcknowledgeOperationalLocationClass *AcknowledgeOperationalLocationClassType

// ChangeOperationalLocationClass ...
type ChangeOperationalLocationClass *ChangeOperationalLocationClassType

// RespondOperationalLocationClass ...
type RespondOperationalLocationClass *RespondOperationalLocationClassType

// CancelOperationalLocationClass ...
type CancelOperationalLocationClass *CancelOperationalLocationClassType

// SyncOperationalLocationClass ...
type SyncOperationalLocationClass *SyncOperationalLocationType

// GetOperationalLocationInformation ...
type GetOperationalLocationInformation *GetOperationalLocationInformationType

// ShowOperationalLocationInformation ...
type ShowOperationalLocationInformation *ShowOperationalLocationInformationType

// ProcessOperationalLocationInformation ...
type ProcessOperationalLocationInformation *ProcessOperationalLocationInformationType

// AcknowledgeOperationalLocationInformation ...
type AcknowledgeOperationalLocationInformation *AcknowledgeOperationalLocationInformationType

// ChangeOperationalLocationInformation ...
type ChangeOperationalLocationInformation *ChangeOperationalLocationInformationType

// RespondOperationalLocationInformation ...
type RespondOperationalLocationInformation *RespondOperationalLocationInformationType

// CancelOperationalLocationInformation ...
type CancelOperationalLocationInformation *CancelOperationalLocationInformationType

// SyncOperationalLocationInformation ...
type SyncOperationalLocationInformation *SyncOperationalLocationInformationType

// OperationalLocationInformationType ...
type OperationalLocationInformationType struct {
	ExtendedOperationalLocationInformation []*OperationalLocationInformationType
	ID                                     *IdentifierType                 `xml:"ID"`
	Description                            []*DescriptionType              `xml:"Description"`
	HierarchyScope                         *HierarchyScopeType             `xml:"HierarchyScope"`
	PublishedDate                          *DateTimeType                   `xml:"PublishedDate"`
	OperationalLocationClass               []*OperationalLocationClassType `xml:"OperationalLocationClass"`
	OperationalLocation                    []*OperationalLocationType      `xml:"OperationalLocation"`
}

// OperationalLocationType ...
type OperationalLocationType struct {
	ExtendedOperationalLocation []*OperationalLocationType
	ID                          *IdentifierType                    `xml:"ID"`
	Description                 []*DescriptionType                 `xml:"Description"`
	Version                     *IdentifierType                    `xml:"Version"`
	PublishedDate               *DateTimeType                      `xml:"PublishedDate"`
	EffectiveStartDate          *DateTimeType                      `xml:"EffectiveStartDate"`
	EffectiveEndDate            *DateTimeType                      `xml:"EffectiveEndDate"`
	HierarchyScope              *HierarchyScopeType                `xml:"HierarchyScope"`
	SpatialDefinition           *SpatialDefinitionType             `xml:"SpatialDefinition"`
	OperationalClassID          *IdentifierType                    `xml:"OperationalClassID"`
	OperationalLocationChild    []*OperationalLocationType         `xml:"OperationalLocationChild"`
	OperationalLocationProperty []*OperationalLocationPropertyType `xml:"OperationalLocationProperty"`
}

// OperationalLocationClassType ...
type OperationalLocationClassType struct {
	ExtendedOperationalLocation      []*OperationalLocationType
	ID                               *IdentifierType                         `xml:"ID"`
	Description                      []*DescriptionType                      `xml:"Description"`
	Version                          *IdentifierType                         `xml:"Version"`
	PublishedDate                    *DateTimeType                           `xml:"PublishedDate"`
	EffectiveStartDate               *DateTimeType                           `xml:"EffectiveStartDate"`
	EffectiveEndDate                 *DateTimeType                           `xml:"EffectiveEndDate"`
	HierarchyScope                   *HierarchyScopeType                     `xml:"HierarchyScope"`
	OperationalLocationClassChild    *OperationalLocationClassType           `xml:"OperationalLocationClassChild"`
	OperationalLocationClassBaseID   []*IdentifierType                       `xml:"OperationalLocationClassBaseID"`
	OperationalLocationSourceID      []*IdentifierType                       `xml:"OperationalLocationSourceID"`
	OperationalLocationClassProperty []*OperationalLocationClassPropertyType `xml:"OperationalLocationClassProperty"`
}

// OperationalLocationClassPropertyType ...
type OperationalLocationClassPropertyType struct {
	ExtendedOperationalLocationClassProperty []*OperationalLocationClassProperty
	ID                                       *IdentifierType                         `xml:"ID"`
	Description                              []*DescriptionType                      `xml:"Description"`
	Value                                    []*ValueType                            `xml:"Value"`
	PropertyType                             *ClassPropertyTypeType                  `xml:"PropertyType"`
	OperationalLocationClassPropertyChild    []*OperationalLocationClassPropertyType `xml:"OperationalLocationClassPropertyChild"`
}

// OperationalLocationPropertyType ...
type OperationalLocationPropertyType struct {
	ExtendedOperationalLocationProperty []*OperationalLocationProperty
	ID                                  *IdentifierType                    `xml:"ID"`
	Description                         []*DescriptionType                 `xml:"Description"`
	Value                               []*ValueType                       `xml:"Value"`
	OperationalLocationPropertyChild    []*OperationalLocationPropertyType `xml:"OperationalLocationPropertyChild"`
	OperationalClassPropertyID          *IdentifierType                    `xml:"OperationalClassPropertyID"`
}

// DataArea ...
type DataArea struct {
	Get                            *TransGetType                         `xml:"Get"`
	OperationalLocationInformation []*OperationalLocationInformationType `xml:"OperationalLocationInformation"`
}

// GetOperationalLocationInformationType ...
type GetOperationalLocationInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ShowOperationalLocationInformationType ...
type ShowOperationalLocationInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ProcessOperationalLocationInformationType ...
type ProcessOperationalLocationInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// AcknowledgeOperationalLocationInformationType ...
type AcknowledgeOperationalLocationInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ChangeOperationalLocationInformationType ...
type ChangeOperationalLocationInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// RespondOperationalLocationInformationType ...
type RespondOperationalLocationInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// CancelOperationalLocationInformationType ...
type CancelOperationalLocationInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// SyncOperationalLocationInformationType ...
type SyncOperationalLocationInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// GetOperationalLocationClassType ...
type GetOperationalLocationClassType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ShowOperationalLocationClassType ...
type ShowOperationalLocationClassType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ProcessOperationalLocationClassType ...
type ProcessOperationalLocationClassType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// AcknowledgeOperationalLocationClassType ...
type AcknowledgeOperationalLocationClassType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ChangeOperationalLocationClassType ...
type ChangeOperationalLocationClassType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// RespondOperationalLocationClassType ...
type RespondOperationalLocationClassType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// CancelOperationalLocationClassType ...
type CancelOperationalLocationClassType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// SyncOperationalLocationClassType ...
type SyncOperationalLocationClassType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// GetOperationalLocationType ...
type GetOperationalLocationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ShowOperationalLocationType ...
type ShowOperationalLocationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ProcessOperationalLocationType ...
type ProcessOperationalLocationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// AcknowledgeOperationalLocationType ...
type AcknowledgeOperationalLocationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ChangeOperationalLocationType ...
type ChangeOperationalLocationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// RespondOperationalLocationType ...
type RespondOperationalLocationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// CancelOperationalLocationType ...
type CancelOperationalLocationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// SyncOperationalLocationType ...
type SyncOperationalLocationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}
