// Code generated by xgen. DO NOT EDIT.

package b2mml

// MaterialInformation ...
// type MaterialInformation *MaterialInformationType

// MaterialClass ...
// type MaterialClass *MaterialClassType

// MaterialDefinition ...
// type MaterialDefinition *MaterialDefinitionType

// MaterialLot ...
// type MaterialLot *MaterialLotType

// MaterialSubLot ...
// type MaterialSubLot *MaterialSubLotType

// GetMaterialInformation ...
type GetMaterialInformation *GetMaterialInformationType

// ShowMaterialInformation ...
type ShowMaterialInformation *ShowMaterialInformationType

// ProcessMaterialInformation ...
type ProcessMaterialInformation *ProcessMaterialInformationType

// AcknowledgeMaterialInformation ...
type AcknowledgeMaterialInformation *AcknowledgeMaterialInformationType

// ChangeMaterialInformation ...
type ChangeMaterialInformation *ChangeMaterialInformationType

// RespondMaterialInformation ...
type RespondMaterialInformation *RespondMaterialInformationType

// CancelMaterialInformation ...
type CancelMaterialInformation *CancelMaterialInformationType

// SyncMaterialInformation ...
type SyncMaterialInformation *SyncMaterialInformationType

// GetMaterialClass ...
type GetMaterialClass *GetMaterialClassType

// ShowMaterialClass ...
type ShowMaterialClass *ShowMaterialClassType

// ProcessMaterialClass ...
type ProcessMaterialClass *ProcessMaterialClassType

// AcknowledgeMaterialClass ...
type AcknowledgeMaterialClass *AcknowledgeMaterialClassType

// ChangeMaterialClass ...
type ChangeMaterialClass *ChangeMaterialClassType

// RespondMaterialClass ...
type RespondMaterialClass *RespondMaterialClassType

// CancelMaterialClass ...
type CancelMaterialClass *CancelMaterialClassType

// SyncMaterialClass ...
type SyncMaterialClass *SyncMaterialClassType

// GetMaterialDefinition ...
type GetMaterialDefinition *GetMaterialDefinitionType

// ShowMaterialDefinition ...
type ShowMaterialDefinition *ShowMaterialDefinitionType

// ProcessMaterialDefinition ...
type ProcessMaterialDefinition *ProcessMaterialDefinitionType

// AcknowledgeMaterialDefinition ...
type AcknowledgeMaterialDefinition *AcknowledgeMaterialDefinitionType

// ChangeMaterialDefinition ...
type ChangeMaterialDefinition *ChangeMaterialDefinitionType

// RespondMaterialDefinition ...
type RespondMaterialDefinition *RespondMaterialDefinitionType

// CancelMaterialDefinition ...
type CancelMaterialDefinition *CancelMaterialDefinitionType

// SyncMaterialDefinition ...
type SyncMaterialDefinition *SyncMaterialDefinitionType

// GetMaterialLot ...
type GetMaterialLot *GetMaterialLotType

// ShowMaterialLot ...
type ShowMaterialLot *ShowMaterialLotType

// ProcessMaterialLot ...
type ProcessMaterialLot *ProcessMaterialLotType

// AcknowledgeMaterialLot ...
type AcknowledgeMaterialLot *AcknowledgeMaterialLotType

// ChangeMaterialLot ...
type ChangeMaterialLot *ChangeMaterialLotType

// RespondMaterialLot ...
type RespondMaterialLot *RespondMaterialLotType

// CancelMaterialLot ...
type CancelMaterialLot *CancelMaterialLotType

// SyncMaterialLot ...
type SyncMaterialLot *SyncMaterialLotType

// GetMaterialSubLot ...
type GetMaterialSubLot *GetMaterialSubLotType

// ShowMaterialSubLot ...
type ShowMaterialSubLot *ShowMaterialSubLotType

// ProcessMaterialSubLot ...
type ProcessMaterialSubLot *ProcessMaterialSubLotType

// AcknowledgeMaterialSubLot ...
type AcknowledgeMaterialSubLot *AcknowledgeMaterialSubLotType

// ChangeMaterialSubLot ...
type ChangeMaterialSubLot *ChangeMaterialSubLotType

// RespondMaterialSubLot ...
type RespondMaterialSubLot *RespondMaterialSubLotType

// CancelMaterialSubLot ...
type CancelMaterialSubLot *CancelMaterialSubLotType

// SyncMaterialSubLot ...
type SyncMaterialSubLot *SyncMaterialSubLotType

// MaterialInformationType ...
type MaterialInformationType struct {
	ExtendedMaterialInformation []*MaterialInformationType
	ID                          *IdentifierType           `xml:"ID"`
	Description                 []*DescriptionType        `xml:"Description"`
	HierarchyScope              *HierarchyScopeType       `xml:"HierarchyScope"`
	PublishedDate               *DateTimeType             `xml:"PublishedDate"`
	MaterialClass               []*MaterialClassType      `xml:"MaterialClass"`
	MaterialDefinition          []*MaterialDefinitionType `xml:"MaterialDefinition"`
	MaterialLot                 []*MaterialLotType        `xml:"MaterialLot"`
	MaterialSubLot              []*MaterialSubLotType     `xml:"MaterialSubLot"`
	TestSpecification           []*TestSpecificationType  `xml:"TestSpecification"`
}

// MaterialClassType ...
type MaterialClassType struct {
	ExtendedMaterialClass      *MaterialClassType
	ID                         *IdentifierType              `xml:"ID"`
	Version                    *IdentifierType              `xml:"Version"`
	Description                []*DescriptionType           `xml:"Description"`
	PublishedDate              *DateTimeType                `xml:"PublishedDate"`
	EffectiveStartDate         *DateTimeType                `xml:"EffectiveStartDate"`
	EffectiveEndDate           *DateTimeType                `xml:"EffectiveEndDate"`
	HierarchyScope             *HierarchyScopeType          `xml:"HierarchyScope"`
	MaterialClassBaseID        []*IdentifierType            `xml:"MaterialClassBaseID"`
	MaterialClassProperty      []*MaterialClassPropertyType `xml:"MaterialClassProperty"`
	MaterialDefinitionSourceID []*IdentifierType            `xml:"MaterialDefinitionSourceID"`
	TestSpecificationID        []*IdentifierType            `xml:"TestSpecificationID"`
	AssemblyClass              []*MaterialClassType         `xml:"AssemblyClass"`
	AssemblyType               *AssemblyTypeType            `xml:"AssemblyType"`
	AssemblyRelationship       *AssemblyRelationshipType    `xml:"AssemblyRelationship"`
}

// MaterialClassPropertyType ...
type MaterialClassPropertyType struct {
	ExtendedMaterialClassProperty *MaterialClassProperty
	ID                            *IdentifierType              `xml:"ID"`
	Description                   []*DescriptionType           `xml:"Description"`
	PropertyType                  *ClassPropertyTypeType       `xml:"PropertyType"`
	Value                         []*ValueType                 `xml:"Value"`
	MaterialClassPropertyChild    []*MaterialClassPropertyType `xml:"MaterialClassPropertyChild"`
}

// MaterialDefinitionType ...
type MaterialDefinitionType struct {
	ExtendedMaterialDefinition *MaterialDefinitionType
	ID                         *IdentifierType                   `xml:"ID"`
	Version                    *IdentifierType                   `xml:"Version"`
	Description                []*DescriptionType                `xml:"Description"`
	PublishedDate              *DateTimeType                     `xml:"PublishedDate"`
	EffectiveStartDate         *DateTimeType                     `xml:"EffectiveStartDate"`
	EffectiveEndDate           *DateTimeType                     `xml:"EffectiveEndDate"`
	HierarchyScope             *HierarchyScopeType               `xml:"HierarchyScope"`
	SpatialDefinition          *SpatialDefinitionType            `xml:"SpatialDefinition"`
	MaterialDefinitionProperty []*MaterialDefinitionPropertyType `xml:"MaterialDefinitionProperty"`
	MaterialClassID            []*IdentifierType                 `xml:"MaterialClassID"`
	MaterialLotSourceID        []*IdentifierType                 `xml:"MaterialLotSourceID"`
	TestSpecificationID        []*IdentifierType                 `xml:"TestSpecificationID"`
	AssemblyDefinition         []*MaterialDefinitionType         `xml:"AssemblyDefinition"`
	AssemblyType               *AssemblyTypeType                 `xml:"AssemblyType"`
	AssemblyRelationship       *AssemblyRelationshipType         `xml:"AssemblyRelationship"`
}

// MaterialDefinitionPropertyType ...
type MaterialDefinitionPropertyType struct {
	ExtendedMaterialDefinitionProperty *MaterialDefinitionProperty
	ID                                 *IdentifierType                   `xml:"ID"`
	Version                            *IdentifierType                   `xml:"Version"`
	Description                        []*DescriptionType                `xml:"Description"`
	PropertyType                       *ClassPropertyTypeType            `xml:"PropertyType"`
	Value                              []*ValueType                      `xml:"Value"`
	MaterialDefinitionPropertyChild    []*MaterialDefinitionPropertyType `xml:"MaterialDefinitionPropertyChild"`
	MaterialClassPropertyID            *IdentifierType                   `xml:"MaterialClassPropertyID"`
}

// MaterialLotType ...
type MaterialLotType struct {
	ExtendedMaterialLot  *MaterialLotType
	ID                   *IdentifierType            `xml:"ID"`
	Version              *IdentifierType            `xml:"Version"`
	Description          []*DescriptionType         `xml:"Description"`
	PublishedDate        *DateTimeType              `xml:"PublishedDate"`
	EffectiveStartDate   *DateTimeType              `xml:"EffectiveStartDate"`
	EffectiveEndDate     *DateTimeType              `xml:"EffectiveEndDate"`
	HierarchyScope       *HierarchyScopeType        `xml:"HierarchyScope"`
	SpatialDefinition    *SpatialDefinitionType     `xml:"SpatialDefinition"`
	MaterialDefinitionID *IdentifierType            `xml:"MaterialDefinitionID"`
	Status               *StatusType                `xml:"Status"`
	Disposition          *DispositionType           `xml:"Disposition"`
	MaterialLotProperty  []*MaterialLotPropertyType `xml:"MaterialLotProperty"`
	MaterialSubLot       []*MaterialSubLotType      `xml:"MaterialSubLot"`
	StorageLocation      *ResourceLocationType      `xml:"StorageLocation"`
	Quantity             []*QuantityValueType       `xml:"Quantity"`
	TestSpecificationID  []*IdentifierType          `xml:"TestSpecificationID"`
	AssemblyLot          []*MaterialLotType         `xml:"AssemblyLot"`
	AssemblySubLot       []*MaterialSubLotType      `xml:"AssemblySubLot"`
	AssemblyType         *AssemblyTypeType          `xml:"AssemblyType"`
	AssemblyRelationship *AssemblyRelationshipType  `xml:"AssemblyRelationship"`
}

// MaterialLotPropertyType ...
type MaterialLotPropertyType struct {
	ExtendedMaterialLotProperty  *MaterialLotProperty
	ID                           *IdentifierType            `xml:"ID"`
	Description                  []*DescriptionType         `xml:"Description"`
	Value                        []*ValueType               `xml:"Value"`
	MaterialLotPropertyChild     []*MaterialLotPropertyType `xml:"MaterialLotPropertyChild"`
	MaterialDefinitionPropertyID *IdentifierType            `xml:"MaterialDefinitionPropertyID"`
}

// MaterialSubLotType ...
type MaterialSubLotType struct {
	ExtendedMaterialSubLot *MaterialSubLotType
	ID                     *IdentifierType            `xml:"ID"`
	Version                *IdentifierType            `xml:"Version"`
	Description            []*DescriptionType         `xml:"Description"`
	PublishedDate          *DateTimeType              `xml:"PublishedDate"`
	EffectiveStartDate     *DateTimeType              `xml:"EffectiveStartDate"`
	EffectiveEndDate       *DateTimeType              `xml:"EffectiveEndDate"`
	HierarchyScope         *HierarchyScopeType        `xml:"HierarchyScope"`
	SpatialDefinition      *SpatialDefinitionType     `xml:"SpatialDefinition"`
	Status                 *StatusType                `xml:"Status"`
	Disposition            *DispositionType           `xml:"Disposition"`
	MaterialLotProperty    []*MaterialLotPropertyType `xml:"MaterialLotProperty"`
	StorageLocation        *ResourceLocationType      `xml:"StorageLocation"`
	Quantity               []*QuantityValueType       `xml:"Quantity"`
	TestSpecificationID    []*IdentifierType          `xml:"TestSpecificationID"`
	MaterialSubLotChild    []*MaterialSubLotType      `xml:"MaterialSubLotChild"`
	MaterialLotID          *IdentifierType            `xml:"MaterialLotID"`
	AssemblyLot            []*MaterialLotType         `xml:"AssemblyLot"`
	AssemblySubLot         []*MaterialSubLotType      `xml:"AssemblySubLot"`
	AssemblyType           *AssemblyTypeType          `xml:"AssemblyType"`
	AssemblyRelationship   *AssemblyRelationshipType  `xml:"AssemblyRelationship"`
}

// DataArea ...
// type DataArea struct {
// 	Get                 *TransGetType              `xml:"Get"`
// 	MaterialInformation []*MaterialInformationType `xml:"MaterialInformation"`
// }

// GetMaterialInformationType ...
type GetMaterialInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ShowMaterialInformationType ...
type ShowMaterialInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ProcessMaterialInformationType ...
type ProcessMaterialInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// AcknowledgeMaterialInformationType ...
type AcknowledgeMaterialInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ChangeMaterialInformationType ...
type ChangeMaterialInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// RespondMaterialInformationType ...
type RespondMaterialInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// CancelMaterialInformationType ...
type CancelMaterialInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// SyncMaterialInformationType ...
type SyncMaterialInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// GetMaterialClassType ...
type GetMaterialClassType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ShowMaterialClassType ...
type ShowMaterialClassType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ProcessMaterialClassType ...
type ProcessMaterialClassType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// AcknowledgeMaterialClassType ...
type AcknowledgeMaterialClassType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ChangeMaterialClassType ...
type ChangeMaterialClassType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// RespondMaterialClassType ...
type RespondMaterialClassType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// CancelMaterialClassType ...
type CancelMaterialClassType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// SyncMaterialClassType ...
type SyncMaterialClassType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// GetMaterialDefinitionType ...
type GetMaterialDefinitionType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ShowMaterialDefinitionType ...
type ShowMaterialDefinitionType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ProcessMaterialDefinitionType ...
type ProcessMaterialDefinitionType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// AcknowledgeMaterialDefinitionType ...
type AcknowledgeMaterialDefinitionType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ChangeMaterialDefinitionType ...
type ChangeMaterialDefinitionType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// RespondMaterialDefinitionType ...
type RespondMaterialDefinitionType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// CancelMaterialDefinitionType ...
type CancelMaterialDefinitionType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// SyncMaterialDefinitionType ...
type SyncMaterialDefinitionType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// GetMaterialLotType ...
type GetMaterialLotType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ShowMaterialLotType ...
type ShowMaterialLotType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ProcessMaterialLotType ...
type ProcessMaterialLotType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// AcknowledgeMaterialLotType ...
type AcknowledgeMaterialLotType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ChangeMaterialLotType ...
type ChangeMaterialLotType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// RespondMaterialLotType ...
type RespondMaterialLotType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// CancelMaterialLotType ...
type CancelMaterialLotType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// SyncMaterialLotType ...
type SyncMaterialLotType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// GetMaterialSubLotType ...
type GetMaterialSubLotType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ShowMaterialSubLotType ...
type ShowMaterialSubLotType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ProcessMaterialSubLotType ...
type ProcessMaterialSubLotType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// AcknowledgeMaterialSubLotType ...
type AcknowledgeMaterialSubLotType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ChangeMaterialSubLotType ...
type ChangeMaterialSubLotType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// RespondMaterialSubLotType ...
type RespondMaterialSubLotType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// CancelMaterialSubLotType ...
type CancelMaterialSubLotType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// SyncMaterialSubLotType ...
type SyncMaterialSubLotType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}
