// Code generated by xgen. DO NOT EDIT.

package b2mml

// PhysicalAssetInformation is The physical asset model contains information about the physical piece of equipment,
// usually managed as a physical asset within the enterprise often utilizing a specific
// serial number. An object in the equipment model defines a role for the equipment,
// and object in the physical asset model defines the physical asset ID and properties
// of a piece of equipment.
type PhysicalAssetInformation *PhysicalAssetInformationType

// PhysicalAsset is A representation of a physical piece of equipment is a physical asset.
type PhysicalAsset *PhysicalAssetType

// PhysicalAssetClass is A representation of a grouping of physical assets with similar characteristics
// for purposes of repair and replacement is a physical asset class. Any physical
// asset is a member of one physical asset class. A physical asset class may be
// defined as a specialization of zero or more physical asset classes.
// A physical asset class may be made up of zero or more physical asset classes.
type PhysicalAssetClass *PhysicalAssetClassType

// GetPhysicalAssetInformation ...
type GetPhysicalAssetInformation *GetPhysicalAssetInformationType

// ShowPhysicalAssetInformation ...
type ShowPhysicalAssetInformation *ShowPhysicalAssetInformationType

// ProcessPhysicalAssetInformation ...
type ProcessPhysicalAssetInformation *ProcessPhysicalAssetInformationType

// AcknowledgePhysicalAssetInformation ...
type AcknowledgePhysicalAssetInformation *AcknowledgePhysicalAssetInformationType

// ChangePhysicalAssetInformation ...
type ChangePhysicalAssetInformation *ChangePhysicalAssetInformationType

// RespondPhysicalAssetInformation ...
type RespondPhysicalAssetInformation *RespondPhysicalAssetInformationType

// CancelPhysicalAssetInformation ...
type CancelPhysicalAssetInformation *CancelPhysicalAssetInformationType

// SyncPhysicalAssetInformation ...
type SyncPhysicalAssetInformation *SyncPhysicalAssetInformationType

// GetPhysicalAssetClass ...
type GetPhysicalAssetClass *GetPhysicalAssetClassType

// ShowPhysicalAssetClass ...
type ShowPhysicalAssetClass *ShowPhysicalAssetClassType

// ProcessPhysicalAssetClass ...
type ProcessPhysicalAssetClass *ProcessPhysicalAssetClassType

// AcknowledgePhysicalAssetClass ...
type AcknowledgePhysicalAssetClass *AcknowledgePhysicalAssetClassType

// ChangePhysicalAssetClass ...
type ChangePhysicalAssetClass *ChangePhysicalAssetClassType

// RespondPhysicalAssetClass ...
type RespondPhysicalAssetClass *RespondPhysicalAssetClassType

// CancelPhysicalAssetClass ...
type CancelPhysicalAssetClass *CancelPhysicalAssetClassType

// SyncPhysicalAssetClass ...
type SyncPhysicalAssetClass *SyncPhysicalAssetClassType

// GetPhysicalAsset ...
type GetPhysicalAsset *GetPhysicalAssetType

// ShowPhysicalAsset ...
type ShowPhysicalAsset *ShowPhysicalAssetType

// ProcessPhysicalAsset ...
type ProcessPhysicalAsset *ProcessPhysicalAssetType

// AcknowledgePhysicalAsset ...
type AcknowledgePhysicalAsset *AcknowledgePhysicalAssetType

// ChangePhysicalAsset ...
type ChangePhysicalAsset *ChangePhysicalAssetType

// RespondPhysicalAsset ...
type RespondPhysicalAsset *RespondPhysicalAssetType

// CancelPhysicalAsset ...
type CancelPhysicalAsset *CancelPhysicalAssetType

// SyncPhysicalAsset ...
type SyncPhysicalAsset *SyncPhysicalAssetType

// PhysicalAssetInformationType ...
type PhysicalAssetInformationType struct {
	ExtendedPhysicalAssetInformation *PhysicalAssetInformationType
	ID                               *IdentifierType           `xml:"ID"`
	Description                      []*DescriptionType        `xml:"Description"`
	HierarchyScope                   *HierarchyScopeType       `xml:"HierarchyScope"`
	PublishedDate                    *DateTimeType             `xml:"PublishedDate"`
	PhysicalAsset                    []*PhysicalAssetType      `xml:"PhysicalAsset"`
	PhysicalAssetClass               []*PhysicalAssetClassType `xml:"PhysicalAssetClass"`
	TestSpecification                []*TestSpecificationType  `xml:"TestSpecification"`
}

// PhysicalAssetType ...
type PhysicalAssetType struct {
	ExtendedPhysicalAsset *PhysicalAssetType
	ID                    *IdentifierType              `xml:"ID"`
	Description           []*DescriptionType           `xml:"Description"`
	Version               *IdentifierType              `xml:"Version"`
	PublishedDate         *DateTimeType                `xml:"PublishedDate"`
	EffectiveStartDate    *DateTimeType                `xml:"EffectiveStartDate"`
	EffectiveEndDate      *DateTimeType                `xml:"EffectiveEndDate"`
	HierarchyScope        *HierarchyScopeType          `xml:"HierarchyScope"`
	FixedAssetID          *IdentifierType              `xml:"FixedAssetID"`
	VendorID              *IdentifierType              `xml:"VendorID"`
	SpatialDefinition     *SpatialDefinitionType       `xml:"SpatialDefinition"`
	PhysicalLocation      *ResourceLocationType        `xml:"PhysicalLocation"`
	EquipmentLevel        *HierarchyScopeType          `xml:"EquipmentLevel"`
	EquipmentAssetMapping []*EquipmentAssetMappingType `xml:"EquipmentAssetMapping"`
	PhysicalAssetProperty []*PhysicalAssetPropertyType `xml:"PhysicalAssetProperty"`
	PhysicalAssetChild    []*PhysicalAssetType         `xml:"PhysicalAssetChild"`
	PhysicalAssetClassID  []*IdentifierType            `xml:"PhysicalAssetClassID"`
	TestSpecificationID   []*IdentifierType            `xml:"TestSpecificationID"`
}

// PhysicalAssetPropertyType ...
type PhysicalAssetPropertyType struct {
	ExtendedPhysicalAssetProperty *PhysicalAssetProperty
	ID                            *IdentifierType              `xml:"ID"`
	Description                   []*DescriptionType           `xml:"Description"`
	Value                         []*ValueType                 `xml:"Value"`
	PhysicalAssetPropertyChild    []*PhysicalAssetPropertyType `xml:"PhysicalAssetPropertyChild"`
	PhysicalAssetClassPropertyID  *IdentifierType              `xml:"PhysicalAssetClassPropertyID"`
}

// PhysicalAssetClassType ...
type PhysicalAssetClassType struct {
	ExtendedPhysicalAssetClass *PhysicalAssetClassType
	ID                         *IdentifierType                   `xml:"ID"`
	Version                    *IdentifierType                   `xml:"Version"`
	Description                []*DescriptionType                `xml:"Description"`
	PublishedDate              *DateTimeType                     `xml:"PublishedDate"`
	EffectiveStartDate         *DateTimeType                     `xml:"EffectiveStartDate"`
	EffectiveEndDate           *DateTimeType                     `xml:"EffectiveEndDate"`
	HierarchyScope             *HierarchyScopeType               `xml:"HierarchyScope"`
	Manufacturer               []*NameType                       `xml:"Manufacturer"`
	PhysicalAssetClassChild    []*PhysicalAssetClassType         `xml:"PhysicalAssetClassChild"`
	PhysicalAssetClassProperty []*PhysicalAssetClassPropertyType `xml:"PhysicalAssetClassProperty"`
	PhysicalAssetClassBaseID   []*IdentifierType                 `xml:"PhysicalAssetClassBaseID"`
	PhysicalAssetSourceID      []*IdentifierType                 `xml:"PhysicalAssetSourceID"`
	TestSpecificationID        []*IdentifierType                 `xml:"TestSpecificationID"`
}

// PhysicalAssetClassPropertyType ...
type PhysicalAssetClassPropertyType struct {
	ExtendedPhysicalAssetClassProperty *PhysicalAssetClassProperty
	ID                                 *IdentifierType                   `xml:"ID"`
	Description                        []*DescriptionType                `xml:"Description"`
	PropertyType                       *ClassPropertyTypeType            `xml:"PropertyType"`
	Value                              []*ValueType                      `xml:"Value"`
	PhysicalAssetClassPropertyChild    []*PhysicalAssetClassPropertyType `xml:"PhysicalAssetClassPropertyChild"`
}

// DataArea ...
type DataArea struct {
	Get                      *TransGetType                   `xml:"Get"`
	PhysicalAssetInformation []*PhysicalAssetInformationType `xml:"PhysicalAssetInformation"`
}

// GetPhysicalAssetInformationType ...
type GetPhysicalAssetInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ShowPhysicalAssetInformationType ...
type ShowPhysicalAssetInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ProcessPhysicalAssetInformationType ...
type ProcessPhysicalAssetInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// AcknowledgePhysicalAssetInformationType ...
type AcknowledgePhysicalAssetInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ChangePhysicalAssetInformationType ...
type ChangePhysicalAssetInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// RespondPhysicalAssetInformationType ...
type RespondPhysicalAssetInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// CancelPhysicalAssetInformationType ...
type CancelPhysicalAssetInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// SyncPhysicalAssetInformationType ...
type SyncPhysicalAssetInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// GetPhysicalAssetClassType ...
type GetPhysicalAssetClassType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ShowPhysicalAssetClassType ...
type ShowPhysicalAssetClassType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ProcessPhysicalAssetClassType ...
type ProcessPhysicalAssetClassType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// AcknowledgePhysicalAssetClassType ...
type AcknowledgePhysicalAssetClassType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ChangePhysicalAssetClassType ...
type ChangePhysicalAssetClassType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// RespondPhysicalAssetClassType ...
type RespondPhysicalAssetClassType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// CancelPhysicalAssetClassType ...
type CancelPhysicalAssetClassType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// SyncPhysicalAssetClassType ...
type SyncPhysicalAssetClassType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// GetPhysicalAssetType ...
type GetPhysicalAssetType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ShowPhysicalAssetType ...
type ShowPhysicalAssetType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ProcessPhysicalAssetType ...
type ProcessPhysicalAssetType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// AcknowledgePhysicalAssetType ...
type AcknowledgePhysicalAssetType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ChangePhysicalAssetType ...
type ChangePhysicalAssetType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// RespondPhysicalAssetType ...
type RespondPhysicalAssetType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// CancelPhysicalAssetType ...
type CancelPhysicalAssetType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// SyncPhysicalAssetType ...
type SyncPhysicalAssetType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}
