// Code generated by xgen. DO NOT EDIT.

package b2mml

// WorkflowSpecificationInformation ...
type WorkflowSpecificationInformation *WorkflowSpecificationInformationType

// WorkflowSpecification ...
type WorkflowSpecification *WorkflowSpecificationType

// WorkflowSpecificationNodeType ...
type WorkflowSpecificationNodeType *WorkflowSpecificationNodeTypeType

// WorkflowSpecificationConnectionType ...
type WorkflowSpecificationConnectionType *WorkflowSpecificationConnectionTypeType

// GetWorkflowSpecificationInformation ...
type GetWorkflowSpecificationInformation *GetWorkflowSpecificationInformationType

// ShowWorkflowSpecificationInformation ...
type ShowWorkflowSpecificationInformation *ShowWorkflowSpecificationInformationType

// ProcessWorkflowSpecificationInformation ...
type ProcessWorkflowSpecificationInformation *ProcessWorkflowSpecificationInformationType

// AcknowledgeWorkflowSpecificationInformation ...
type AcknowledgeWorkflowSpecificationInformation *AcknowledgeWorkflowSpecificationInformationType

// ChangeWorkflowSpecificationInformation ...
type ChangeWorkflowSpecificationInformation *ChangeWorkflowSpecificationInformationType

// RespondWorkflowSpecificationInformation ...
type RespondWorkflowSpecificationInformation *RespondWorkflowSpecificationInformationType

// CancelWorkflowSpecificationInformation ...
type CancelWorkflowSpecificationInformation *CancelWorkflowSpecificationInformationType

// SyncWorkflowSpecificationInformation ...
type SyncWorkflowSpecificationInformation *SyncWorkflowSpecificationInformationType

// GetWorkflowSpecification ...
type GetWorkflowSpecification *GetWorkflowSpecificationType

// ShowWorkflowSpecification ...
type ShowWorkflowSpecification *ShowWorkflowSpecificationType

// ProcessWorkflowSpecification ...
type ProcessWorkflowSpecification *ProcessWorkflowSpecificationType

// AcknowledgeWorkflowSpecification ...
type AcknowledgeWorkflowSpecification *AcknowledgeWorkflowSpecificationType

// ChangeWorkflowSpecification ...
type ChangeWorkflowSpecification *ChangeWorkflowSpecificationType

// RespondWorkflowSpecification ...
type RespondWorkflowSpecification *RespondWorkflowSpecificationType

// CancelWorkflowSpecification ...
type CancelWorkflowSpecification *CancelWorkflowSpecificationType

// SyncWorkflowSpecification ...
type SyncWorkflowSpecification *SyncWorkflowSpecificationType

// GetWorkflowSpecificationNodeType ...
type GetWorkflowSpecificationNodeType *GetWorkflowSpecificationNodeTypeType

// ShowWorkflowSpecificationNodeType ...
type ShowWorkflowSpecificationNodeType *ShowWorkflowSpecificationNodeTypeType

// ProcessWorkflowSpecificationNodeType ...
type ProcessWorkflowSpecificationNodeType *ProcessWorkflowSpecificationNodeTypeType

// AcknowledgeWorkflowSpecificationNodeType ...
type AcknowledgeWorkflowSpecificationNodeType *AcknowledgeWorkflowSpecificationNodeTypeType

// ChangeWorkflowSpecificationNodeType ...
type ChangeWorkflowSpecificationNodeType *ChangeWorkflowSpecificationNodeTypeType

// RespondWorkflowSpecificationNodeType ...
type RespondWorkflowSpecificationNodeType *RespondWorkflowSpecificationNodeTypeType

// CancelWorkflowSpecificationNodeType ...
type CancelWorkflowSpecificationNodeType *CancelWorkflowSpecificationNodeTypeType

// SyncWorkflowSpecificationNodeType ...
type SyncWorkflowSpecificationNodeType *SyncWorkflowSpecificationNodeTypeType

// GetWorkflowSpecificationConnectionType ...
type GetWorkflowSpecificationConnectionType *GetWorkflowSpecificationConnectionTypeType

// ShowWorkflowSpecificationConnectionType ...
type ShowWorkflowSpecificationConnectionType *ShowWorkflowSpecificationConnectionTypeType

// ProcessWorkflowSpecificationConnectionType ...
type ProcessWorkflowSpecificationConnectionType *ProcessWorkflowSpecificationConnectionTypeType

// AcknowledgeWorkflowSpecificationConnectionType ...
type AcknowledgeWorkflowSpecificationConnectionType *AcknowledgeWorkflowSpecificationConnectionTypeType

// ChangeWorkflowSpecificationConnectionType ...
type ChangeWorkflowSpecificationConnectionType *ChangeWorkflowSpecificationConnectionTypeType

// RespondWorkflowSpecificationConnectionType ...
type RespondWorkflowSpecificationConnectionType *RespondWorkflowSpecificationConnectionTypeType

// CancelWorkflowSpecificationConnectionType ...
type CancelWorkflowSpecificationConnectionType *CancelWorkflowSpecificationConnectionTypeType

// SyncWorkflowSpecificationConnectionType ...
type SyncWorkflowSpecificationConnectionType *SyncWorkflowSpecificationConnectionTypeType

// WorkflowSpecificationInformationType ...
type WorkflowSpecificationInformationType struct {
	ExtendedWorkflowSpecificationInformation *WorkflowSpecificationInformationType
	ID                                       *IdentifierType                            `xml:"ID"`
	Description                              []*DescriptionType                         `xml:"Description"`
	HierarchyScope                           *HierarchyScopeType                        `xml:"HierarchyScope"`
	PublishedDate                            *DateTimeType                              `xml:"PublishedDate"`
	WorkflowSpecification                    []*WorkflowSpecificationType               `xml:"WorkflowSpecification"`
	WorkflowSpecificationNodeType            []*WorkflowSpecificationNodeTypeType       `xml:"WorkflowSpecificationNodeType"`
	WorkflowSpecificationConnectionType      []*WorkflowSpecificationConnectionTypeType `xml:"WorkflowSpecificationConnectionType"`
}

// WorkflowSpecificationType ...
type WorkflowSpecificationType struct {
	ExtendedWorkflowSpecification   *WorkflowSpecificationType
	ID                              *IdentifierType                            `xml:"ID"`
	Description                     []*DescriptionType                         `xml:"Description"`
	Version                         *IdentifierType                            `xml:"Version"`
	PublishedDate                   *DateTimeType                              `xml:"PublishedDate"`
	EffectiveStartDate              *DateTimeType                              `xml:"EffectiveStartDate"`
	EffectiveEndDate                *DateTimeType                              `xml:"EffectiveEndDate"`
	HierarchyScope                  *HierarchyScopeType                        `xml:"HierarchyScope"`
	DefinitionType                  *DefinitionTypeType                        `xml:"DefinitionType"`
	WorkflowSpecificationNode       []*WorkflowSpecificationNodeTypeType       `xml:"WorkflowSpecificationNode"`
	WorkflowSpecificationConnection []*WorkflowSpecificationConnectionTypeType `xml:"WorkflowSpecificationConnection"`
	WorkflowSpecificationPatternID  *IdentifierType                            `xml:"WorkflowSpecificationPatternID"`
	WorkflowSpecificationProperty   []*WorkflowSpecificationPropertyType       `xml:"WorkflowSpecificationProperty"`
}

// WorkflowSpecificationNodeTypeType ...
type WorkflowSpecificationNodeTypeType struct {
	ExtendedWorkflowSpecificationNodeType *WorkflowSpecificationNodeTypeType
	ID                                    *IdentifierType                              `xml:"ID"`
	Description                           []*DescriptionType                           `xml:"Description"`
	Version                               *IdentifierType                              `xml:"Version"`
	PublishedDate                         *DateTimeType                                `xml:"PublishedDate"`
	EffectiveStartDate                    *DateTimeType                                `xml:"EffectiveStartDate"`
	EffectiveEndDate                      *DateTimeType                                `xml:"EffectiveEndDate"`
	HierarchyScope                        *HierarchyScopeType                          `xml:"HierarchyScope"`
	WorkflowSpecificationNodeTypeBaseID   []*IdentifierType                            `xml:"WorkflowSpecificationNodeTypeBaseID"`
	WorkflowSpecificationNodeTypeProperty []*WorkflowSpecificationNodeTypePropertyType `xml:"WorkflowSpecificationNodeTypeProperty"`
}

// WorkflowSpecificationConnectionTypeType ...
type WorkflowSpecificationConnectionTypeType struct {
	ExtendedWorkflowSpecificationConnectionType *WorkflowSpecificationConnectionTypeType
	ID                                          *IdentifierType                                    `xml:"ID"`
	Description                                 []*DescriptionType                                 `xml:"Description"`
	Version                                     *IdentifierType                                    `xml:"Version"`
	PublishedDate                               *DateTimeType                                      `xml:"PublishedDate"`
	EffectiveStartDate                          *DateTimeType                                      `xml:"EffectiveStartDate"`
	EffectiveEndDate                            *DateTimeType                                      `xml:"EffectiveEndDate"`
	HierarchyScope                              *HierarchyScopeType                                `xml:"HierarchyScope"`
	FromWSNodeMultiplicity                      *DescriptionType                                   `xml:"FromWSNodeMultiplicity"`
	ToWSNodeMultiplicity                        *DescriptionType                                   `xml:"ToWSNodeMultiplicity"`
	Dependency                                  *DependencyType                                    `xml:"Dependency"`
	DependencyFactor                            *ValueType                                         `xml:"DependencyFactor"`
	WorkflowSpecificationConnectionTypeBaseID   []*IdentifierType                                  `xml:"WorkflowSpecificationConnectionTypeBaseID"`
	WorkflowSpecificationConnectionTypeProperty []*WorkflowSpecificationConnectionTypePropertyType `xml:"WorkflowSpecificationConnectionTypeProperty"`
}

// WorkflowSpecificationPropertyType ...
type WorkflowSpecificationPropertyType struct {
	ExtendedWorkflowSpecificationProperty *WorkflowSpecificationProperty
	ID                                    *IdentifierType                      `xml:"ID"`
	Description                           []*DescriptionType                   `xml:"Description"`
	Value                                 []*ValueType                         `xml:"Value"`
	WorkflowSpecificationPropertyChild    []*WorkflowSpecificationPropertyType `xml:"WorkflowSpecificationPropertyChild"`
}

// WorkflowSpecificationNodePropertyType ...
type WorkflowSpecificationNodePropertyType struct {
	ExtendedWorkflowSpecificationNodeProperty *WorkflowSpecificationNodeProperty
	ID                                        *IdentifierType                          `xml:"ID"`
	Description                               []*DescriptionType                       `xml:"Description"`
	Value                                     []*ValueType                             `xml:"Value"`
	WorkflowSpecificationNodeTypePropertyID   *IdentifierType                          `xml:"WorkflowSpecificationNodeTypePropertyID"`
	WorkflowSpecificationNodePropertyChild    []*WorkflowSpecificationNodePropertyType `xml:"WorkflowSpecificationNodePropertyChild"`
}

// WorkflowSpecificationConnectionPropertyType ...
type WorkflowSpecificationConnectionPropertyType struct {
	ExtendedWorkflowSpecificationConnectionProperty *WorkflowSpecificationConnectionProperty
	ID                                              *IdentifierType                                `xml:"ID"`
	Description                                     []*DescriptionType                             `xml:"Description"`
	Value                                           []*ValueType                                   `xml:"Value"`
	WorkflowSpecificationConnectionTypePropertyID   *IdentifierType                                `xml:"WorkflowSpecificationConnectionTypePropertyID"`
	WorkflowSpecificationConnectionPropertyChild    []*WorkflowSpecificationConnectionPropertyType `xml:"WorkflowSpecificationConnectionPropertyChild"`
}

// WorkflowSpecificationNodeTypePropertyType ...
type WorkflowSpecificationNodeTypePropertyType struct {
	ExtendedWorkflowSpecificationNodeTypeProperty *WorkflowSpecificationNodeTypeProperty
	ID                                            *IdentifierType                              `xml:"ID"`
	Description                                   []*DescriptionType                           `xml:"Description"`
	Value                                         []*ValueType                                 `xml:"Value"`
	WorkflowSpecificationNodeTypePropertyChild    []*WorkflowSpecificationNodeTypePropertyType `xml:"WorkflowSpecificationNodeTypePropertyChild"`
}

// WorkflowSpecificationConnectionTypePropertyType ...
type WorkflowSpecificationConnectionTypePropertyType struct {
	ExtendedWorkflowSpecificationConnectionTypeProperty *WorkflowSpecificationConnectionTypeProperty
	ID                                                  *IdentifierType                                    `xml:"ID"`
	Description                                         []*DescriptionType                                 `xml:"Description"`
	Value                                               []*ValueType                                       `xml:"Value"`
	WorkflowSpecificationConnectionTypePropertyChild    []*WorkflowSpecificationConnectionTypePropertyType `xml:"WorkflowSpecificationConnectionTypePropertyChild"`
}

// DataArea ...
type DataArea struct {
	Get                              *TransGetType                           `xml:"Get"`
	WorkflowSpecificationInformation []*WorkflowSpecificationInformationType `xml:"WorkflowSpecificationInformation"`
}

// GetWorkflowSpecificationInformationType ...
type GetWorkflowSpecificationInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ShowWorkflowSpecificationInformationType ...
type ShowWorkflowSpecificationInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ProcessWorkflowSpecificationInformationType ...
type ProcessWorkflowSpecificationInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// AcknowledgeWorkflowSpecificationInformationType ...
type AcknowledgeWorkflowSpecificationInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ChangeWorkflowSpecificationInformationType ...
type ChangeWorkflowSpecificationInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// RespondWorkflowSpecificationInformationType ...
type RespondWorkflowSpecificationInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// CancelWorkflowSpecificationInformationType ...
type CancelWorkflowSpecificationInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// SyncWorkflowSpecificationInformationType ...
type SyncWorkflowSpecificationInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// GetWorkflowSpecificationType ...
type GetWorkflowSpecificationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ShowWorkflowSpecificationType ...
type ShowWorkflowSpecificationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ProcessWorkflowSpecificationType ...
type ProcessWorkflowSpecificationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// AcknowledgeWorkflowSpecificationType ...
type AcknowledgeWorkflowSpecificationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ChangeWorkflowSpecificationType ...
type ChangeWorkflowSpecificationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// RespondWorkflowSpecificationType ...
type RespondWorkflowSpecificationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// CancelWorkflowSpecificationType ...
type CancelWorkflowSpecificationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// SyncWorkflowSpecificationType ...
type SyncWorkflowSpecificationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// GetWorkflowSpecificationNodeTypeType ...
type GetWorkflowSpecificationNodeTypeType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ShowWorkflowSpecificationNodeTypeType ...
type ShowWorkflowSpecificationNodeTypeType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ProcessWorkflowSpecificationNodeTypeType ...
type ProcessWorkflowSpecificationNodeTypeType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// AcknowledgeWorkflowSpecificationNodeTypeType ...
type AcknowledgeWorkflowSpecificationNodeTypeType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ChangeWorkflowSpecificationNodeTypeType ...
type ChangeWorkflowSpecificationNodeTypeType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// RespondWorkflowSpecificationNodeTypeType ...
type RespondWorkflowSpecificationNodeTypeType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// CancelWorkflowSpecificationNodeTypeType ...
type CancelWorkflowSpecificationNodeTypeType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// SyncWorkflowSpecificationNodeTypeType ...
type SyncWorkflowSpecificationNodeTypeType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// GetWorkflowSpecificationConnectionTypeType ...
type GetWorkflowSpecificationConnectionTypeType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ShowWorkflowSpecificationConnectionTypeType ...
type ShowWorkflowSpecificationConnectionTypeType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ProcessWorkflowSpecificationConnectionTypeType ...
type ProcessWorkflowSpecificationConnectionTypeType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// AcknowledgeWorkflowSpecificationConnectionTypeType ...
type AcknowledgeWorkflowSpecificationConnectionTypeType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ChangeWorkflowSpecificationConnectionTypeType ...
type ChangeWorkflowSpecificationConnectionTypeType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// RespondWorkflowSpecificationConnectionTypeType ...
type RespondWorkflowSpecificationConnectionTypeType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// CancelWorkflowSpecificationConnectionTypeType ...
type CancelWorkflowSpecificationConnectionTypeType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// SyncWorkflowSpecificationConnectionTypeType ...
type SyncWorkflowSpecificationConnectionTypeType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}
