// Code generated by xgen. DO NOT EDIT.

package b2mml

// ProcessSegmentInformation ...
// type ProcessSegmentInformation *ProcessSegmentInformationType

// ProcessSegment is A process segment lists the classes of personnel, equipment, physical assets, and material needed,
// and/or it may present specific resources, such as specific equipment needed for the process segment.
// A process segment may list the quantity of the resource needed.
// A process segment may be a specialization of another process segment. A process segment shall be
// defined as a “pattern” or an “instance”. A pattern process segment defines a ‘template’, upon which
// other pattern or instance process segments may be based. Unlike instance process segments, pattern
// process segments shall not be directly scheduled or tracked. Therefore, segment requirements,
// segment responses and process segment capabilities shall not reference pattern process segments.
// Where a process segment references a work master, the definition type (pattern or instance) of the
// referenced work master shall have the same value as that of the process segment.
// type ProcessSegment *ProcessSegmentType

// GetProcessSegmentInformation ...
type GetProcessSegmentInformation *GetProcessSegmentInformationType

// ShowProcessSegmentInformation ...
type ShowProcessSegmentInformation *ShowProcessSegmentInformationType

// ProcessProcessSegmentInformation ...
type ProcessProcessSegmentInformation *ProcessProcessSegmentInformationType

// AcknowledgeProcessSegmentInformation ...
type AcknowledgeProcessSegmentInformation *AcknowledgeProcessSegmentInformationType

// ChangeProcessSegmentInformation ...
type ChangeProcessSegmentInformation *ChangeProcessSegmentInformationType

// RespondProcessSegmentInformation ...
type RespondProcessSegmentInformation *RespondProcessSegmentInformationType

// CancelProcessSegmentInformation ...
type CancelProcessSegmentInformation *CancelProcessSegmentInformationType

// SyncProcessSegmentInformation ...
type SyncProcessSegmentInformation *SyncProcessSegmentInformationType

// GetProcessSegment ...
type GetProcessSegment *GetProcessSegmentType

// ShowProcessSegment ...
type ShowProcessSegment *ShowProcessSegmentType

// ProcessProcessSegment ...
type ProcessProcessSegment *ProcessProcessSegmentType

// AcknowledgeProcessSegment ...
type AcknowledgeProcessSegment *AcknowledgeProcessSegmentType

// ChangeProcessSegment ...
type ChangeProcessSegment *ChangeProcessSegmentType

// RespondProcessSegment ...
type RespondProcessSegment *RespondProcessSegmentType

// CancelProcessSegment ...
type CancelProcessSegment *CancelProcessSegmentType

// SyncProcessSegment ...
type SyncProcessSegment *SyncProcessSegmentType

// ProcessSegmentInformationType ...
type ProcessSegmentInformationType struct {
	ExtendedProcessSegmentInformation []*ProcessSegmentInformationType
	ID                                *IdentifierType       `xml:"ID"`
	Description                       []*DescriptionType    `xml:"Description"`
	HierarchyScope                    *HierarchyScopeType   `xml:"HierarchyScope"`
	PublishedDate                     *DateTimeType         `xml:"PublishedDate"`
	ProcessSegment                    []*ProcessSegmentType `xml:"ProcessSegment"`
}

// ProcessSegmentType ...
type ProcessSegmentType struct {
	ExtendedProcessSegment            []*ProcessSegmentType
	ID                                *IdentifierType                          `xml:"ID"`
	Description                       []*DescriptionType                       `xml:"Description"`
	Version                           *IdentifierType                          `xml:"Version"`
	PublishedDate                     *DateTimeType                            `xml:"PublishedDate"`
	EffectiveStartDate                *DateTimeType                            `xml:"EffectiveStartDate"`
	EffectiveEndDate                  *DateTimeType                            `xml:"EffectiveEndDate"`
	OperationsType                    *OperationsTypeType                      `xml:"OperationsType"`
	HierarchyScope                    *HierarchyScopeType                      `xml:"HierarchyScope"`
	DefinitionType                    *DefinitionTypeType                      `xml:"DefinitionType"`
	PersonnelSegmentSpecification     []*PersonnelSegmentSpecificationType     `xml:"PersonnelSegmentSpecification"`
	EquipmentSegmentSpecification     []*EquipmentSegmentSpecificationType     `xml:"EquipmentSegmentSpecification"`
	PhysicalAssetSegmentSpecification []*PhysicalAssetSegmentSpecificationType `xml:"PhysicalAssetSegmentSpecification"`
	MaterialSegmentSpecification      []*MaterialSegmentSpecificationType      `xml:"MaterialSegmentSpecification"`
	ProcessSegmentParameter           []*ParameterTypeType                     `xml:"ProcessSegmentParameter"`
	SegmentDependency                 []*SegmentDependencyType                 `xml:"SegmentDependency"`
	DependentProcessSegmentID         []*IdentifierType                        `xml:"DependentProcessSegmentID"`
	ProcessSegmentChild               []*ProcessSegmentType                    `xml:"ProcessSegmentChild"`
	ProcessSegmentPatternID           *IdentifierType                          `xml:"ProcessSegmentPatternID"`
	WorkMasterSourceID                []*IdentifierType                        `xml:"WorkMasterSourceID"`
	OperationsSegmentSourceID         []*IdentifierType                        `xml:"OperationsSegmentSourceID"`
	SegmentRequirementSourceID        []*IdentifierType                        `xml:"SegmentRequirementSourceID"`
}

// PersonnelSegmentSpecificationType ...
type PersonnelSegmentSpecificationType struct {
	ExtendedPersonnelSegmentSpecification []*PersonnelSegmentSpecification
	ID                                    *IdentifierType                              `xml:"ID"`
	PersonnelClassID                      []*IdentifierType                            `xml:"PersonnelClassID"`
	PersonID                              []*IdentifierType                            `xml:"PersonID"`
	Description                           []*DescriptionType                           `xml:"Description"`
	PersonnelUse                          *CodeType                                    `xml:"PersonnelUse"`
	HierarchyScope                        *HierarchyScopeType                          `xml:"HierarchyScope"`
	SpatialDefinition                     *SpatialDefinitionType                       `xml:"SpatialDefinition"`
	OperationalLocation                   *ResourceLocationType                        `xml:"OperationalLocation"`
	Quantity                              []*QuantityValueType                         `xml:"Quantity"`
	PersonnelSegmentSpecificationProperty []*PersonnelSegmentSpecificationPropertyType `xml:"PersonnelSegmentSpecificationProperty"`
	PersonnelSegmentSpecificationChild    []*PersonnelSegmentSpecificationType         `xml:"PersonnelSegmentSpecificationChild"`
	TestSpecificationID                   []*IdentifierType                            `xml:"TestSpecificationID"`
}

// PersonnelSegmentSpecificationPropertyType ...
type PersonnelSegmentSpecificationPropertyType struct {
	ExtendedPersonnelSegmentSpecificationProperty []*PersonnelSegmentSpecificationProperty
	ID                                            *IdentifierType                              `xml:"ID"`
	Description                                   []*DescriptionType                           `xml:"Description"`
	Value                                         []*ValueType                                 `xml:"Value"`
	Quantity                                      []*QuantityValueType                         `xml:"Quantity"`
	PersonnalSegmentSpecificationPropertyChild    []*PersonnelSegmentSpecificationPropertyType `xml:"PersonnalSegmentSpecificationPropertyChild"`
	PersonnelClassPropertyID                      *IdentifierType                              `xml:"PersonnelClassPropertyID"`
	PersonPropertyID                              *IdentifierType                              `xml:"PersonPropertyID"`
}

// EquipmentSegmentSpecificationType ...
type EquipmentSegmentSpecificationType struct {
	ExtendedEquipmentSegmentSpecification []*EquipmentSegmentSpecification
	ID                                    *IdentifierType                              `xml:"ID"`
	EquipmentClassID                      []*IdentifierType                            `xml:"EquipmentClassID"`
	EquipmentID                           []*IdentifierType                            `xml:"EquipmentID"`
	Description                           []*DescriptionType                           `xml:"Description"`
	EquipmentUse                          *CodeType                                    `xml:"EquipmentUse"`
	HierarchyScope                        *HierarchyScopeType                          `xml:"HierarchyScope"`
	SpatialDefinition                     *SpatialDefinitionType                       `xml:"SpatialDefinition"`
	OperationalLocation                   *ResourceLocationType                        `xml:"OperationalLocation"`
	Quantity                              []*QuantityValueType                         `xml:"Quantity"`
	EquipmentSegmentSpecificationProperty []*EquipmentSegmentSpecificationPropertyType `xml:"EquipmentSegmentSpecificationProperty"`
	EquipmentSegmentSpecificationChild    []*EquipmentSegmentSpecificationType         `xml:"EquipmentSegmentSpecificationChild"`
	TestSpecificationID                   []*IdentifierType                            `xml:"TestSpecificationID"`
}

// EquipmentSegmentSpecificationPropertyType ...
type EquipmentSegmentSpecificationPropertyType struct {
	ExtendedEquipmentSegmentSpecificationProperty []*EquipmentSegmentSpecificationProperty
	ID                                            *IdentifierType                              `xml:"ID"`
	Description                                   []*DescriptionType                           `xml:"Description"`
	Value                                         []*ValueType                                 `xml:"Value"`
	Quantity                                      []*QuantityValueType                         `xml:"Quantity"`
	EquipmentSegmentSpecificationPropertyChild    []*EquipmentSegmentSpecificationPropertyType `xml:"EquipmentSegmentSpecificationPropertyChild"`
	EquipmentClassPropertyID                      *IdentifierType                              `xml:"EquipmentClassPropertyID"`
	EquipmentPropertyID                           *IdentifierType                              `xml:"EquipmentPropertyID"`
}

// PhysicalAssetSegmentSpecificationType ...
type PhysicalAssetSegmentSpecificationType struct {
	ExtendedPhysicalAssetSegmentSpecification []*PhysicalAssetSegmentSpecification
	ID                                        *IdentifierType                                  `xml:"ID"`
	PhysicalAssetClassID                      []*IdentifierType                                `xml:"PhysicalAssetClassID"`
	PhysicalAssetID                           []*IdentifierType                                `xml:"PhysicalAssetID"`
	Description                               []*DescriptionType                               `xml:"Description"`
	PhysicalAssetUse                          *CodeType                                        `xml:"PhysicalAssetUse"`
	HierarchyScope                            *HierarchyScopeType                              `xml:"HierarchyScope"`
	SpatialDefinition                         *SpatialDefinitionType                           `xml:"SpatialDefinition"`
	PhysicalLocation                          *ResourceLocationType                            `xml:"PhysicalLocation"`
	Quantity                                  []*QuantityValueType                             `xml:"Quantity"`
	PhysicalAssetSegmentSpecificationProperty []*PhysicalAssetSegmentSpecificationPropertyType `xml:"PhysicalAssetSegmentSpecificationProperty"`
	PhysicalAssetSegmentSpecificationChild    []*PhysicalAssetSegmentSpecificationType         `xml:"PhysicalAssetSegmentSpecificationChild"`
	TestSpecificationID                       []*IdentifierType                                `xml:"TestSpecificationID"`
}

// PhysicalAssetSegmentSpecificationPropertyType ...
type PhysicalAssetSegmentSpecificationPropertyType struct {
	ExtendedPhysicalAssetSegmentSpecificationProperty []*PhysicalAssetSegmentSpecificationProperty
	ID                                                *IdentifierType                                  `xml:"ID"`
	Description                                       []*DescriptionType                               `xml:"Description"`
	Value                                             []*ValueType                                     `xml:"Value"`
	Quantity                                          []*QuantityValueType                             `xml:"Quantity"`
	PhysicalAssetSegmentSpecificationPropertyChild    []*PhysicalAssetSegmentSpecificationPropertyType `xml:"PhysicalAssetSegmentSpecificationPropertyChild"`
	PhysicalAssetClassPropertyID                      *IdentifierType                                  `xml:"PhysicalAssetClassPropertyID"`
	PhysicalAssetPropertyID                           *IdentifierType                                  `xml:"PhysicalAssetPropertyID"`
}

// MaterialSegmentSpecificationType ...
type MaterialSegmentSpecificationType struct {
	ExtendedMaterialSegmentSpecification []*MaterialSegmentSpecification
	ID                                   *IdentifierType                             `xml:"ID"`
	MaterialClassID                      []*IdentifierType                           `xml:"MaterialClassID"`
	MaterialDefinitionID                 []*IdentifierType                           `xml:"MaterialDefinitionID"`
	MaterialLotID                        []*IdentifierType                           `xml:"MaterialLotID"`
	MaterialSublotID                     []*IdentifierType                           `xml:"MaterialSublotID"`
	Description                          []*DescriptionType                          `xml:"Description"`
	AssemblyType                         *AssemblyTypeType                           `xml:"AssemblyType"`
	AssemblyRelationship                 *AssemblyRelationshipType                   `xml:"AssemblyRelationship"`
	AssemblySegmentSpecification         []*MaterialSegmentSpecificationType         `xml:"AssemblySegmentSpecification"`
	MaterialUse                          *MaterialUseType                            `xml:"MaterialUse"`
	HierarchyScope                       *HierarchyScopeType                         `xml:"HierarchyScope"`
	SpatialDefinition                    *SpatialDefinitionType                      `xml:"SpatialDefinition"`
	StorageLocation                      *ResourceLocationType                       `xml:"StorageLocation"`
	Quantity                             []*QuantityValueType                        `xml:"Quantity"`
	MaterialSegmentSpecificationProperty []*MaterialSegmentSpecificationPropertyType `xml:"MaterialSegmentSpecificationProperty"`
	MaterialSegmentSpecificationChild    []*MaterialSegmentSpecificationType         `xml:"MaterialSegmentSpecificationChild"`
	TestSpecificationID                  []*IdentifierType                           `xml:"TestSpecificationID"`
}

// MaterialSegmentSpecificationPropertyType ...
type MaterialSegmentSpecificationPropertyType struct {
	ExtendedMaterialSegmentSpecificationProperty []*MaterialSegmentSpecificationProperty
	ID                                           *IdentifierType                             `xml:"ID"`
	Description                                  []*DescriptionType                          `xml:"Description"`
	Value                                        []*ValueType                                `xml:"Value"`
	Quantity                                     []*QuantityValueType                        `xml:"Quantity"`
	MaterialSegmentSpecificationPropertyChild    []*MaterialSegmentSpecificationPropertyType `xml:"MaterialSegmentSpecificationPropertyChild"`
	MaterialClassPropertyID                      *IdentifierType                             `xml:"MaterialClassPropertyID"`
	MaterialDefinitionPropertyID                 *IdentifierType                             `xml:"MaterialDefinitionPropertyID"`
	MaterialLotPropertyID                        *IdentifierType                             `xml:"MaterialLotPropertyID"`
}

// DataArea ...
// type DataArea struct {
// 	Get                       *TransGetType                    `xml:"Get"`
// 	ProcessSegmentInformation []*ProcessSegmentInformationType `xml:"ProcessSegmentInformation"`
// }

// GetProcessSegmentInformationType ...
type GetProcessSegmentInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ShowProcessSegmentInformationType ...
type ShowProcessSegmentInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ProcessProcessSegmentInformationType ...
type ProcessProcessSegmentInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// AcknowledgeProcessSegmentInformationType ...
type AcknowledgeProcessSegmentInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ChangeProcessSegmentInformationType ...
type ChangeProcessSegmentInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// RespondProcessSegmentInformationType ...
type RespondProcessSegmentInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// CancelProcessSegmentInformationType ...
type CancelProcessSegmentInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// SyncProcessSegmentInformationType ...
type SyncProcessSegmentInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// GetProcessSegmentType ...
type GetProcessSegmentType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ShowProcessSegmentType ...
type ShowProcessSegmentType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ProcessProcessSegmentType ...
type ProcessProcessSegmentType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// AcknowledgeProcessSegmentType ...
type AcknowledgeProcessSegmentType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ChangeProcessSegmentType ...
type ChangeProcessSegmentType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// RespondProcessSegmentType ...
type RespondProcessSegmentType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// CancelProcessSegmentType ...
type CancelProcessSegmentType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// SyncProcessSegmentType ...
type SyncProcessSegmentType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}
