// Code generated by xgen. DO NOT EDIT.

package b2mml

// ConfirmBOD ...
type ConfirmBOD *ConfirmBODType

// DataArea ...
// type DataArea struct {
// 	Confirm *TransConfirmType `xml:"Confirm"`
// 	BOD     []*BODType        `xml:"BOD"`
// }

// ConfirmBODType ...
type ConfirmBODType struct {
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// BODType ...
type BODType struct {
	FreeFormTextGroup       *FreeFormTextGroup
	OriginalApplicationArea *TransApplicationAreaType `xml:"OriginalApplicationArea"`
	UserArea                *TransUserAreaType        `xml:"UserArea"`
}

// FreeFormTextGroup ...
type FreeFormTextGroup struct {
	Description []*TextType
	Note        []*TextType
}
