// Code generated by xgen. DO NOT EDIT.

package b2mml

// OperationsCapabilityInformation ...
type OperationsCapabilityInformation *OperationsCapabilityInformationType

// OperationsCapability ...
type OperationsCapability *OperationsCapabilityType

// GetOperationsCapability ...
type GetOperationsCapability *GetOperationsCapabilityType

// ShowOperationsCapability ...
type ShowOperationsCapability *ShowOperationsCapabilityType

// ProcessOperationsCapability ...
type ProcessOperationsCapability *ProcessOperationsCapabilityType

// AcknowledgeOperationsCapability ...
type AcknowledgeOperationsCapability *AcknowledgeOperationsCapabilityType

// ChangeOperationsCapability ...
type ChangeOperationsCapability *ChangeOperationsCapabilityType

// RespondOperationsCapability ...
type RespondOperationsCapability *RespondOperationsCapabilityType

// CancelOperationsCapability ...
type CancelOperationsCapability *CancelOperationsCapabilityType

// SyncOperationsCapability ...
type SyncOperationsCapability *SyncOperationsCapabilityType

// GetOperationsCapabilityInformation ...
type GetOperationsCapabilityInformation *GetOperationsCapabilityInformationType

// ShowOperationsCapabilityInformation ...
type ShowOperationsCapabilityInformation *ShowOperationsCapabilityInformationType

// ProcessOperationsCapabilityInformation ...
type ProcessOperationsCapabilityInformation *ProcessOperationsCapabilityInformationType

// AcknowledgeOperationsCapabilityInformation ...
type AcknowledgeOperationsCapabilityInformation *AcknowledgeOperationsCapabilityInformationType

// ChangeOperationsCapabilityInformation ...
type ChangeOperationsCapabilityInformation *ChangeOperationsCapabilityInformationType

// RespondOperationsCapabilityInformation ...
type RespondOperationsCapabilityInformation *RespondOperationsCapabilityInformationType

// CancelOperationsCapabilityInformation ...
type CancelOperationsCapabilityInformation *CancelOperationsCapabilityInformationType

// SyncOperationsCapabilityInformation ...
type SyncOperationsCapabilityInformation *SyncOperationsCapabilityInformationType

// OperationsCapabilityInformationType ...
type OperationsCapabilityInformationType struct {
	ExtendedOperationsCapabilityInformation []*OperationsCapabilityInformationType
	ID                                      *IdentifierType             `xml:"ID"`
	Description                             []*DescriptionType          `xml:"Description"`
	HierarchyScope                          *HierarchyScopeType         `xml:"HierarchyScope"`
	PublishedDate                           *DateTimeType               `xml:"PublishedDate"`
	OperationsCapability                    []*OperationsCapabilityType `xml:"OperationsCapability"`
}

// OperationsCapabilityType ...
type OperationsCapabilityType struct {
	ExtendedOperationsCapability []*OperationsCapabilityType
	ID                           *IdentifierType                      `xml:"ID"`
	Description                  []*DescriptionType                   `xml:"Description"`
	Version                      *IdentifierType                      `xml:"Version"`
	PublishedDate                *DateTimeType                        `xml:"PublishedDate"`
	StartTime                    *DateTimeType                        `xml:"StartTime"`
	EndTime                      *DateTimeType                        `xml:"EndTime"`
	HierarchyScope               *HierarchyScopeType                  `xml:"HierarchyScope"`
	OperationsType               *OperationsTypeType                  `xml:"OperationsType"`
	CapabilityType               *CapabilityTypeType                  `xml:"CapabilityType"`
	Reason                       *ReasonType                          `xml:"Reason"`
	ConfidenceFactor             *ConfidenceFactorType                `xml:"ConfidenceFactor"`
	PersonnelCapability          []*OpPersonnelCapabilityType         `xml:"PersonnelCapability"`
	EquipmentCapability          []*OpEquipmentCapabilityType         `xml:"EquipmentCapability"`
	PhysicalAssetCapability      []*OpPhysicalAssetCapabilityType     `xml:"PhysicalAssetCapability"`
	MaterialCapability           []*OpMaterialCapabilityType          `xml:"MaterialCapability"`
	ProcessSegmentCapability     []*OpProcessSegmentCapabilityType    `xml:"ProcessSegmentCapability"`
	OperationsSegmentCapability  []*OpOperationsSegmentCapabilityType `xml:"OperationsSegmentCapability"`
}

// OpProcessSegmentCapabilityType ...
type OpProcessSegmentCapabilityType struct {
	ExtendedOpProcessSegmentCapability []*OpProcessSegmentCapability
	ID                                 *IdentifierType                   `xml:"ID"`
	Description                        []*DescriptionType                `xml:"Description"`
	Version                            *IdentifierType                   `xml:"Version"`
	PublishedDate                      *DateTimeType                     `xml:"PublishedDate"`
	StartTime                          *DateTimeType                     `xml:"StartTime"`
	EndTime                            *DateTimeType                     `xml:"EndTime"`
	ProcessSegmentID                   []*IdentifierType                 `xml:"ProcessSegmentID"`
	OperationsType                     *OperationsTypeType               `xml:"OperationsType"`
	CapabilityType                     *CapabilityTypeType               `xml:"CapabilityType"`
	Reason                             []*ReasonType                     `xml:"Reason"`
	HierarchyScope                     []*HierarchyScopeType             `xml:"HierarchyScope"`
	PersonnelCapability                []*OpPersonnelCapabilityType      `xml:"PersonnelCapability"`
	EquipmentCapability                []*OpEquipmentCapabilityType      `xml:"EquipmentCapability"`
	PhysicalAssetCapability            []*OpPhysicalAssetCapabilityType  `xml:"PhysicalAssetCapability"`
	MaterialCapability                 []*OpMaterialCapabilityType       `xml:"MaterialCapability"`
	ProcessSegmentCapabilityChild      []*OpProcessSegmentCapabilityType `xml:"ProcessSegmentCapabilityChild"`
}

// OpOperationsSegmentCapabilityType ...
type OpOperationsSegmentCapabilityType struct {
	ExtendedOpOperationsSegmentCapability []*OpOperationsSegmentCapability
	ID                                    *IdentifierType                      `xml:"ID"`
	Description                           []*DescriptionType                   `xml:"Description"`
	Version                               *IdentifierType                      `xml:"Version"`
	PublishedDate                         *DateTimeType                        `xml:"PublishedDate"`
	StartTime                             *DateTimeType                        `xml:"StartTime"`
	EndTime                               *DateTimeType                        `xml:"EndTime"`
	OperationsSegmentID                   *IdentifierType                      `xml:"OperationsSegmentID"`
	OperationsType                        *OperationsTypeType                  `xml:"OperationsType"`
	CapabilityType                        *CapabilityTypeType                  `xml:"CapabilityType"`
	Reason                                []*ReasonType                        `xml:"Reason"`
	HierarchyScope                        []*HierarchyScopeType                `xml:"HierarchyScope"`
	PersonnelCapability                   []*OpPersonnelCapabilityType         `xml:"PersonnelCapability"`
	EquipmentCapability                   []*OpEquipmentCapabilityType         `xml:"EquipmentCapability"`
	PhysicalAssetCapability               []*OpPhysicalAssetCapabilityType     `xml:"PhysicalAssetCapability"`
	MaterialCapability                    []*OpMaterialCapabilityType          `xml:"MaterialCapability"`
	OperationsSegmentCapabilityChild      []*OpOperationsSegmentCapabilityType `xml:"OperationsSegmentCapabilityChild"`
}

// DataArea ...
type DataArea struct {
	Get                             *TransGetType                          `xml:"Get"`
	OperationsCapabilityInformation []*OperationsCapabilityInformationType `xml:"OperationsCapabilityInformation"`
}

// GetOperationsCapabilityInformationType ...
type GetOperationsCapabilityInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ShowOperationsCapabilityInformationType ...
type ShowOperationsCapabilityInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ProcessOperationsCapabilityInformationType ...
type ProcessOperationsCapabilityInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// AcknowledgeOperationsCapabilityInformationType ...
type AcknowledgeOperationsCapabilityInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ChangeOperationsCapabilityInformationType ...
type ChangeOperationsCapabilityInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// RespondOperationsCapabilityInformationType ...
type RespondOperationsCapabilityInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// CancelOperationsCapabilityInformationType ...
type CancelOperationsCapabilityInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// SyncOperationsCapabilityInformationType ...
type SyncOperationsCapabilityInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// GetOperationsCapabilityType ...
type GetOperationsCapabilityType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ShowOperationsCapabilityType ...
type ShowOperationsCapabilityType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ProcessOperationsCapabilityType ...
type ProcessOperationsCapabilityType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// AcknowledgeOperationsCapabilityType ...
type AcknowledgeOperationsCapabilityType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ChangeOperationsCapabilityType ...
type ChangeOperationsCapabilityType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// RespondOperationsCapabilityType ...
type RespondOperationsCapabilityType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// CancelOperationsCapabilityType ...
type CancelOperationsCapabilityType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// SyncOperationsCapabilityType ...
type SyncOperationsCapabilityType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}
