// Code generated by xgen. DO NOT EDIT.

package b2mml

// WorkCapabilityInformation ...
// type WorkCapabilityInformation *WorkCapabilityInformationType

// WorkCapability ...
// type WorkCapability *WorkCapabilityType

// WorkMasterCapability ...
// type WorkMasterCapability *WorkMasterCapabilityType

// GetWorkCapability ...
type GetWorkCapability *GetWorkCapabilityType

// ShowWorkCapability ...
type ShowWorkCapability *ShowWorkCapabilityType

// ProcessWorkCapability ...
type ProcessWorkCapability *ProcessWorkCapabilityType

// AcknowledgeWorkCapability ...
type AcknowledgeWorkCapability *AcknowledgeWorkCapabilityType

// ChangeWorkCapability ...
type ChangeWorkCapability *ChangeWorkCapabilityType

// RespondWorkCapability ...
type RespondWorkCapability *RespondWorkCapabilityType

// CancelWorkCapability ...
type CancelWorkCapability *CancelWorkCapabilityType

// SyncWorkCapability ...
type SyncWorkCapability *SyncWorkCapabilityType

// GetWorkMasterCapability ...
type GetWorkMasterCapability *GetWorkMasterCapabilityType

// ShowWorkMasterCapability ...
type ShowWorkMasterCapability *ShowWorkMasterCapabilityType

// ProcessWorkMasterCapability ...
type ProcessWorkMasterCapability *ProcessWorkMasterCapabilityType

// AcknowledgeWorkMasterCapability ...
type AcknowledgeWorkMasterCapability *AcknowledgeWorkMasterCapabilityType

// ChangeWorkMasterCapability ...
type ChangeWorkMasterCapability *ChangeWorkMasterCapabilityType

// RespondWorkMasterCapability ...
type RespondWorkMasterCapability *RespondWorkMasterCapabilityType

// CancelWorkMasterCapability ...
type CancelWorkMasterCapability *CancelWorkMasterCapabilityType

// SyncWorkMasaterCapability ...
type SyncWorkMasaterCapability *SyncWorkMasterCapabilityType

// GetWorkCapabilityInformation ...
type GetWorkCapabilityInformation *GetWorkCapabilityInformationType

// ShowWorkCapabilityInformation ...
type ShowWorkCapabilityInformation *ShowWorkCapabilityInformationType

// ProcessWorkCapabilityInformation ...
type ProcessWorkCapabilityInformation *ProcessWorkCapabilityInformationType

// AcknowledgeWorkCapabilityInformation ...
type AcknowledgeWorkCapabilityInformation *AcknowledgeWorkCapabilityInformationType

// ChangeWorkCapabilityInformation ...
type ChangeWorkCapabilityInformation *ChangeWorkCapabilityInformationType

// RespondWorkCapabilityInformation ...
type RespondWorkCapabilityInformation *RespondWorkCapabilityInformationType

// CancelWorkCapabilityInformation ...
type CancelWorkCapabilityInformation *CancelWorkCapabilityInformationType

// SyncWorkCapabilityInformation ...
type SyncWorkCapabilityInformation *SyncWorkCapabilityInformationType

// WorkCapabilityInformationType ...
type WorkCapabilityInformationType struct {
	ExtendedWorkCapabilityInformation []*WorkCapabilityInformationType
	ID                                *IdentifierType             `xml:"ID"`
	Description                       []*DescriptionType          `xml:"Description"`
	HierarchyScope                    *HierarchyScopeType         `xml:"HierarchyScope"`
	PublishedDate                     *DateTimeType               `xml:"PublishedDate"`
	WorkCapability                    []*WorkCapabilityType       `xml:"WorkCapability"`
	WorkMasterCapability              []*WorkMasterCapabilityType `xml:"WorkMasterCapability"`
}

// WorkCapabilityType ...
type WorkCapabilityType struct {
	ExtendedWorkCapability  []*WorkCapabilityType
	ID                      *IdentifierType                  `xml:"ID"`
	Description             []*DescriptionType               `xml:"Description"`
	Version                 *IdentifierType                  `xml:"Version"`
	PublishedDate           *DateTimeType                    `xml:"PublishedDate"`
	StartTime               *DateTimeType                    `xml:"StartTime"`
	EndTime                 *DateTimeType                    `xml:"EndTime"`
	HierarchyScope          *HierarchyScopeType              `xml:"HierarchyScope"`
	OperationsType          *OperationsTypeType              `xml:"OperationsType"`
	CapabilityType          *CapabilityTypeType              `xml:"CapabilityType"`
	Reason                  *ReasonType                      `xml:"Reason"`
	ConfidenceFactor        *ConfidenceFactorType            `xml:"ConfidenceFactor"`
	PersonnelCapability     []*OpPersonnelCapabilityType     `xml:"PersonnelCapability"`
	EquipmentCapability     []*OpEquipmentCapabilityType     `xml:"EquipmentCapability"`
	PhysicalAssetCapability []*OpPhysicalAssetCapabilityType `xml:"PhysicalAssetCapability"`
	MaterialCapability      []*OpMaterialCapabilityType      `xml:"MaterialCapability"`
	WorkMasterCapability    []*WorkMasterCapabilityType      `xml:"WorkMasterCapability"`
}

// WorkMasterCapabilityType ...
type WorkMasterCapabilityType struct {
	ExtendedWorkMasterCapability []*WorkMasterCapabilityType
	ID                           *IdentifierType                  `xml:"ID"`
	Description                  []*DescriptionType               `xml:"Description"`
	Version                      *IdentifierType                  `xml:"Version"`
	PublishedDate                *DateTimeType                    `xml:"PublishedDate"`
	StartTime                    *DateTimeType                    `xml:"StartTime"`
	EndTime                      *DateTimeType                    `xml:"EndTime"`
	WorkMasterID                 *IdentifierType                  `xml:"WorkMasterID"`
	CapabilityType               *CapabilityTypeType              `xml:"CapabilityType"`
	Reason                       []*ReasonType                    `xml:"Reason"`
	HierarchyScope               []*HierarchyScopeType            `xml:"HierarchyScope"`
	PersonnelCapability          []*OpPersonnelCapabilityType     `xml:"PersonnelCapability"`
	EquipmentCapability          []*OpEquipmentCapabilityType     `xml:"EquipmentCapability"`
	PhysicalAssetCapability      []*OpPhysicalAssetCapabilityType `xml:"PhysicalAssetCapability"`
	MaterialCapability           []*OpMaterialCapabilityType      `xml:"MaterialCapability"`
	WorkMasterCapability         []*WorkMasterCapabilityType      `xml:"WorkMasterCapability"`
}

// DataArea ...
// type DataArea struct {
// 	Get                       *TransGetType                    `xml:"Get"`
// 	WorkCapabilityInformation []*WorkCapabilityInformationType `xml:"WorkCapabilityInformation"`
// }

// GetWorkCapabilityInformationType ...
type GetWorkCapabilityInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ShowWorkCapabilityInformationType ...
type ShowWorkCapabilityInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ProcessWorkCapabilityInformationType ...
type ProcessWorkCapabilityInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// AcknowledgeWorkCapabilityInformationType ...
type AcknowledgeWorkCapabilityInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ChangeWorkCapabilityInformationType ...
type ChangeWorkCapabilityInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// RespondWorkCapabilityInformationType ...
type RespondWorkCapabilityInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// CancelWorkCapabilityInformationType ...
type CancelWorkCapabilityInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// SyncWorkCapabilityInformationType ...
type SyncWorkCapabilityInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// GetWorkCapabilityType ...
type GetWorkCapabilityType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ShowWorkCapabilityType ...
type ShowWorkCapabilityType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ProcessWorkCapabilityType ...
type ProcessWorkCapabilityType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// AcknowledgeWorkCapabilityType ...
type AcknowledgeWorkCapabilityType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ChangeWorkCapabilityType ...
type ChangeWorkCapabilityType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// RespondWorkCapabilityType ...
type RespondWorkCapabilityType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// CancelWorkCapabilityType ...
type CancelWorkCapabilityType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// SyncWorkCapabilityType ...
type SyncWorkCapabilityType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// GetWorkMasterCapabilityType ...
type GetWorkMasterCapabilityType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ShowWorkMasterCapabilityType ...
type ShowWorkMasterCapabilityType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ProcessWorkMasterCapabilityType ...
type ProcessWorkMasterCapabilityType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// AcknowledgeWorkMasterCapabilityType ...
type AcknowledgeWorkMasterCapabilityType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ChangeWorkMasterCapabilityType ...
type ChangeWorkMasterCapabilityType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// RespondWorkMasterCapabilityType ...
type RespondWorkMasterCapabilityType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// CancelWorkMasterCapabilityType ...
type CancelWorkMasterCapabilityType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// SyncWorkMasterCapabilityType ...
type SyncWorkMasterCapabilityType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}
