// Code generated by xgen. DO NOT EDIT.

package b2mml

// WorkCalendarInformation ...
type WorkCalendarInformation *WorkCalendarInformationType

// WorkCalendar ...
type WorkCalendar *WorkCalendarType

// WorkCalendarDefinition ...
type WorkCalendarDefinition *WorkCalendarDefinitionType

// GetWorkCalendar ...
type GetWorkCalendar *GetWorkCalendarType

// ShowWorkCalendar ...
type ShowWorkCalendar *ShowWorkCalendarType

// ProcessWorkCalendar ...
type ProcessWorkCalendar *ProcessWorkCalendarType

// AcknowledgeWorkCalendar ...
type AcknowledgeWorkCalendar *AcknowledgeWorkCalendarType

// ChangeWorkCalendar ...
type ChangeWorkCalendar *ChangeWorkCalendarType

// RespondWorkCalendar ...
type RespondWorkCalendar *RespondWorkCalendarType

// CancelWorkCalendar ...
type CancelWorkCalendar *CancelWorkCalendarType

// SyncWorkCalendar ...
type SyncWorkCalendar *SyncWorkCalendarType

// GetWorkCalendarDefinition ...
type GetWorkCalendarDefinition *GetWorkCalendarDefinitionType

// ShowWorkCalendarDefinition ...
type ShowWorkCalendarDefinition *ShowWorkCalendarDefinitionType

// ProcessWorkCalendarDefinition ...
type ProcessWorkCalendarDefinition *ProcessWorkCalendarDefinitionType

// AcknowledgeWorkCalendarDefinition ...
type AcknowledgeWorkCalendarDefinition *AcknowledgeWorkCalendarDefinitionType

// ChangeWorkCalendarDefinition ...
type ChangeWorkCalendarDefinition *ChangeWorkCalendarDefinitionType

// RespondWorkCalendarDefinition ...
type RespondWorkCalendarDefinition *RespondWorkCalendarDefinitionType

// CancelWorkCalendarDefinition ...
type CancelWorkCalendarDefinition *CancelWorkCalendarDefinitionType

// SyncWorkCalendarDefinition ...
type SyncWorkCalendarDefinition *SyncWorkCalendarDefinitionType

// GetWorkCalendarInformation ...
type GetWorkCalendarInformation *GetWorkCalendarInformationType

// ShowWorkCalendarInformation ...
type ShowWorkCalendarInformation *ShowWorkCalendarInformationType

// ProcessWorkCalendarInformation ...
type ProcessWorkCalendarInformation *ProcessWorkCalendarInformationType

// AcknowledgeWorkCalendarInformation ...
type AcknowledgeWorkCalendarInformation *AcknowledgeWorkCalendarInformationType

// ChangeWorkCalendarInformation ...
type ChangeWorkCalendarInformation *ChangeWorkCalendarInformationType

// RespondWorkCalendarInformation ...
type RespondWorkCalendarInformation *RespondWorkCalendarInformationType

// CancelWorkCalendarInformation ...
type CancelWorkCalendarInformation *CancelWorkCalendarInformationType

// SyncWorkCalendarInformation ...
type SyncWorkCalendarInformation *SyncWorkCalendarInformationType

// WorkCalendarInformationType ...
type WorkCalendarInformationType struct {
	ExtendedWorkCalendarInformation []*WorkCalendarInformationType
	ID                              *IdentifierType               `xml:"ID"`
	Description                     []*DescriptionType            `xml:"Description"`
	HierarchyScope                  *HierarchyScopeType           `xml:"HierarchyScope"`
	PublishedDate                   *DateTimeType                 `xml:"PublishedDate"`
	WorkCalendar                    []*WorkCalendarType           `xml:"WorkCalendar"`
	WorkCalendarDefinition          []*WorkCalendarDefinitionType `xml:"WorkCalendarDefinition"`
}

// WorkCalendarDefinitionType ...
type WorkCalendarDefinitionType struct {
	ExtendedWorkCalendarDefinition []*WorkCalendarDefinitionType
	ID                             *IdentifierType                       `xml:"ID"`
	Description                    []*DescriptionType                    `xml:"Description"`
	Version                        *IdentifierType                       `xml:"Version"`
	PublishedDate                  *DateTimeType                         `xml:"PublishedDate"`
	EffectiveStartDate             *DateTimeType                         `xml:"EffectiveStartDate"`
	EffectiveEndDate               *DateTimeType                         `xml:"EffectiveEndDate"`
	HierarchyScope                 *HierarchyScopeType                   `xml:"HierarchyScope"`
	WorkCalendarDefinitionEntry    []*WorkCalendarDefinitionEntryType    `xml:"WorkCalendarDefinitionEntry"`
	WorkCalendarDefinitionProperty []*WorkCalendarDefinitionPropertyType `xml:"WorkCalendarDefinitionProperty"`
}

// WorkCalendarDefinitionPropertyType ...
type WorkCalendarDefinitionPropertyType struct {
	ExtendedWorkCalendarDefinitionProperty []*WorkCalendarDefinitionProperty
	ID                                     *IdentifierType                       `xml:"ID"`
	Description                            []*DescriptionType                    `xml:"Description"`
	Value                                  []*ValueType                          `xml:"Value"`
	WorkCalendarDefinitionPropertyChild    []*WorkCalendarDefinitionPropertyType `xml:"WorkCalendarDefinitionPropertyChild"`
}

// WorkCalendarDefinitionEntryType ...
type WorkCalendarDefinitionEntryType struct {
	ExtendedWorkCalendarDefinitionEntry []*WorkCalendarDefinitionEntry
	ID                                  *IdentifierType                            `xml:"ID"`
	Description                         []*DescriptionType                         `xml:"Description"`
	Version                             *IdentifierType                            `xml:"Version"`
	PublishedDate                       *DateTimeType                              `xml:"PublishedDate"`
	EffectiveStartDate                  *DateTimeType                              `xml:"EffectiveStartDate"`
	EffectiveEndDate                    *DateTimeType                              `xml:"EffectiveEndDate"`
	HierarchyScope                      *HierarchyScopeType                        `xml:"HierarchyScope"`
	RecurrenceTime                      *CodeType                                  `xml:"RecurrenceTime"`
	DurationRule                        *CodeType                                  `xml:"DurationRule"`
	EntryType                           *CodeType                                  `xml:"EntryType"`
	WorkCalendarDefinitionEntryChild    []*WorkCalendarDefinitionEntryType         `xml:"WorkCalendarDefinitionEntryChild"`
	WorkCalendarDefinitionEntryProperty []*WorkCalendarDefinitionEntryPropertyType `xml:"WorkCalendarDefinitionEntryProperty"`
}

// WorkCalendarDefinitionEntryPropertyType ...
type WorkCalendarDefinitionEntryPropertyType struct {
	ExtendedWorkCalendarDefinitionEntryProperty []*WorkCalendarDefinitionEntryProperty
	ID                                          *IdentifierType                            `xml:"ID"`
	Description                                 []*DescriptionType                         `xml:"Description"`
	Value                                       []*ValueType                               `xml:"Value"`
	WorkCalendarDefinitionEntryPropertyChild    []*WorkCalendarDefinitionEntryPropertyType `xml:"WorkCalendarDefinitionEntryPropertyChild"`
}

// WorkCalendarType ...
type WorkCalendarType struct {
	ExtendedWorkCalendar []*WorkCalendarType
	ID                   *IdentifierType             `xml:"ID"`
	Description          []*DescriptionType          `xml:"Description"`
	Version              *IdentifierType             `xml:"Version"`
	PublishedDate        *DateTimeType               `xml:"PublishedDate"`
	EffectiveStartDate   *DateTimeType               `xml:"EffectiveStartDate"`
	EffectiveEndDate     *DateTimeType               `xml:"EffectiveEndDate"`
	HierarchyScope       *HierarchyScopeType         `xml:"HierarchyScope"`
	WorkCalendarEntry    []*WorkCalendarEntryType    `xml:"WorkCalendarEntry"`
	WorkCalendarProperty []*WorkCalendarPropertyType `xml:"WorkCalendarProperty"`
}

// WorkCalendarPropertyType ...
type WorkCalendarPropertyType struct {
	ExtendedWorkCalendarProperty    []*WorkCalendarProperty
	ID                              *IdentifierType             `xml:"ID"`
	Description                     []*DescriptionType          `xml:"Description"`
	Value                           []*ValueType                `xml:"Value"`
	WorkCalendarPropertyChild       []*WorkCalendarPropertyType `xml:"WorkCalendarPropertyChild"`
	WorkCalendarDefintionPropertyID *IdentifierType             `xml:"WorkCalendarDefintionPropertyID"`
}

// WorkCalendarEntryType ...
type WorkCalendarEntryType struct {
	ExtendedWorkCalendarEntry    []*WorkCalendarEntry
	ID                           *IdentifierType                  `xml:"ID"`
	Description                  []*DescriptionType               `xml:"Description"`
	PublishedDate                *DateTimeType                    `xml:"PublishedDate"`
	StartDateTime                *DateTimeType                    `xml:"StartDateTime"`
	FinishDateTime               *DateTimeType                    `xml:"FinishDateTime"`
	HierarchyScope               *HierarchyScopeType              `xml:"HierarchyScope"`
	EntryType                    *CodeType                        `xml:"EntryType"`
	WorkCalendarEntryChild       []*WorkCalendarEntryType         `xml:"WorkCalendarEntryChild"`
	WorkCalendarDefintionEntryID *IdentifierType                  `xml:"WorkCalendarDefintionEntryID"`
	WorkCalendarEntryProperty    []*WorkCalendarEntryPropertyType `xml:"WorkCalendarEntryProperty"`
}

// WorkCalendarEntryPropertyType ...
type WorkCalendarEntryPropertyType struct {
	ExtendedWorkCalendarEntryProperty    []*WorkCalendarEntryProperty
	ID                                   *IdentifierType                  `xml:"ID"`
	Description                          []*DescriptionType               `xml:"Description"`
	Value                                []*ValueType                     `xml:"Value"`
	WorkCalendarDefintionEntryPropertyID *IdentifierType                  `xml:"WorkCalendarDefintionEntryPropertyID"`
	WorkCalendarEntryPropertyChild       []*WorkCalendarEntryPropertyType `xml:"WorkCalendarEntryPropertyChild"`
}

// DataArea ...
type DataArea struct {
	Get                     *TransGetType                  `xml:"Get"`
	WorkCalendarInformation []*WorkCalendarInformationType `xml:"WorkCalendarInformation"`
}

// GetWorkCalendarInformationType ...
type GetWorkCalendarInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ShowWorkCalendarInformationType ...
type ShowWorkCalendarInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ProcessWorkCalendarInformationType ...
type ProcessWorkCalendarInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// AcknowledgeWorkCalendarInformationType ...
type AcknowledgeWorkCalendarInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ChangeWorkCalendarInformationType ...
type ChangeWorkCalendarInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// RespondWorkCalendarInformationType ...
type RespondWorkCalendarInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// CancelWorkCalendarInformationType ...
type CancelWorkCalendarInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// SyncWorkCalendarInformationType ...
type SyncWorkCalendarInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// GetWorkCalendarType ...
type GetWorkCalendarType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ShowWorkCalendarType ...
type ShowWorkCalendarType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ProcessWorkCalendarType ...
type ProcessWorkCalendarType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// AcknowledgeWorkCalendarType ...
type AcknowledgeWorkCalendarType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ChangeWorkCalendarType ...
type ChangeWorkCalendarType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// RespondWorkCalendarType ...
type RespondWorkCalendarType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// CancelWorkCalendarType ...
type CancelWorkCalendarType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// SyncWorkCalendarType ...
type SyncWorkCalendarType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// GetWorkCalendarDefinitionType ...
type GetWorkCalendarDefinitionType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ShowWorkCalendarDefinitionType ...
type ShowWorkCalendarDefinitionType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ProcessWorkCalendarDefinitionType ...
type ProcessWorkCalendarDefinitionType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// AcknowledgeWorkCalendarDefinitionType ...
type AcknowledgeWorkCalendarDefinitionType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ChangeWorkCalendarDefinitionType ...
type ChangeWorkCalendarDefinitionType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// RespondWorkCalendarDefinitionType ...
type RespondWorkCalendarDefinitionType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// CancelWorkCalendarDefinitionType ...
type CancelWorkCalendarDefinitionType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// SyncWorkCalendarDefinitionType ...
type SyncWorkCalendarDefinitionType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}
