// Code generated by xgen. DO NOT EDIT.

package b2mml

// EquipmentAssetMapping ...
type EquipmentAssetMapping struct {
}

// HierarchyScope ...
type HierarchyScope struct {
}

// Parameter ...
type Parameter struct {
}

// Quantity ...
type Quantity struct {
}

// OperationalLocationInformation ...
type OperationalLocationInformation struct {
}

// OperationalLocationClass ...
type OperationalLocationClass struct {
}

// OperationalLocation ...
type OperationalLocation struct {
}

// OperationalLocationClassProperty ...
type OperationalLocationClassProperty struct {
}

// OperationalLocationProperty ...
type OperationalLocationProperty struct {
}

// OperationsEventInformation ...
type OperationsEventInformation struct {
}

// OperationsEventClass ...
type OperationsEventClass struct {
}

// OperationsEventClassProperty ...
type OperationsEventClassProperty struct {
}

// OperationsEventDefinition ...
type OperationsEventDefinition struct {
}

// OperationsEventDefinitionProperty ...
type OperationsEventDefinitionProperty struct {
}

// OperationsEvent ...
type OperationsEvent struct {
}

// OperationsEventProperty ...
type OperationsEventProperty struct {
}

// OperationsRecordEntryTemplate ...
type OperationsRecordEntryTemplate struct {
}

// OperationsRecordTemplate ...
type OperationsRecordTemplate struct {
}

// OperationsRecordSpecTemplate ...
type OperationsRecordSpecTemplate struct {
}

// SegmentDependency ...
type SegmentDependency struct {
}

// SpatialDefinition ...
type SpatialDefinition struct {
}

// Value ...
type Value struct {
}

// OpPersonnelSegmentSpecification ...
type OpPersonnelSegmentSpecification struct {
}

// OpPersonnelSegmentSpecificationProperty ...
type OpPersonnelSegmentSpecificationProperty struct {
}

// OpEquipmentSegmentSpecification ...
type OpEquipmentSegmentSpecification struct {
}

// OpEquipmentSegmentSpecificationProperty ...
type OpEquipmentSegmentSpecificationProperty struct {
}

// OpPhysicalAssetSegmentSpecification ...
type OpPhysicalAssetSegmentSpecification struct {
}

// OpPhysicalAssetSegmentSpecificationProperty ...
type OpPhysicalAssetSegmentSpecificationProperty struct {
}

// OpMaterialSegmentSpecification ...
type OpMaterialSegmentSpecification struct {
}

// OpMaterialSegmentSpecificationProperty ...
type OpMaterialSegmentSpecificationProperty struct {
}

// OpPersonnelCapability ...
type OpPersonnelCapability struct {
}

// OpPersonnelCapabilityProperty ...
type OpPersonnelCapabilityProperty struct {
}

// OpEquipmentCapability ...
type OpEquipmentCapability struct {
}

// OpEquipmentCapabilityProperty ...
type OpEquipmentCapabilityProperty struct {
}

// OpPhysicalAssetCapability ...
type OpPhysicalAssetCapability struct {
}

// OpPhysicalAssetCapabilityProperty ...
type OpPhysicalAssetCapabilityProperty struct {
}

// OpMaterialCapability ...
type OpMaterialCapability struct {
}

// OpMaterialCapabilityProperty ...
type OpMaterialCapabilityProperty struct {
}

// OpOperationsSegmentCapability ...
type OpOperationsSegmentCapability struct {
}

// OpProcessSegmentCapability ...
type OpProcessSegmentCapability struct {
}

// OpPersonnelSpecification ...
type OpPersonnelSpecification struct {
}

// OpPersonnelSpecificationProperty ...
type OpPersonnelSpecificationProperty struct {
}

// OpEquipmentSpecification ...
type OpEquipmentSpecification struct {
}

// OpEquipmentSpecificationProperty ...
type OpEquipmentSpecificationProperty struct {
}

// OpPhysicalAssetSpecification ...
type OpPhysicalAssetSpecification struct {
}

// OpPhysicalAssetSpecificationProperty ...
type OpPhysicalAssetSpecificationProperty struct {
}

// OpMaterialSpecification ...
type OpMaterialSpecification struct {
}

// OpMaterialSpecificationProperty ...
type OpMaterialSpecificationProperty struct {
}

// OpPersonnelRequirement ...
type OpPersonnelRequirement struct {
}

// OpPersonnelRequirementProperty ...
type OpPersonnelRequirementProperty struct {
}

// OpEquipmentRequirement ...
type OpEquipmentRequirement struct {
}

// OpEquipmentRequirementProperty ...
type OpEquipmentRequirementProperty struct {
}

// OpPhysicalAssetRequirement ...
type OpPhysicalAssetRequirement struct {
}

// OpPhysicalAssetRequirementProperty ...
type OpPhysicalAssetRequirementProperty struct {
}

// OpMaterialRequirement ...
type OpMaterialRequirement struct {
}

// OpMaterialRequirementProperty ...
type OpMaterialRequirementProperty struct {
}
