// Code generated by xgen. DO NOT EDIT.

package b2mml

// EquipmentInformation ...
type EquipmentInformation struct {
}

// Equipment ...
type Equipment struct {
}

// EquipmentProperty ...
type EquipmentProperty struct {
}

// EquipmentClass ...
type EquipmentClass struct {
}

// EquipmentClassProperty ...
type EquipmentClassProperty struct {
}

// PhysicalAssetInformation ...
type PhysicalAssetInformation struct {
}

// PhysicalAsset ...
type PhysicalAsset struct {
}

// PhysicalAssetProperty ...
type PhysicalAssetProperty struct {
}

// PhysicalAssetClass ...
type PhysicalAssetClass struct {
}

// PhysicalAssetClassProperty ...
type PhysicalAssetClassProperty struct {
}

// MaterialInformation ...
type MaterialInformation struct {
}

// MaterialClass ...
type MaterialClass struct {
}

// MaterialClassProperty ...
type MaterialClassProperty struct {
}

// MaterialDefinition ...
type MaterialDefinition struct {
}

// MaterialDefinitionProperty ...
type MaterialDefinitionProperty struct {
}

// MaterialLot ...
type MaterialLot struct {
}

// MaterialLotProperty ...
type MaterialLotProperty struct {
}

// MaterialSubLot ...
type MaterialSubLot struct {
}

// PersonnelInformation ...
type PersonnelInformation struct {
}

// Person ...
type Person struct {
}

// PersonProperty ...
type PersonProperty struct {
}

// PersonnelClass ...
type PersonnelClass struct {
}

// PersonnelClassProperty ...
type PersonnelClassProperty struct {
}

// ProcessSegmentInformation ...
type ProcessSegmentInformation struct {
}

// ProcessSegment ...
type ProcessSegment struct {
}

// PersonnelSegmentSpecification ...
type PersonnelSegmentSpecification struct {
}

// PersonnelSegmentSpecificationProperty ...
type PersonnelSegmentSpecificationProperty struct {
}

// EquipmentSegmentSpecification ...
type EquipmentSegmentSpecification struct {
}

// EquipmentSegmentSpecificationProperty ...
type EquipmentSegmentSpecificationProperty struct {
}

// PhysicalAssetSegmentSpecification ...
type PhysicalAssetSegmentSpecification struct {
}

// PhysicalAssetSegmentSpecificationProperty ...
type PhysicalAssetSegmentSpecificationProperty struct {
}

// MaterialSegmentSpecification ...
type MaterialSegmentSpecification struct {
}

// MaterialSegmentSpecificationProperty ...
type MaterialSegmentSpecificationProperty struct {
}

// OperationsTestInformation ...
type OperationsTestInformation struct {
}

// TestSpecification ...
type TestSpecification struct {
}

// TestSpecificationProperty ...
type TestSpecificationProperty struct {
}

// TestSpecificationInformation ...
type TestSpecificationInformation struct {
}

// TestSpecificationCriteria ...
type TestSpecificationCriteria struct {
}

// EvaluatedProperty ...
type EvaluatedProperty struct {
}

// TestResult ...
type TestResult struct {
}

// PropertyMeasurement ...
type PropertyMeasurement struct {
}

// OperationsDefinitionInformation ...
type OperationsDefinitionInformation struct {
}

// OperationsDefinition ...
type OperationsDefinition struct {
}

// ProductInformation ...
type ProductInformation struct {
}

// OperationsMaterialBill ...
type OperationsMaterialBill struct {
}

// OperationsMaterialBillItem ...
type OperationsMaterialBillItem struct {
}

// OperationsSegment ...
type OperationsSegment struct {
}

// PersonnelSpecification ...
type PersonnelSpecification struct {
}

// PersonnelSpecificationProperty ...
type PersonnelSpecificationProperty struct {
}

// EquipmentSpecification ...
type EquipmentSpecification struct {
}

// EquipmentSpecificationProperty ...
type EquipmentSpecificationProperty struct {
}

// PhysicalAssetSpecification ...
type PhysicalAssetSpecification struct {
}

// PhysicalAssetSpecificationProperty ...
type PhysicalAssetSpecificationProperty struct {
}

// MaterialSpecification ...
type MaterialSpecification struct {
}

// MaterialSpecificationProperty ...
type MaterialSpecificationProperty struct {
}

// OperationsCapability ...
type OperationsCapability struct {
}

// OperationsCapabilityInformation ...
type OperationsCapabilityInformation struct {
}

// PersonnelCapability ...
type PersonnelCapability struct {
}

// PersonnelCapabilityProperty ...
type PersonnelCapabilityProperty struct {
}

// EquipmentCapability ...
type EquipmentCapability struct {
}

// EquipmentCapabilityProperty ...
type EquipmentCapabilityProperty struct {
}

// PhysicalAssetCapability ...
type PhysicalAssetCapability struct {
}

// PhysicalAssetCapabilityProperty ...
type PhysicalAssetCapabilityProperty struct {
}

// MaterialCapability ...
type MaterialCapability struct {
}

// MaterialCapabilityProperty ...
type MaterialCapabilityProperty struct {
}

// ProcessSegmentCapability ...
type ProcessSegmentCapability struct {
}

// OperationsPerformance ...
type OperationsPerformance struct {
}

// OperationsResponse ...
type OperationsResponse struct {
}

// OpSegmentResponse ...
type OpSegmentResponse struct {
}

// SegmentResponse ...
type SegmentResponse struct {
}

// OpSegmentData ...
type OpSegmentData struct {
}

// SegmentData ...
type SegmentData struct {
}

// OpPersonnelActual ...
type OpPersonnelActual struct {
}

// OpPersonnelActualProperty ...
type OpPersonnelActualProperty struct {
}

// OpEquipmentActual ...
type OpEquipmentActual struct {
}

// OpEquipmentActualProperty ...
type OpEquipmentActualProperty struct {
}

// OpPhysicalAssetActual ...
type OpPhysicalAssetActual struct {
}

// OpPhysicalAssetActualProperty ...
type OpPhysicalAssetActualProperty struct {
}

// OpMaterialActual ...
type OpMaterialActual struct {
}

// OpMaterialActualProperty ...
type OpMaterialActualProperty struct {
}

// PersonnelActual ...
type PersonnelActual struct {
}

// PersonnelActualProperty ...
type PersonnelActualProperty struct {
}

// EquipmentActual ...
type EquipmentActual struct {
}

// EquipmentActualProperty ...
type EquipmentActualProperty struct {
}

// PhysicalAssetActual ...
type PhysicalAssetActual struct {
}

// PhysicalAssetActualProperty ...
type PhysicalAssetActualProperty struct {
}

// MaterialActual ...
type MaterialActual struct {
}

// MaterialActualProperty ...
type MaterialActualProperty struct {
}

// OperationsSchedule ...
type OperationsSchedule struct {
}

// OperationsRequest ...
type OperationsRequest struct {
}

// OpSegmentRequirement ...
type OpSegmentRequirement struct {
}

// SegmentRequirement ...
type SegmentRequirement struct {
}

// PersonnelRequirement ...
type PersonnelRequirement struct {
}

// PersonnelRequirementProperty ...
type PersonnelRequirementProperty struct {
}

// EquipmentRequirement ...
type EquipmentRequirement struct {
}

// EquipmentRequirementProperty ...
type EquipmentRequirementProperty struct {
}

// PhysicalAssetRequirement ...
type PhysicalAssetRequirement struct {
}

// PhysicalAssetRequirementProperty ...
type PhysicalAssetRequirementProperty struct {
}

// MaterialRequirement ...
type MaterialRequirement struct {
}

// MaterialRequirementProperty ...
type MaterialRequirementProperty struct {
}

// ResourceRelationshipNetworkInformation ...
type ResourceRelationshipNetworkInformation struct {
}

// ResourceNetworkConnectionType ...
type ResourceNetworkConnectionType struct {
}

// ResourceRelationshipNetwork ...
type ResourceRelationshipNetwork struct {
}

// ResourceNetworkConnection ...
type ResourceNetworkConnection struct {
}

// ResourceReference ...
type ResourceReference struct {
}

// ResourceReferenceProperty ...
type ResourceReferenceProperty struct {
}

// RNCTypeProperty ...
type RNCTypeProperty struct {
}

// RRNProperty ...
type RRNProperty struct {
}

// RNCProperty ...
type RNCProperty struct {
}

// TransactionProfile ...
type TransactionProfile struct {
}

// SupportedAction ...
type SupportedAction struct {
}

// WorkAlertInformation ...
type WorkAlertInformation struct {
}

// WorkAlertDefinition ...
type WorkAlertDefinition struct {
}

// WorkAlert ...
type WorkAlert struct {
}

// WorkAlertDefinitionProperty ...
type WorkAlertDefinitionProperty struct {
}

// WorkAlertProperty ...
type WorkAlertProperty struct {
}

// WorkCalendarInformation ...
type WorkCalendarInformation struct {
}

// WorkCalendarDefinition ...
type WorkCalendarDefinition struct {
}

// WorkCalendarDefinitionEntry ...
type WorkCalendarDefinitionEntry struct {
}

// WorkCalendarDefinitionEntryProperty ...
type WorkCalendarDefinitionEntryProperty struct {
}

// WorkCalendarDefinitionProperty ...
type WorkCalendarDefinitionProperty struct {
}

// WorkCalendar ...
type WorkCalendar struct {
}

// WorkCalendarEntry ...
type WorkCalendarEntry struct {
}

// WorkCalendarEntryProperty ...
type WorkCalendarEntryProperty struct {
}

// WorkCalendarProperty ...
type WorkCalendarProperty struct {
}

// WorkCapabilityInformation ...
type WorkCapabilityInformation struct {
}

// WorkCapability ...
type WorkCapability struct {
}

// WorkMasterCapability ...
type WorkMasterCapability struct {
}

// WorkDefinition ...
type WorkDefinition struct {
}

// WorkDefinitionInformation ...
type WorkDefinitionInformation struct {
}

// WorkMaster ...
type WorkMaster struct {
}

// WorkDirective ...
type WorkDirective struct {
}

// WorkflowSpecificationInformation ...
type WorkflowSpecificationInformation struct {
}

// WorkflowSpecification ...
type WorkflowSpecification struct {
}

// WorkflowSpecificationNode ...
type WorkflowSpecificationNode struct {
}

// WorkflowSpecificationConnection ...
type WorkflowSpecificationConnection struct {
}

// WorkflowSpecificationNodeType ...
type WorkflowSpecificationNodeType struct {
}

// WorkflowSpecificationConnectionType ...
type WorkflowSpecificationConnectionType struct {
}

// WorkflowSpecificationProperty ...
type WorkflowSpecificationProperty struct {
}

// WorkflowSpecificationNodeProperty ...
type WorkflowSpecificationNodeProperty struct {
}

// WorkflowSpecificationNodeTypeProperty ...
type WorkflowSpecificationNodeTypeProperty struct {
}

// WorkflowSpecificationConnectionProperty ...
type WorkflowSpecificationConnectionProperty struct {
}

// WorkflowSpecificationConnectionTypeProperty ...
type WorkflowSpecificationConnectionTypeProperty struct {
}

// WorkPerformance ...
type WorkPerformance struct {
}

// WorkResponse ...
type WorkResponse struct {
}

// JobResponse ...
type JobResponse struct {
}

// JobResponseList ...
type JobResponseList struct {
}

// WorkRecord ...
type WorkRecord struct {
}

// WorkRecordEntry ...
type WorkRecordEntry struct {
}

// WorkRecordSpecification ...
type WorkRecordSpecification struct {
}

// WorkSchedule ...
type WorkSchedule struct {
}

// WorkRequest ...
type WorkRequest struct {
}

// JobList ...
type JobList struct {
}

// JobOrder ...
type JobOrder struct {
}
