// Code generated by xgen. DO NOT EDIT.

package b2mml

// OperationsSchedule ...
type OperationsSchedule *OperationsScheduleType

// OperationsRequest ...
type OperationsRequest *OperationsRequestType

// GetOperationsSchedule ...
type GetOperationsSchedule *GetOperationsScheduleType

// ShowOperationsSchedule ...
type ShowOperationsSchedule *ShowOperationsScheduleType

// ProcessOperationsSchedule ...
type ProcessOperationsSchedule *ProcessOperationsScheduleType

// AcknowledgeOperationsSchedule ...
type AcknowledgeOperationsSchedule *AcknowledgeOperationsScheduleType

// ChangeOperationsSchedule ...
type ChangeOperationsSchedule *ChangeOperationsScheduleType

// RespondOperationsSchedule ...
type RespondOperationsSchedule *RespondOperationsScheduleType

// CancelOperationsSchedule ...
type CancelOperationsSchedule *CancelOperationsScheduleType

// SyncOperationsSchedule ...
type SyncOperationsSchedule *SyncOperationsScheduleType

// OperationsScheduleType ...
type OperationsScheduleType struct {
	ExtendedOperationsSchedule []*OperationsScheduleType
	ID                         *IdentifierType          `xml:"ID"`
	Description                []*DescriptionType       `xml:"Description"`
	Version                    *IdentifierType          `xml:"Version"`
	PublishedDate              *DateTimeType            `xml:"PublishedDate"`
	StartTime                  *DateTimeType            `xml:"StartTime"`
	EndTime                    *DateTimeType            `xml:"EndTime"`
	HierarchyScope             *HierarchyScopeType      `xml:"HierarchyScope"`
	OperationsType             *OperationsTypeType      `xml:"OperationsType"`
	ScheduleState              *RequestStateType        `xml:"ScheduleState"`
	OperationsRequest          []*OperationsRequestType `xml:"OperationsRequest"`
}

// OperationsRequestType ...
type OperationsRequestType struct {
	ExtendedOperationsRequest          []*OperationsRequestType
	ID                                 *IdentifierType                         `xml:"ID"`
	Description                        []*DescriptionType                      `xml:"Description"`
	Version                            *IdentifierType                         `xml:"Version"`
	StartTime                          *DateTimeType                           `xml:"StartTime"`
	EndTime                            *DateTimeType                           `xml:"EndTime"`
	HierarchyScope                     *HierarchyScopeType                     `xml:"HierarchyScope"`
	OperationsType                     *OperationsTypeType                     `xml:"OperationsType"`
	Priority                           *PriorityType                           `xml:"Priority"`
	RequestState                       *RequestStateType                       `xml:"RequestState"`
	OperationsDefinitionID             *IdentifierType                         `xml:"OperationsDefinitionID"`
	OperationsSegmentID                *IdentifierType                         `xml:"OperationsSegmentID"`
	SegmentRequirement                 []*OpSegmentRequirementType             `xml:"SegmentRequirement"`
	RequestedSegmentResponse           []*OpSegmentResponseType                `xml:"RequestedSegmentResponse"`
	RequiredByRequestedSegmentResponse *RequiredByRequestedSegmentResponseType `xml:"RequiredByRequestedSegmentResponse"`
}

// OpSegmentRequirementType ...
type OpSegmentRequirementType struct {
	ExtendedOpSegmentRequirement       []*OpSegmentRequirement
	ID                                 *IdentifierType                         `xml:"ID"`
	Description                        []*DescriptionType                      `xml:"Description"`
	Version                            *IdentifierType                         `xml:"Version"`
	EarliestStartTime                  *DateTimeType                           `xml:"EarliestStartTime"`
	LatestEndTime                      *DateTimeType                           `xml:"LatestEndTime"`
	HierarchyScope                     *HierarchyScopeType                     `xml:"HierarchyScope"`
	OperationsType                     *OperationsTypeType                     `xml:"OperationsType"`
	ProcessSegmentID                   *IdentifierType                         `xml:"ProcessSegmentID"`
	Duration                           *string                                 `xml:"Duration"`
	OperationsDefinitionID             *IdentifierType                         `xml:"OperationsDefinitionID"`
	OperationsSegmentID                *IdentifierType                         `xml:"OperationsSegmentID"`
	SegmentState                       *RequestStateType                       `xml:"SegmentState"`
	SegmentParameter                   []*ParameterTypeType                    `xml:"SegmentParameter"`
	PersonnelRequirement               []*OpPersonnelRequirementType           `xml:"PersonnelRequirement"`
	EquipmentRequirement               []*OpEquipmentRequirementType           `xml:"EquipmentRequirement"`
	PhysicalAssetRequirement           []*OpPhysicalAssetRequirementType       `xml:"PhysicalAssetRequirement"`
	MaterialRequirement                []*OpMaterialRequirementType            `xml:"MaterialRequirement"`
	SegmentRequirementChild            []*OpSegmentRequirementType             `xml:"SegmentRequirementChild"`
	RequestedSegmentResponse           []*OpSegmentResponseType                `xml:"RequestedSegmentResponse"`
	RequiredByRequestedSegmentResponse *RequiredByRequestedSegmentResponseType `xml:"RequiredByRequestedSegmentResponse"`
}

// DataArea ...
type DataArea struct {
	Get                *TransGetType             `xml:"Get"`
	OperationsSchedule []*OperationsScheduleType `xml:"OperationsSchedule"`
}

// GetOperationsScheduleType ...
type GetOperationsScheduleType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ShowOperationsScheduleType ...
type ShowOperationsScheduleType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ProcessOperationsScheduleType ...
type ProcessOperationsScheduleType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// AcknowledgeOperationsScheduleType ...
type AcknowledgeOperationsScheduleType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ChangeOperationsScheduleType ...
type ChangeOperationsScheduleType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// RespondOperationsScheduleType ...
type RespondOperationsScheduleType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// CancelOperationsScheduleType ...
type CancelOperationsScheduleType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// SyncOperationsScheduleType ...
type SyncOperationsScheduleType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}
