// Code generated by xgen. DO NOT EDIT.

package b2mml

// ErrorMessage ...
type ErrorMessage *ErrorMessageType

// GetErrorMessage ...
type GetErrorMessage *GetErrorMessageType

// ShowErrorMessage ...
type ShowErrorMessage *ShowErrorMessageType

// ProcessErrorMessage ...
type ProcessErrorMessage *ProcessErrorMessageType

// AcknowledgeErrorMessage ...
type AcknowledgeErrorMessage *AcknowledgeErrorMessageType

// ChangeErrorMessage ...
type ChangeErrorMessage *ChangeErrorMessageType

// RespondErrorMessage ...
type RespondErrorMessage *RespondErrorMessageType

// CancelErrorMessage ...
type CancelErrorMessage *CancelErrorMessageType

// SyncErrorMessage ...
type SyncErrorMessage *SyncErrorMessageType

// ErrorMessageType ...
type ErrorMessageType struct {
	ErrorDescription []string          `xml:"ErrorDescription"`
	ThrownFrom       string            `xml:"ThrownFrom"`
	TimeStamp        *DateTimeType     `xml:"TimeStamp"`
	ErrorType        *ErrorTypeType    `xml:"ErrorType"`
	ErrorCode        *string           `xml:"ErrorCode"`
	CausedBy         *ErrorMessageType `xml:"CausedBy"`
}

// ErrorTypeType ...
type ErrorTypeType struct {
	OtherValueAttr *string `xml:"OtherValue,attr"`
	*ErrorType1Type
}

// ErrorType1Type ...
type ErrorType1Type struct {
}

// DataArea ...
type DataArea struct {
	Get          *TransGetType       `xml:"Get"`
	ErrorMessage []*ErrorMessageType `xml:"ErrorMessage"`
}

// GetErrorMessageType ...
type GetErrorMessageType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ShowErrorMessageType ...
type ShowErrorMessageType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ProcessErrorMessageType ...
type ProcessErrorMessageType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// AcknowledgeErrorMessageType ...
type AcknowledgeErrorMessageType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ChangeErrorMessageType ...
type ChangeErrorMessageType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// RespondErrorMessageType ...
type RespondErrorMessageType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// CancelErrorMessageType ...
type CancelErrorMessageType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// SyncErrorMessageType ...
type SyncErrorMessageType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}
