// Code generated by xgen. DO NOT EDIT.

package b2mml

// PersonnelInformation ...
// type PersonnelInformation *PersonnelInformationType

// PersonnelClass is A representation of a grouping of persons with similar characteristics for a definite purpose such as
// manufacturing operations definition, scheduling, capability and performance is a personnel class.
// Any person may be a member of zero or more personnel classes. A personnel class may be defined as
// a specialization of zero or more personnel class. A personnel class may be made up of zero or more personnel class(s).
// type PersonnelClass *PersonnelClassType

// Person is A representation of a specifically identified individual is a person.
// A person may be a member of zero or more personnel classes.
// type Person *PersonType

// GetPersonnelInformation ...
type GetPersonnelInformation *GetPersonnelInformationType

// ShowPersonnelInformation ...
type ShowPersonnelInformation *ShowPersonnelInformationType

// ProcessPersonnelInformation ...
type ProcessPersonnelInformation *ProcessPersonnelInformationType

// AcknowledgePersonnelInformation ...
type AcknowledgePersonnelInformation *AcknowledgePersonnelInformationType

// ChangePersonnelInformation ...
type ChangePersonnelInformation *ChangePersonnelInformationType

// RespondPersonnelInformation ...
type RespondPersonnelInformation *RespondPersonnelInformationType

// CancelPersonnelInformation ...
type CancelPersonnelInformation *CancelPersonnelInformationType

// SyncPersonnelInformation ...
type SyncPersonnelInformation *SyncPersonnelInformationType

// GetPersonnelClass ...
type GetPersonnelClass *GetPersonnelClassType

// ShowPersonnelClass ...
type ShowPersonnelClass *ShowPersonnelClassType

// ProcessPersonnelClass ...
type ProcessPersonnelClass *ProcessPersonnelClassType

// AcknowledgePersonnelClass ...
type AcknowledgePersonnelClass *AcknowledgePersonnelClassType

// ChangePersonnelClass ...
type ChangePersonnelClass *ChangePersonnelClassType

// RespondPersonnelClass ...
type RespondPersonnelClass *RespondPersonnelClassType

// CancelPersonnelClass ...
type CancelPersonnelClass *CancelPersonnelClassType

// SyncPersonnelClass ...
type SyncPersonnelClass *SyncPersonnelClassType

// GetPerson ...
type GetPerson *GetPersonType

// ShowPerson ...
type ShowPerson *ShowPersonType

// ProcessPerson ...
type ProcessPerson *ProcessPersonType

// AcknowledgePerson ...
type AcknowledgePerson *AcknowledgePersonType

// ChangePerson ...
type ChangePerson *ChangePersonType

// RespondPerson ...
type RespondPerson *RespondPersonType

// CancelPerson ...
type CancelPerson *CancelPersonType

// SyncPerson ...
type SyncPerson *SyncPersonType

// PersonnelInformationType ...
type PersonnelInformationType struct {
	ExtendedPersonnelInformation []*PersonnelInformationType
	ID                           *IdentifierType          `xml:"ID"`
	Description                  []*DescriptionType       `xml:"Description"`
	HierarchyScope               *HierarchyScopeType      `xml:"HierarchyScope"`
	PublishedDate                *DateTimeType            `xml:"PublishedDate"`
	Person                       []*PersonType            `xml:"Person"`
	PersonnelClass               []*PersonnelClassType    `xml:"PersonnelClass"`
	TestSpecification            []*TestSpecificationType `xml:"TestSpecification"`
}

// PersonType ...
type PersonType struct {
	ExtendedPerson      []*PersonType
	ID                  *IdentifierType        `xml:"ID"`
	Version             *IdentifierType        `xml:"Version"`
	Description         []*DescriptionType     `xml:"Description"`
	PublishedDate       *DateTimeType          `xml:"PublishedDate"`
	EffectiveStartDate  *DateTimeType          `xml:"EffectiveStartDate"`
	EffectiveEndDate    *DateTimeType          `xml:"EffectiveEndDate"`
	HierarchyScope      *HierarchyScopeType    `xml:"HierarchyScope"`
	PersonName          *PersonNameType        `xml:"PersonName"`
	SpatialDefinition   *SpatialDefinitionType `xml:"SpatialDefinition"`
	OperationalLocation *ResourceLocationType  `xml:"OperationalLocation"`
	PersonProperty      []*PersonPropertyType  `xml:"PersonProperty"`
	PersonnelClassID    []*IdentifierType      `xml:"PersonnelClassID"`
	TestSpecificationID []*IdentifierType      `xml:"TestSpecificationID"`
}

// PersonPropertyType ...
type PersonPropertyType struct {
	ExtendedPersonProperty   *PersonProperty
	ID                       *IdentifierType       `xml:"ID"`
	Description              []*DescriptionType    `xml:"Description"`
	Value                    []*ValueType          `xml:"Value"`
	PersonPropertyChild      []*PersonPropertyType `xml:"PersonPropertyChild"`
	PersonnelClassPropertyID *IdentifierType       `xml:"PersonnelClassPropertyID"`
}

// PersonnelClassType ...
type PersonnelClassType struct {
	ExtendedPersonnelClass *PersonnelClassType
	ID                     *IdentifierType               `xml:"ID"`
	Version                *IdentifierType               `xml:"Version"`
	Description            []*DescriptionType            `xml:"Description"`
	PublishedDate          *DateTimeType                 `xml:"PublishedDate"`
	EffectiveStartDate     *DateTimeType                 `xml:"EffectiveStartDate"`
	EffectiveEndDate       *DateTimeType                 `xml:"EffectiveEndDate"`
	HierarchyScope         *HierarchyScopeType           `xml:"HierarchyScope"`
	PersonnelClassBaseID   []*IdentifierType             `xml:"PersonnelClassBaseID"`
	PersonnelClassProperty []*PersonnelClassPropertyType `xml:"PersonnelClassProperty"`
	PersonSourceID         []*IdentifierType             `xml:"PersonSourceID"`
	TestSpecificationID    []*IdentifierType             `xml:"TestSpecificationID"`
}

// PersonnelClassPropertyType ...
type PersonnelClassPropertyType struct {
	ExtendedPersonnelClassProperty *PersonnelClassProperty
	ID                             *IdentifierType               `xml:"ID"`
	Description                    []*DescriptionType            `xml:"Description"`
	PropertyType                   *ClassPropertyTypeType        `xml:"PropertyType"`
	Value                          []*ValueType                  `xml:"Value"`
	PersonnelClassPropertyChild    []*PersonnelClassPropertyType `xml:"PersonnelClassPropertyChild"`
}

// DataArea ...
// type DataArea struct {
// 	Get                  *TransGetType               `xml:"Get"`
// 	PersonnelInformation []*PersonnelInformationType `xml:"PersonnelInformation"`
// }

// GetPersonnelInformationType ...
type GetPersonnelInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ShowPersonnelInformationType ...
type ShowPersonnelInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ProcessPersonnelInformationType ...
type ProcessPersonnelInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// AcknowledgePersonnelInformationType ...
type AcknowledgePersonnelInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ChangePersonnelInformationType ...
type ChangePersonnelInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// RespondPersonnelInformationType ...
type RespondPersonnelInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// CancelPersonnelInformationType ...
type CancelPersonnelInformationType struct {
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// SyncPersonnelInformationType ...
type SyncPersonnelInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// GetPersonnelClassType ...
type GetPersonnelClassType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ShowPersonnelClassType ...
type ShowPersonnelClassType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ProcessPersonnelClassType ...
type ProcessPersonnelClassType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// AcknowledgePersonnelClassType ...
type AcknowledgePersonnelClassType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ChangePersonnelClassType ...
type ChangePersonnelClassType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// RespondPersonnelClassType ...
type RespondPersonnelClassType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// CancelPersonnelClassType ...
type CancelPersonnelClassType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// SyncPersonnelClassType ...
type SyncPersonnelClassType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// GetPersonType ...
type GetPersonType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ShowPersonType ...
type ShowPersonType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ProcessPersonType ...
type ProcessPersonType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// AcknowledgePersonType ...
type AcknowledgePersonType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ChangePersonType ...
type ChangePersonType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// RespondPersonType ...
type RespondPersonType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// CancelPersonType ...
type CancelPersonType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// SyncPersonType ...
type SyncPersonType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}
