// Code generated by xgen. DO NOT EDIT.

package b2mml

// AmountType ...
type AmountType struct {
	CurrencyIDAttr                *string `xml:"currencyID,attr"`
	CurrencyCodeListVersionIDAttr *string `xml:"currencyCodeListVersionID,attr"`
	Value                         float64 `xml:",chardata"`
}

// BinaryObjectType ...
type BinaryObjectType struct {
	FormatAttr           *string `xml:"format,attr"`
	MimeCodeAttr         *string `xml:"mimeCode,attr"`
	EncodingCodeAttr     *string `xml:"encodingCode,attr"`
	CharacterSetCodeAttr *string `xml:"characterSetCode,attr"`
	UriAttr              *string `xml:"uri,attr"`
	FilenameAttr         *string `xml:"filename,attr"`
	Value                string  `xml:",chardata"`
}

// CodeType ...
type CodeType struct {
	ListIDAttr         *string `xml:"listID,attr"`
	ListAgencyIDAttr   *string `xml:"listAgencyID,attr"`
	ListAgencyNameAttr *string `xml:"listAgencyName,attr"`
	ListNameAttr       *string `xml:"listName,attr"`
	ListVersionIDAttr  *string `xml:"listVersionID,attr"`
	NameAttr           *string `xml:"name,attr"`
	LanguageIDAttr     *string `xml:"languageID,attr"`
	ListURIAttr        *string `xml:"listURI,attr"`
	ListSchemeURIAttr  *string `xml:"listSchemeURI,attr"`
	Value              string  `xml:",chardata"`
}

// DateTimeType ...
type DateTimeType struct {
	FormatAttr *string `xml:"format,attr"`
	Value      string  `xml:",chardata"`
}

// IdentifierType ...
type IdentifierType struct {
	SchemeIDAttr         *string `xml:"schemeID,attr"`
	SchemeNameAttr       *string `xml:"schemeName,attr"`
	SchemeAgencyIDAttr   *string `xml:"schemeAgencyID,attr"`
	SchemeAgencyNameAttr *string `xml:"schemeAgencyName,attr"`
	SchemeVersionIDAttr  *string `xml:"schemeVersionID,attr"`
	SchemeDataURIAttr    *string `xml:"schemeDataURI,attr"`
	SchemeURIAttr        *string `xml:"schemeURI,attr"`
	Value                string  `xml:",chardata"`
}

// IndicatorType ...
type IndicatorType bool

// MeasureType ...
type MeasureType struct {
	UnitCodeAttr              *string `xml:"unitCode,attr"`
	UnitCodeListVersionIDAttr *string `xml:"unitCodeListVersionID,attr"`
	Value                     float64 `xml:",chardata"`
}

// NameType ...
type NameType struct {
	LanguageIDAttr *string `xml:"languageID,attr"`
	Value          string  `xml:",chardata"`
}

// NumericType ...
type NumericType struct {
	FormatAttr *string `xml:"format,attr"`
	Value      float64 `xml:",chardata"`
}

// QuantityType ...
type QuantityType struct {
	UnitCodeAttr               *string `xml:"unitCode,attr"`
	UnitCodeListIDAttr         *string `xml:"unitCodeListID,attr"`
	UnitCodeListAgencyIDAttr   *string `xml:"unitCodeListAgencyID,attr"`
	UnitCodeListAgencyNameAttr *string `xml:"unitCodeListAgencyName,attr"`
	Value                      float64 `xml:",chardata"`
}

// TextType ...
type TextType struct {
	LanguageIDAttr *string `xml:"languageID,attr"`
	Value          string  `xml:",chardata"`
}
