// Code generated by xgen. DO NOT EDIT.

package b2mml

// OperationsDefinitionInformation ...
// type OperationsDefinitionInformation *OperationsDefinitionInformationType

// OperationsDefinition ...
// type OperationsDefinition *OperationsDefinitionType

// OperationsSegment ...
// type OperationsSegment *OperationsSegmentType

// OperationsMaterialBill ...
// type OperationsMaterialBill *OperationsMaterialBillType

// GetOperationsDefinitionInformation ...
type GetOperationsDefinitionInformation *GetOperationsDefinitionInformationType

// ShowOperationsDefinitionInformation ...
type ShowOperationsDefinitionInformation *ShowOperationsDefinitionInformationType

// ProcessOperationsDefinitionInformation ...
type ProcessOperationsDefinitionInformation *ProcessOperationsDefinitionInformationType

// AcknowledgeOperationsDefinitionInformation ...
type AcknowledgeOperationsDefinitionInformation *AcknowledgeOperationsDefinitionInformationType

// ChangeOperationsDefinitionInformation ...
type ChangeOperationsDefinitionInformation *ChangeOperationsDefinitionInformationType

// RespondOperationsDefinitionInformation ...
type RespondOperationsDefinitionInformation *RespondOperationsDefinitionInformationType

// CancelOperationsDefinitionInformation ...
type CancelOperationsDefinitionInformation *CancelOperationsDefinitionInformationType

// SyncOperationsDefinitionInformation ...
type SyncOperationsDefinitionInformation *SyncOperationsDefinitionInformationType

// GetOperationsDefinition ...
type GetOperationsDefinition *GetOperationsDefinitionType

// ShowOperationsDefinition ...
type ShowOperationsDefinition *ShowOperationsDefinitionType

// ProcessOperationsDefinition ...
type ProcessOperationsDefinition *ProcessOperationsDefinitionType

// AcknowledgeOperationsDefinition ...
type AcknowledgeOperationsDefinition *AcknowledgeOperationsDefinitionType

// ChangeOperationsDefinition ...
type ChangeOperationsDefinition *ChangeOperationsDefinitionType

// RespondOperationsDefinition ...
type RespondOperationsDefinition *RespondOperationsDefinitionType

// CancelOperationsDefinition ...
type CancelOperationsDefinition *CancelOperationsDefinitionType

// SyncOperationsDefinition ...
type SyncOperationsDefinition *SyncOperationsDefinitionType

// GetOperationsMaterialBill ...
type GetOperationsMaterialBill *GetOperationsMaterialBillType

// ShowOperationsMaterialBill ...
type ShowOperationsMaterialBill *ShowOperationsMaterialBillType

// ProcessOperationsMaterialBill ...
type ProcessOperationsMaterialBill *ProcessOperationsMaterialBillType

// AcknowledgeOperationsMaterialBill ...
type AcknowledgeOperationsMaterialBill *AcknowledgeOperationsMaterialBillType

// ChangeOperationsMaterialBill ...
type ChangeOperationsMaterialBill *ChangeOperationsMaterialBillType

// RespondOperationsMaterialBill ...
type RespondOperationsMaterialBill *RespondOperationsMaterialBillType

// CancelOperationsMaterialBill ...
type CancelOperationsMaterialBill *CancelOperationsMaterialBillType

// SyncOperationsMaterialBill ...
type SyncOperationsMaterialBill *SyncOperationsMaterialBillType

// OperationsDefinitionInformationType ...
type OperationsDefinitionInformationType struct {
	ExtendedOperationsDefinitionInformation *OperationsDefinitionInformationType
	ID                                      *IdentifierType               `xml:"ID"`
	Description                             []*DescriptionType            `xml:"Description"`
	HierarchyScope                          *HierarchyScopeType           `xml:"HierarchyScope"`
	PublishedDate                           *DateTimeType                 `xml:"PublishedDate"`
	OperationsDefinition                    []*OperationsDefinitionType   `xml:"OperationsDefinition"`
	OperationsSegment                       []*OperationsSegmentType      `xml:"OperationsSegment"`
	OperationsMaterialBill                  []*OperationsMaterialBillType `xml:"OperationsMaterialBill"`
}

// OperationsDefinitionType ...
type OperationsDefinitionType struct {
	ExtendedOperationsDefinition  *OperationsDefinitionType
	ID                            *IdentifierType          `xml:"ID"`
	Description                   []*DescriptionType       `xml:"Description"`
	Version                       *IdentifierType          `xml:"Version"`
	PublishedDate                 *DateTimeType            `xml:"PublishedDate"`
	EffectiveStartDate            *DateTimeType            `xml:"EffectiveStartDate"`
	EffectiveEndDate              *DateTimeType            `xml:"EffectiveEndDate"`
	HierarchyScope                *HierarchyScopeType      `xml:"HierarchyScope"`
	OperationsType                *OperationsTypeType      `xml:"OperationsType"`
	DefinitionType                *DefinitionTypeType      `xml:"DefinitionType"`
	OperationsSegment             []*OperationsSegmentType `xml:"OperationsSegment"`
	BillOfMaterialsID             []*IdentifierType        `xml:"BillOfMaterialsID"`
	WorkMasterSourceID            []*IdentifierType        `xml:"WorkMasterSourceID"`
	BillOfResourcesID             []*IdentifierType        `xml:"BillOfResourcesID"`
	OperationsMaterialBillID      []*IdentifierType        `xml:"OperationsMaterialBillID"`
	OperationsDefinitionPatternID *IdentifierType          `xml:"OperationsDefinitionPatternID"`
}

// OperationsMaterialBillType ...
type OperationsMaterialBillType struct {
	ExtendedOperationsMaterialBill *OperationsMaterialBillType
	ID                             *IdentifierType                   `xml:"ID"`
	Description                    []*DescriptionType                `xml:"Description"`
	Version                        *IdentifierType                   `xml:"Version"`
	PublishedDate                  *DateTimeType                     `xml:"PublishedDate"`
	EffectiveStartDate             *DateTimeType                     `xml:"EffectiveStartDate"`
	EffectiveEndDate               *DateTimeType                     `xml:"EffectiveEndDate"`
	HierarchyScope                 *HierarchyScopeType               `xml:"HierarchyScope"`
	UseType                        *CodeType                         `xml:"UseType"`
	OperationsMaterialBillItem     []*OperationsMaterialBillItemType `xml:"OperationsMaterialBillItem"`
	BillOfMaterialsID              []*IdentifierType                 `xml:"BillOfMaterialsID"`
}

// OperationsMaterialBillItemType ...
type OperationsMaterialBillItemType struct {
	ExtendedOperationsMaterialBillItem *OperationsMaterialBillItem
	ID                                 *IdentifierType                   `xml:"ID"`
	Description                        []*DescriptionType                `xml:"Description"`
	Version                            *IdentifierType                   `xml:"Version"`
	PublishedDate                      *DateTimeType                     `xml:"PublishedDate"`
	EffectiveStartDate                 *DateTimeType                     `xml:"EffectiveStartDate"`
	EffectiveEndDate                   *DateTimeType                     `xml:"EffectiveEndDate"`
	UseType                            *CodeType                         `xml:"UseType"`
	HierarchyScope                     *HierarchyScopeType               `xml:"HierarchyScope"`
	AssemblyBillOfMaterialItem         []*OperationsMaterialBillItemType `xml:"AssemblyBillOfMaterialItem"`
	AssemblyType                       *AssemblyTypeType                 `xml:"AssemblyType"`
	AssemblyRelationship               *AssemblyRelationshipType         `xml:"AssemblyRelationship"`
	MaterialSpecificationID            []*IdentifierType                 `xml:"MaterialSpecificationID"`
	Quantity                           []*QuantityValueType              `xml:"Quantity"`
}

// OperationsSegmentType ...
type OperationsSegmentType struct {
	ExtendedOperationsSegment    *OperationsSegmentType
	ID                           *IdentifierType                     `xml:"ID"`
	Description                  []*DescriptionType                  `xml:"Description"`
	Version                      *IdentifierType                     `xml:"Version"`
	PublishedDate                *DateTimeType                       `xml:"PublishedDate"`
	EffectiveStartDate           *DateTimeType                       `xml:"EffectiveStartDate"`
	EffectiveEndDate             *DateTimeType                       `xml:"EffectiveEndDate"`
	OperationsType               *OperationsTypeType                 `xml:"OperationsType"`
	DefinitionType               *DefinitionTypeType                 `xml:"DefinitionType"`
	HierarchyScope               *HierarchyScopeType                 `xml:"HierarchyScope"`
	Duration                     *string                             `xml:"Duration"`
	ProcessSegmentID             []*IdentifierType                   `xml:"ProcessSegmentID"`
	BillOfMaterialsID            []*IdentifierType                   `xml:"BillOfMaterialsID"`
	WorkMasterSourceID           []*IdentifierType                   `xml:"WorkMasterSourceID"`
	BillOfResourcesID            []*IdentifierType                   `xml:"BillOfResourcesID"`
	OperationsMaterialBillID     []*IdentifierType                   `xml:"OperationsMaterialBillID"`
	OperationsSegmentPatternID   *IdentifierType                     `xml:"OperationsSegmentPatternID"`
	ParameterSpecification       []*ParameterTypeType                `xml:"ParameterSpecification"`
	PersonnelSpecification       []*OpPersonnelSpecificationType     `xml:"PersonnelSpecification"`
	EquipmentSpecification       []*OpEquipmentSpecificationType     `xml:"EquipmentSpecification"`
	PhysicalAssetSpecification   []*OpPhysicalAssetSpecificationType `xml:"PhysicalAssetSpecification"`
	MaterialSpecification        []*OpMaterialSpecificationType      `xml:"MaterialSpecification"`
	SegmentDependency            []*SegmentDependencyType            `xml:"SegmentDependency"`
	DependentOperationsSegmentID []*IdentifierType                   `xml:"DependentOperationsSegmentID"`
	OperationsSegmentChild       []*OperationsSegmentType            `xml:"OperationsSegmentChild"`
}

// DataArea ...
// type DataArea struct {
// 	Get                             *TransGetType                          `xml:"Get"`
// 	OperationsDefinitionInformation []*OperationsDefinitionInformationType `xml:"OperationsDefinitionInformation"`
// }

// GetOperationsDefinitionInformationType ...
type GetOperationsDefinitionInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ShowOperationsDefinitionInformationType ...
type ShowOperationsDefinitionInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ProcessOperationsDefinitionInformationType ...
type ProcessOperationsDefinitionInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// AcknowledgeOperationsDefinitionInformationType ...
type AcknowledgeOperationsDefinitionInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ChangeOperationsDefinitionInformationType ...
type ChangeOperationsDefinitionInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// RespondOperationsDefinitionInformationType ...
type RespondOperationsDefinitionInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// CancelOperationsDefinitionInformationType ...
type CancelOperationsDefinitionInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// SyncOperationsDefinitionInformationType ...
type SyncOperationsDefinitionInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// GetOperationsDefinitionType ...
type GetOperationsDefinitionType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ShowOperationsDefinitionType ...
type ShowOperationsDefinitionType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ProcessOperationsDefinitionType ...
type ProcessOperationsDefinitionType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// AcknowledgeOperationsDefinitionType ...
type AcknowledgeOperationsDefinitionType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ChangeOperationsDefinitionType ...
type ChangeOperationsDefinitionType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// RespondOperationsDefinitionType ...
type RespondOperationsDefinitionType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// CancelOperationsDefinitionType ...
type CancelOperationsDefinitionType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// SyncOperationsDefinitionType ...
type SyncOperationsDefinitionType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// GetOperationsMaterialBillType ...
type GetOperationsMaterialBillType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ShowOperationsMaterialBillType ...
type ShowOperationsMaterialBillType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ProcessOperationsMaterialBillType ...
type ProcessOperationsMaterialBillType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// AcknowledgeOperationsMaterialBillType ...
type AcknowledgeOperationsMaterialBillType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ChangeOperationsMaterialBillType ...
type ChangeOperationsMaterialBillType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// RespondOperationsMaterialBillType ...
type RespondOperationsMaterialBillType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// CancelOperationsMaterialBillType ...
type CancelOperationsMaterialBillType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// SyncOperationsMaterialBillType ...
type SyncOperationsMaterialBillType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}
