// Code generated by xgen. DO NOT EDIT.

package b2mml

// OperationsPerformance ...
type OperationsPerformance *OperationsPerformanceType

// OperationsResponse ...
type OperationsResponse *OperationsResponseType

// GetOperationsPerformance ...
type GetOperationsPerformance *GetOperationsPerformanceType

// ShowOperationsPerformance ...
type ShowOperationsPerformance *ShowOperationsPerformanceType

// ProcessOperationsPerformance ...
type ProcessOperationsPerformance *ProcessOperationsPerformanceType

// AcknowledgeOperationsPerformance ...
type AcknowledgeOperationsPerformance *AcknowledgeOperationsPerformanceType

// ChangeOperationsPerformance ...
type ChangeOperationsPerformance *ChangeOperationsPerformanceType

// RespondOperationsPerformance ...
type RespondOperationsPerformance *RespondOperationsPerformanceType

// CancelOperationsPerformance ...
type CancelOperationsPerformance *CancelOperationsPerformanceType

// SyncOperationsPerformance ...
type SyncOperationsPerformance *SyncOperationsPerformanceType

// OperationsPerformanceType ...
type OperationsPerformanceType struct {
	ExtendedOperationsPerformance []*OperationsPerformanceType
	ID                            *IdentifierType           `xml:"ID"`
	Description                   []*DescriptionType        `xml:"Description"`
	Version                       *IdentifierType           `xml:"Version"`
	PublishedDate                 *DateTimeType             `xml:"PublishedDate"`
	StartTime                     *DateTimeType             `xml:"StartTime"`
	Endtime                       *DateTimeType             `xml:"Endtime"`
	HierarchyScope                *HierarchyScopeType       `xml:"HierarchyScope"`
	OperationsType                *OperationsTypeType       `xml:"OperationsType"`
	OperationsScheduleID          *IdentifierType           `xml:"OperationsScheduleID"`
	PerformanceState              *ResponseStateType        `xml:"PerformanceState"`
	OperationsResponse            []*OperationsResponseType `xml:"OperationsResponse"`
}

// OperationsResponseType ...
type OperationsResponseType struct {
	ExtendedOperationsResponse []*OperationsResponseType
	ID                         *IdentifierType          `xml:"ID"`
	Description                []*DescriptionType       `xml:"Description"`
	Version                    *IdentifierType          `xml:"Version"`
	StartTime                  *DateTimeType            `xml:"StartTime"`
	EndTime                    *DateTimeType            `xml:"EndTime"`
	HierarchyScope             *HierarchyScopeType      `xml:"HierarchyScope"`
	OperationsType             *OperationsTypeType      `xml:"OperationsType"`
	OperationsRequestID        []*IdentifierType        `xml:"OperationsRequestID"`
	SegmentRequirementID       []*IdentifierType        `xml:"SegmentRequirementID"`
	OperationsDefinitionID     []*IdentifierType        `xml:"OperationsDefinitionID"`
	OperationsSegmentID        []*IdentifierType        `xml:"OperationsSegmentID"`
	ResponseState              *ResponseStateType       `xml:"ResponseState"`
	SegmentResponse            []*OpSegmentResponseType `xml:"SegmentResponse"`
}

// DataArea ...
type DataArea struct {
	Get                   *TransGetType                `xml:"Get"`
	OperationsPerformance []*OperationsPerformanceType `xml:"OperationsPerformance"`
}

// GetOperationsPerformanceType ...
type GetOperationsPerformanceType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ShowOperationsPerformanceType ...
type ShowOperationsPerformanceType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ProcessOperationsPerformanceType ...
type ProcessOperationsPerformanceType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// AcknowledgeOperationsPerformanceType ...
type AcknowledgeOperationsPerformanceType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ChangeOperationsPerformanceType ...
type ChangeOperationsPerformanceType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// RespondOperationsPerformanceType ...
type RespondOperationsPerformanceType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// CancelOperationsPerformanceType ...
type CancelOperationsPerformanceType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// SyncOperationsPerformanceType ...
type SyncOperationsPerformanceType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}
