// Code generated by xgen. DO NOT EDIT.

package b2mml

// InformationObject ...
type InformationObject *InformationObjectTypeType

// InformationObjectType ...
type InformationObjectType *InformationObjectTypeType

// InformationObjectType1Type ...
type InformationObjectType1Type struct {
}

// InformationObjectTypeType ...
type InformationObjectTypeType struct {
	OtherValueAttr *string `xml:"OtherValue,attr"`
	*InformationObjectType1Type
}
