// Code generated by xgen. DO NOT EDIT.

package b2mml

// OperationsTestInformation is Operations test information is exchanged to communicate criteria that are to be applied to perform tests of personnel, equipment, physical assets and/or materials and to communicate the results of those tests.
// type OperationsTestInformation *OperationsTestInformationType

// TestSpecification is The test specification details the test specification criteria and the tested evaluated property(s)
// required for a testable object to match the quality or performance requirements of the business or
// particular customers. A test specification may contain other test specifications to form a hierarchy
// of test specifications.
// type TestSpecification *TestSpecificationType

// TestResult is Operations test information is exchanged to communicate test result for evaluated test criteria and/or
// property measurement for performed test specifications of personnel, equipment, physical assets and/or
// materials.  The test result details for the evaluation of test specification criteria and/or property
// measurement of the tested evaluated property(s) required for a testable object to match the quality
// or performance requirements of a test specification. A test result may contain other test results to
// form a hierarchy of test specifications.
// type TestResult *TestResultType

// GetOperationsTestInformation ...
type GetOperationsTestInformation *GetOperationsTestInformationType

// ShowOperationsTestInformation ...
type ShowOperationsTestInformation *ShowOperationsTestInformationType

// ProcessOperationsTestInformation ...
type ProcessOperationsTestInformation *ProcessOperationsTestInformationType

// AcknowledgeOperationsTestInformation ...
type AcknowledgeOperationsTestInformation *AcknowledgeOperationsTestInformationType

// ChangeOperationsTestInformation ...
type ChangeOperationsTestInformation *ChangeOperationsTestInformationType

// RespondOperationsTestInformation ...
type RespondOperationsTestInformation *RespondOperationsTestInformationType

// CancelOperationsTestInformation ...
type CancelOperationsTestInformation *CancelOperationsTestInformationType

// SyncOperationsTestInformation ...
type SyncOperationsTestInformation *SyncOperationsTestInformationType

// GetTestSpecification ...
type GetTestSpecification *GetTestSpecificationType

// ShowTestSpecification ...
type ShowTestSpecification *ShowTestSpecificationType

// ProcessTestSpecification ...
type ProcessTestSpecification *ProcessTestSpecificationType

// AcknowledgeTestSpecification ...
type AcknowledgeTestSpecification *AcknowledgeTestSpecificationType

// ChangeTestSpecification ...
type ChangeTestSpecification *ChangeTestSpecificationType

// RespondTestSpecification ...
type RespondTestSpecification *RespondTestSpecificationType

// CancelTestSpecification ...
type CancelTestSpecification *CancelTestSpecificationType

// SyncTestSpecification ...
type SyncTestSpecification *SyncTestSpecificationType

// GetTestResult ...
type GetTestResult *GetTestResultType

// ShowTestResult ...
type ShowTestResult *ShowTestResultType

// ProcessTestResult ...
type ProcessTestResult *ProcessTestResultType

// AcknowledgeTestResult ...
type AcknowledgeTestResult *AcknowledgeTestResultType

// ChangeTestResult ...
type ChangeTestResult *ChangeTestResultType

// RespondTestResult ...
type RespondTestResult *RespondTestResultType

// CancelTestResult ...
type CancelTestResult *CancelTestResultType

// SyncTestResult ...
type SyncTestResult *SyncTestResultType

// OperationsTestInformationType ...
type OperationsTestInformationType struct {
	ExtendedOperationsTestInformation []*OperationsTestInformationType
	ID                                *IdentifierType          `xml:"ID"`
	Description                       []*DescriptionType       `xml:"Description"`
	HierarchyScope                    *HierarchyScopeType      `xml:"HierarchyScope"`
	PublishedDate                     *DateTimeType            `xml:"PublishedDate"`
	TestSpecification                 []*TestSpecificationType `xml:"TestSpecification"`
	TestResult                        []*TestResultType        `xml:"TestResult"`
}

// TestSpecificationType ...
type TestSpecificationType struct {
	ExtendedTestSpecification   []*TestSpecificationType
	ID                          *IdentifierType                           `xml:"ID"`
	Description                 []*DescriptionType                        `xml:"Description"`
	Version                     *IdentifierType                           `xml:"Version"`
	PublishedEndDate            *DateTimeType                             `xml:"PublishedEndDate"`
	EffectiveStartDate          *DateTimeType                             `xml:"EffectiveStartDate"`
	EffectiveEndDate            *DateTimeType                             `xml:"EffectiveEndDate"`
	HierarchyScope              *HierarchyScopeType                       `xml:"HierarchyScope"`
	TestSampleSize              *ValueType                                `xml:"TestSampleSize"`
	RecurrenceQuantity          *ValueType                                `xml:"RecurrenceQuantity"`
	RecurrenceTimeInterval      *string                                   `xml:"RecurrenceTimeInterval"`
	PhysicalSampleRequired      *bool                                     `xml:"PhysicalSampleRequired"`
	TestSpecificationChild      []*TestSpecificationType                  `xml:"TestSpecificationChild"`
	TestSpecificationProperty   []*TestSpecificationPropertyType          `xml:"TestSpecificationProperty"`
	TestSpecificationCriteria   []*TestSpecificationCriteriaType          `xml:"TestSpecificationCriteria"`
	EvaluatedProperty           []*TestSpecificationEvaluatedPropertyType `xml:"EvaluatedProperty"`
	OperationsTestRequirementID *IdentifierType                           `xml:"OperationsTestRequirementID"`
	TestableObjectID            *IdentifierType                           `xml:"TestableObjectID"`
}

// TestSpecificationPropertyType ...
type TestSpecificationPropertyType struct {
	ExtendedTestSpecificationProperty []*TestSpecificationProperty
	ID                                *IdentifierType                  `xml:"ID"`
	Description                       []*DescriptionType               `xml:"Description"`
	Value                             []*ValueType                     `xml:"Value"`
	TestSpecificationPropertyChild    []*TestSpecificationPropertyType `xml:"TestSpecificationPropertyChild"`
}

// TestSpecificationCriteriaType ...
type TestSpecificationCriteriaType struct {
	ExtendedTestSpecificationCriteria []*TestSpecificationCriteria
	ID                                *IdentifierType    `xml:"ID"`
	Description                       []*DescriptionType `xml:"Description"`
	Sequence                          []*NumericType     `xml:"Sequence"`
	Expression                        []*TextType        `xml:"Expression"`
	Result                            []*TextType        `xml:"Result"`
	EvaluatedPropertyID               []*IdentifierType  `xml:"EvaluatedPropertyID"`
}

// TestSpecificationEvaluatedPropertyType ...
type TestSpecificationEvaluatedPropertyType struct {
	ExtendedEvaluatedProperty   []*EvaluatedProperty
	ID                          *IdentifierType    `xml:"ID"`
	Description                 []*DescriptionType `xml:"Description"`
	TestSpecificationCriteriaID []*IdentifierType  `xml:"TestSpecificationCriteriaID"`
	TestableObjectPropertyID    []*IdentifierType  `xml:"TestableObjectPropertyID"`
	WorkDefinitionID            []*IdentifierType  `xml:"WorkDefinitionID"`
}

// TestResultType ...
type TestResultType struct {
	ExtendedTestResult          []*TestResultType
	ID                          *IdentifierType            `xml:"ID"`
	Description                 []*DescriptionType         `xml:"Description"`
	EvaluationDate              *DateTimeType              `xml:"EvaluationDate"`
	Expiration                  *DateTimeType              `xml:"Expiration"`
	HierarchyScope              *HierarchyScopeType        `xml:"HierarchyScope"`
	TestableObjectID            *IdentifierType            `xml:"TestableObjectID"`
	OperationsTestRequirementID *IdentifierType            `xml:"OperationsTestRequirementID"`
	EvaluatedCriterionResult    *TextType                  `xml:"EvaluatedCriterionResult"`
	TestResultChild             []*TestResultType          `xml:"TestResultChild"`
	PropertyMeasurement         []*PropertyMeasurementType `xml:"PropertyMeasurement"`
}

// PropertyMeasurementType ...
type PropertyMeasurementType struct {
	ExtendedPropertyMeasurement []*PropertyMeasurement
	ID                          *IdentifierType    `xml:"ID"`
	Description                 []*DescriptionType `xml:"Description"`
	TestableObjectPropertyID    []*IdentifierType  `xml:"TestableObjectPropertyID"`
	MeasurementDate             *DateTimeType      `xml:"MeasurementDate"`
	Value                       *ValueType         `xml:"Value"`
	Expiration                  *DateTimeType      `xml:"Expiration"`
	WorkDefinitionID            *IdentifierType    `xml:"WorkDefinitionID"`
}

// DataArea ...
// type DataArea struct {
// 	Get                       *TransGetType                    `xml:"Get"`
// 	OperationsTestInformation []*OperationsTestInformationType `xml:"OperationsTestInformation"`
// }

// GetOperationsTestInformationType ...
type GetOperationsTestInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ShowOperationsTestInformationType ...
type ShowOperationsTestInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ProcessOperationsTestInformationType ...
type ProcessOperationsTestInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// AcknowledgeOperationsTestInformationType ...
type AcknowledgeOperationsTestInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ChangeOperationsTestInformationType ...
type ChangeOperationsTestInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// RespondOperationsTestInformationType ...
type RespondOperationsTestInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// CancelOperationsTestInformationType ...
type CancelOperationsTestInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// SyncOperationsTestInformationType ...
type SyncOperationsTestInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// GetTestSpecificationType ...
type GetTestSpecificationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ShowTestSpecificationType ...
type ShowTestSpecificationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ProcessTestSpecificationType ...
type ProcessTestSpecificationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// AcknowledgeTestSpecificationType ...
type AcknowledgeTestSpecificationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ChangeTestSpecificationType ...
type ChangeTestSpecificationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// RespondTestSpecificationType ...
type RespondTestSpecificationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// CancelTestSpecificationType ...
type CancelTestSpecificationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// SyncTestSpecificationType ...
type SyncTestSpecificationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// GetTestResultType ...
type GetTestResultType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ShowTestResultType ...
type ShowTestResultType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ProcessTestResultType ...
type ProcessTestResultType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// AcknowledgeTestResultType ...
type AcknowledgeTestResultType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ChangeTestResultType ...
type ChangeTestResultType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// RespondTestResultType ...
type RespondTestResultType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// CancelTestResultType ...
type CancelTestResultType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// SyncTestResultType ...
type SyncTestResultType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}
