// Code generated by xgen. DO NOT EDIT.

package b2mml

// WorkPerformance ...
// type WorkPerformance *WorkPerformanceType

// WorkResponse ...
// type WorkResponse *WorkResponseType

// JobResponse ...
// type JobResponse *JobResponseType

// JobResponseList ...
// type JobResponseList *JobResponseListType

// GetWorkPerformance ...
type GetWorkPerformance *GetWorkPerformanceType

// ShowWorkPerformance ...
type ShowWorkPerformance *ShowWorkPerformanceType

// ProcessWorkPerformance ...
type ProcessWorkPerformance *ProcessWorkPerformanceType

// AcknowledgeWorkPerformance ...
type AcknowledgeWorkPerformance *AcknowledgeWorkPerformanceType

// ChangeWorkPerformance ...
type ChangeWorkPerformance *ChangeWorkPerformanceType

// RespondWorkPerformance ...
type RespondWorkPerformance *RespondWorkPerformanceType

// CancelWorkPerformance ...
type CancelWorkPerformance *CancelWorkPerformanceType

// SyncWorkPerformance ...
type SyncWorkPerformance *SyncWorkPerformanceType

// GetWorkResponse ...
type GetWorkResponse *GetWorkResponseType

// ShowWorkResponse ...
type ShowWorkResponse *ShowWorkResponseType

// ProcessWorkResponse ...
type ProcessWorkResponse *ProcessWorkResponseType

// AcknowledgeWorkResponse ...
type AcknowledgeWorkResponse *AcknowledgeWorkResponseType

// ChangeWorkResponse ...
type ChangeWorkResponse *ChangeWorkResponseType

// RespondWorkResponse ...
type RespondWorkResponse *RespondWorkResponseType

// CancelWorkResponse ...
type CancelWorkResponse *CancelWorkResponseType

// SyncWorkResponse ...
type SyncWorkResponse *SyncWorkResponseType

// GetJobResponse ...
type GetJobResponse *GetJobResponseType

// ShowJobResponse ...
type ShowJobResponse *ShowJobResponseType

// ProcessJobResponse ...
type ProcessJobResponse *ProcessJobResponseType

// AcknowledgeJobResponse ...
type AcknowledgeJobResponse *AcknowledgeJobResponseType

// ChangeJobResponse ...
type ChangeJobResponse *ChangeJobResponseType

// RespondJobResponse ...
type RespondJobResponse *RespondJobResponseType

// CancelJobResponse ...
type CancelJobResponse *CancelJobResponseType

// SyncJobResponse ...
type SyncJobResponse *SyncJobResponseType

// GetJobResponseList ...
type GetJobResponseList *GetJobResponseListType

// ShowJobResponseList ...
type ShowJobResponseList *ShowJobResponseListType

// ProcessJobResponseList ...
type ProcessJobResponseList *ProcessJobResponseListType

// AcknowledgeJobResponseList ...
type AcknowledgeJobResponseList *AcknowledgeJobResponseListType

// ChangeJobResponseList ...
type ChangeJobResponseList *ChangeJobResponseListType

// RespondJobResponseList ...
type RespondJobResponseList *RespondJobResponseListType

// CancelJobResponseList ...
type CancelJobResponseList *CancelJobResponseListType

// SyncJobResponseList ...
type SyncJobResponseList *SyncJobResponseListType

// WorkPerformanceType ...
type WorkPerformanceType struct {
	ExtendedWorkPerformance []*WorkPerformanceType
	ID                      *IdentifierType        `xml:"ID"`
	Description             []*DescriptionType     `xml:"Description"`
	Version                 *IdentifierType        `xml:"Version"`
	PublishedDate           *DateTimeType          `xml:"PublishedDate"`
	StartTime               *DateTimeType          `xml:"StartTime"`
	EndTime                 *DateTimeType          `xml:"EndTime"`
	HierarchyScope          *HierarchyScopeType    `xml:"HierarchyScope"`
	WorkType                *OperationsTypeType    `xml:"WorkType"`
	WorkScheduleID          *IdentifierType        `xml:"WorkScheduleID"`
	WorkState               *ResponseStateType     `xml:"WorkState"`
	WorkResponse            []*WorkResponseType    `xml:"WorkResponse"`
	WorkPerformanceChild    []*WorkPerformanceType `xml:"WorkPerformanceChild"`
}

// WorkResponseType ...
type WorkResponseType struct {
	ExtendedWorkResponse               []*WorkResponseType
	ID                                 *IdentifierType                         `xml:"ID"`
	Description                        []*DescriptionType                      `xml:"Description"`
	Version                            *IdentifierType                         `xml:"Version"`
	PublishedDate                      *DateTimeType                           `xml:"PublishedDate"`
	StartTime                          *DateTimeType                           `xml:"StartTime"`
	EndTime                            *DateTimeType                           `xml:"EndTime"`
	HierarchyScope                     *HierarchyScopeType                     `xml:"HierarchyScope"`
	WorkType                           *OperationsTypeType                     `xml:"WorkType"`
	WorkRequestID                      *IdentifierType                         `xml:"WorkRequestID"`
	ResponseState                      *ResponseStateType                      `xml:"ResponseState"`
	WorkResponseChild                  []*WorkResponseType                     `xml:"WorkResponseChild"`
	JobResponse                        []*JobResponseType                      `xml:"JobResponse"`
	RequiredByRequestedSegmentResponse *RequiredByRequestedSegmentResponseType `xml:"RequiredByRequestedSegmentResponse"`
}

// JobResponseType ...
type JobResponseType struct {
	ExtendedJobResponse                []*JobResponseType
	ID                                 *IdentifierType                         `xml:"ID"`
	Description                        []*DescriptionType                      `xml:"Description"`
	Version                            *IdentifierType                         `xml:"Version"`
	PublishedDate                      *DateTimeType                           `xml:"PublishedDate"`
	StartTime                          *DateTimeType                           `xml:"StartTime"`
	EndTime                            *DateTimeType                           `xml:"EndTime"`
	HierarchyScope                     *HierarchyScopeType                     `xml:"HierarchyScope"`
	WorkType                           *OperationsTypeType                     `xml:"WorkType"`
	JobOrderID                         *IdentifierType                         `xml:"JobOrderID"`
	WorkDirective                      *WorkDirectiveType                      `xml:"WorkDirective"`
	WorkDirectiveVersion               *IdentifierType                         `xml:"WorkDirectiveVersion"`
	WorkMasterID                       *IdentifierType                         `xml:"WorkMasterID"`
	WorkMasterVersion                  *IdentifierType                         `xml:"WorkMasterVersion"`
	WorkflowSpecificationID            *IdentifierType                         `xml:"WorkflowSpecificationID"`
	WorkflowSpecificationNodeID        *IdentifierType                         `xml:"WorkflowSpecificationNodeID"`
	JobState                           *ResponseStateType                      `xml:"JobState"`
	JobResponseData                    []*OpSegmentDataType                    `xml:"JobResponseData"`
	PersonnelActual                    []*OpPersonnelActualType                `xml:"PersonnelActual"`
	EquipmentActual                    []*OpEquipmentActualType                `xml:"EquipmentActual"`
	PhysicalAssetActual                []*OpPhysicalAssetActualType            `xml:"PhysicalAssetActual"`
	MaterialActual                     []*OpMaterialActualType                 `xml:"MaterialActual"`
	RequiredByRequestedSegmentResponse *RequiredByRequestedSegmentResponseType `xml:"RequiredByRequestedSegmentResponse"`
}

// JobResponseListType ...
type JobResponseListType struct {
	ExtendedJobResponseList []*JobResponseListType
	ID                      *IdentifierType     `xml:"ID"`
	Version                 *IdentifierType     `xml:"Version"`
	PublishedDate           *DateTimeType       `xml:"PublishedDate"`
	StartTime               *DateTimeType       `xml:"StartTime"`
	EndTime                 *DateTimeType       `xml:"EndTime"`
	Description             []*DescriptionType  `xml:"Description"`
	HierarchyScope          *HierarchyScopeType `xml:"HierarchyScope"`
	WorkType                *OperationsTypeType `xml:"WorkType"`
	JobState                *ResponseStateType  `xml:"JobState"`
	JobResponse             []*JobResponseType  `xml:"JobResponse"`
}

// DataArea ...
// type DataArea struct {
// 	Get             *TransGetType          `xml:"Get"`
// 	WorkPerformance []*WorkPerformanceType `xml:"WorkPerformance"`
// }

// GetWorkPerformanceType ...
type GetWorkPerformanceType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ShowWorkPerformanceType ...
type ShowWorkPerformanceType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ProcessWorkPerformanceType ...
type ProcessWorkPerformanceType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// AcknowledgeWorkPerformanceType ...
type AcknowledgeWorkPerformanceType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ChangeWorkPerformanceType ...
type ChangeWorkPerformanceType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// RespondWorkPerformanceType ...
type RespondWorkPerformanceType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// CancelWorkPerformanceType ...
type CancelWorkPerformanceType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// SyncWorkPerformanceType ...
type SyncWorkPerformanceType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// GetWorkResponseType ...
type GetWorkResponseType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ShowWorkResponseType ...
type ShowWorkResponseType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ProcessWorkResponseType ...
type ProcessWorkResponseType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// AcknowledgeWorkResponseType ...
type AcknowledgeWorkResponseType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ChangeWorkResponseType ...
type ChangeWorkResponseType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// RespondWorkResponseType ...
type RespondWorkResponseType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// CancelWorkResponseType ...
type CancelWorkResponseType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// SyncWorkResponseType ...
type SyncWorkResponseType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// GetJobResponseType ...
type GetJobResponseType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ShowJobResponseType ...
type ShowJobResponseType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ProcessJobResponseType ...
type ProcessJobResponseType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// AcknowledgeJobResponseType ...
type AcknowledgeJobResponseType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ChangeJobResponseType ...
type ChangeJobResponseType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// RespondJobResponseType ...
type RespondJobResponseType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// CancelJobResponseType ...
type CancelJobResponseType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// SyncJobResponseType ...
type SyncJobResponseType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// GetJobResponseListType ...
type GetJobResponseListType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ShowJobResponseListType ...
type ShowJobResponseListType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ProcessJobResponseListType ...
type ProcessJobResponseListType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// AcknowledgeJobResponseListType ...
type AcknowledgeJobResponseListType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ChangeJobResponseListType ...
type ChangeJobResponseListType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// RespondJobResponseListType ...
type RespondJobResponseListType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// CancelJobResponseListType ...
type CancelJobResponseListType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// SyncJobResponseListType ...
type SyncJobResponseListType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}
