// Code generated by xgen. DO NOT EDIT.

package b2mml

// EquipmentInformation is A collection of Role Based Equipment Class and Equipment instance definitions.
// type EquipmentInformation *EquipmentInformationType

// Equipment ...
// type Equipment *EquipmentType

// EquipmentClass is A representation of a grouping of equipment with similar characteristics for a definite purpose
// such as manufacturing operations definition, scheduling, capability and performance is an equipment class.
// Any piece of equipment may be a member of zero or more equipment classes. An equipment class may be
// defined as a specialization of zero or more equipment classes. An equipment class may be made up of
// zero or more equipment classes.
// type EquipmentClass *EquipmentClassType

// GetEquipmentInformation ...
type GetEquipmentInformation *GetEquipmentInformationType

// ShowEquipmentInformation ...
type ShowEquipmentInformation *ShowEquipmentInformationType

// ProcessEquipmentInformation ...
type ProcessEquipmentInformation *ProcessEquipmentInformationType

// AcknowledgeEquipmentInformation ...
type AcknowledgeEquipmentInformation *AcknowledgeEquipmentInformationType

// ChangeEquipmentInformation ...
type ChangeEquipmentInformation *ChangeEquipmentInformationType

// RespondEquipmentInformation ...
type RespondEquipmentInformation *RespondEquipmentInformationType

// CancelEquipmentInformation ...
type CancelEquipmentInformation *CancelEquipmentInformationType

// SyncEquipmentInformation ...
type SyncEquipmentInformation *SyncEquipmentInformationType

// GetEquipmentClass ...
type GetEquipmentClass *GetEquipmentClassType

// ShowEquipmentClass ...
type ShowEquipmentClass *ShowEquipmentClassType

// ProcessEquipmentClass ...
type ProcessEquipmentClass *ProcessEquipmentClassType

// AcknowledgeEquipmentClass ...
type AcknowledgeEquipmentClass *AcknowledgeEquipmentClassType

// ChangeEquipmentClass ...
type ChangeEquipmentClass *ChangeEquipmentClassType

// RespondEquipmentClass ...
type RespondEquipmentClass *RespondEquipmentClassType

// CancelEquipmentClass ...
type CancelEquipmentClass *CancelEquipmentClassType

// SyncEquipmentClass ...
type SyncEquipmentClass *SyncEquipmentClassType

// GetEquipment ...
type GetEquipment *GetEquipmentType

// ShowEquipment ...
type ShowEquipment *ShowEquipmentType

// ProcessEquipment ...
type ProcessEquipment *ProcessEquipmentType

// AcknowledgeEquipment ...
type AcknowledgeEquipment *AcknowledgeEquipmentType

// ChangeEquipment ...
type ChangeEquipment *ChangeEquipmentType

// RespondEquipment ...
type RespondEquipment *RespondEquipmentType

// CancelEquipment ...
type CancelEquipment *CancelEquipmentType

// SyncEquipment ...
type SyncEquipment *SyncEquipmentType

// EquipmentInformationType ...
type EquipmentInformationType struct {
	ExtendedEquipmentInformation []*EquipmentInformationType
	ID                           *IdentifierType          `xml:"ID"`
	Description                  []*DescriptionType       `xml:"Description"`
	HierarchyScope               *HierarchyScopeType      `xml:"HierarchyScope"`
	PublishedDate                *DateTimeType            `xml:"PublishedDate"`
	Equipment                    []*EquipmentType         `xml:"Equipment"`
	EquipmentClass               []*EquipmentClassType    `xml:"EquipmentClass"`
	TestSpecification            []*TestSpecificationType `xml:"TestSpecification"`
}

// EquipmentType ...
type EquipmentType struct {
	ExtendedEquipment     *EquipmentType
	ID                    *IdentifierType              `xml:"ID"`
	Version               *IdentifierType              `xml:"Version"`
	Description           []*DescriptionType           `xml:"Description"`
	PublishedDate         *DateTimeType                `xml:"PublishedDate"`
	EffectiveStartDate    *DateTimeType                `xml:"EffectiveStartDate"`
	EffectiveEndDate      *DateTimeType                `xml:"EffectiveEndDate"`
	HierarchyScope        *HierarchyScopeType          `xml:"HierarchyScope"`
	EquipmentLevel        *EquipmentLevelType          `xml:"EquipmentLevel"`
	SpatialDefinition     *SpatialDefinitionType       `xml:"SpatialDefinition"`
	EquipmentAssetMapping []*EquipmentAssetMappingType `xml:"EquipmentAssetMapping"`
	PhysicalAssetID       *IdentifierType              `xml:"PhysicalAssetID"`
	OperationalLocation   *ResourceLocationType        `xml:"OperationalLocation"`
	EquipmentProperty     []*EquipmentPropertyType     `xml:"EquipmentProperty"`
	EquipmentChild        []*EquipmentType             `xml:"EquipmentChild"`
	EquipmentClassID      []*IdentifierType            `xml:"EquipmentClassID"`
	TestSpecificationID   []*IdentifierType            `xml:"TestSpecificationID"`
}

// EquipmentPropertyType ...
type EquipmentPropertyType struct {
	ExtendedEquipmentProperty *EquipmentProperty
	ID                        *IdentifierType          `xml:"ID"`
	Description               []*DescriptionType       `xml:"Description"`
	Value                     []*ValueType             `xml:"Value"`
	EquipmentPropertyChild    []*EquipmentPropertyType `xml:"EquipmentPropertyChild"`
	EquipmentClassPropertyID  *IdentifierType          `xml:"EquipmentClassPropertyID"`
}

// EquipmentClassType ...
type EquipmentClassType struct {
	ExtendedEquipmentClass *EquipmentClassType
	ID                     *IdentifierType               `xml:"ID"`
	Version                *IdentifierType               `xml:"Version"`
	Description            []*DescriptionType            `xml:"Description"`
	PublishedDate          *DateTimeType                 `xml:"PublishedDate"`
	EffectiveStartDate     *DateTimeType                 `xml:"EffectiveStartDate"`
	EffectiveEndDate       *DateTimeType                 `xml:"EffectiveEndDate"`
	HierarchyScope         *HierarchyScopeType           `xml:"HierarchyScope"`
	EquipmentLevel         *EquipmentLevelType           `xml:"EquipmentLevel"`
	EquipmentClassProperty []*EquipmentClassPropertyType `xml:"EquipmentClassProperty"`
	EquipmentClassChild    []*EquipmentClassType         `xml:"EquipmentClassChild"`
	EquipmentClassBaseID   []*IdentifierType             `xml:"EquipmentClassBaseID"`
	EquipmentSourceID      []*IdentifierType             `xml:"EquipmentSourceID"`
	TestSpecificationID    []*IdentifierType             `xml:"TestSpecificationID"`
}

// EquipmentClassPropertyType ...
type EquipmentClassPropertyType struct {
	ExtendedEquipmentClassProperty *EquipmentClassProperty
	ID                             *IdentifierType               `xml:"ID"`
	Description                    []*DescriptionType            `xml:"Description"`
	PropertyType                   *ClassPropertyTypeType        `xml:"PropertyType"`
	Value                          []*ValueType                  `xml:"Value"`
	EquipmentClassPropertyChild    []*EquipmentClassPropertyType `xml:"EquipmentClassPropertyChild"`
}

// DataArea ...
// type DataArea struct {
// 	Get                  *TransGetType               `xml:"Get"`
// 	EquipmentInformation []*EquipmentInformationType `xml:"EquipmentInformation"`
// }

// GetEquipmentInformationType ...
type GetEquipmentInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ShowEquipmentInformationType ...
type ShowEquipmentInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ProcessEquipmentInformationType ...
type ProcessEquipmentInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// AcknowledgeEquipmentInformationType ...
type AcknowledgeEquipmentInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ChangeEquipmentInformationType ...
type ChangeEquipmentInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// RespondEquipmentInformationType ...
type RespondEquipmentInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// CancelEquipmentInformationType ...
type CancelEquipmentInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// SyncEquipmentInformationType ...
type SyncEquipmentInformationType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// GetEquipmentClassType ...
type GetEquipmentClassType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ShowEquipmentClassType ...
type ShowEquipmentClassType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ProcessEquipmentClassType ...
type ProcessEquipmentClassType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// AcknowledgeEquipmentClassType ...
type AcknowledgeEquipmentClassType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ChangeEquipmentClassType ...
type ChangeEquipmentClassType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// RespondEquipmentClassType ...
type RespondEquipmentClassType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// CancelEquipmentClassType ...
type CancelEquipmentClassType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// SyncEquipmentClassType ...
type SyncEquipmentClassType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// GetEquipmentType ...
type GetEquipmentType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ShowEquipmentType ...
type ShowEquipmentType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ProcessEquipmentType ...
type ProcessEquipmentType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// AcknowledgeEquipmentType ...
type AcknowledgeEquipmentType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// ChangeEquipmentType ...
type ChangeEquipmentType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// RespondEquipmentType ...
type RespondEquipmentType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// CancelEquipmentType ...
type CancelEquipmentType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}

// SyncEquipmentType ...
type SyncEquipmentType struct {
	ReleaseIDAttr   string                    `xml:"releaseID,attr"`
	VersionIDAttr   *string                   `xml:"versionID,attr"`
	ApplicationArea *TransApplicationAreaType `xml:"ApplicationArea"`
	DataArea        *DataArea                 `xml:"DataArea"`
}
