// Code generated by xgen. DO NOT EDIT.

package b2mml

// ActualBatchSizeType ...
type ActualBatchSizeType struct {
}

// ActualProductProducedType ...
type ActualProductProducedType struct {
}

// ApprovalHistoryType ...
type ApprovalHistoryType struct {
	ExtendedApprovalHistory []*ApprovalHistoryType
	FinalApprovalDate       *DateTimeType             `xml:"FinalApprovalDate"`
	Version                 *IdentifierType           `xml:"Version"`
	Description             []*DescriptionType        `xml:"Description"`
	IndividualApproval      []*IndividualApprovalType `xml:"IndividualApproval"`
}

// ApprovedByType ...
type ApprovedByType struct {
}

// AuthorType ...
type AuthorType struct {
}

// BatchInformationType ...
type BatchInformationType struct {
	ExtendedBatchInformation []*BatchInformationType
	ListHeader               []*ListHeaderType           `xml:"ListHeader"`
	Description              []*DescriptionType          `xml:"Description"`
	MasterRecipe             []*MasterRecipeType         `xml:"MasterRecipe"`
	ControlRecipe            []*ControlRecipeType        `xml:"ControlRecipe"`
	RecipeBuildingBlock      []*RecipeBuildingBlockType  `xml:"RecipeBuildingBlock"`
	EquipmentElement         []*EquipmentElementTypeType `xml:"EquipmentElement"`
	BatchList                []*BatchListType            `xml:"BatchList"`
	EnumerationSet           []*EnumerationSetType       `xml:"EnumerationSet"`
}

// BatchListEntryType1Type ...
type BatchListEntryType1Type struct {
}

// BatchListEntryTypeType ...
type BatchListEntryTypeType struct {
	OtherValueAttr *string `xml:"OtherValue,attr"`
	*BatchListEntryType1Type
}

// BatchListEntryType ...
type BatchListEntryType struct {
	ExtendedBatchListEntry []*BatchListEntryTypeType
	ID                     *IdentifierType           `xml:"ID"`
	Description            []*DescriptionType        `xml:"Description"`
	BatchListEntryType     *BatchListEntryTypeType   `xml:"BatchListEntryType"`
	Status                 *BatchStatusType          `xml:"Status"`
	Mode                   *ModeType                 `xml:"Mode"`
	ExternalID             *IdentifierType           `xml:"ExternalID"`
	RecipeID               *IdentifierType           `xml:"RecipeID"`
	RecipeVersion          *IdentifierType           `xml:"RecipeVersion"`
	BatchID                *IdentifierType           `xml:"BatchID"`
	LotID                  *IdentifierType           `xml:"LotID"`
	CampaignID             *IdentifierType           `xml:"CampaignID"`
	ProductID              *IdentifierType           `xml:"ProductID"`
	OrderID                *IdentifierType           `xml:"OrderID"`
	StartCondition         *DateTimeType             `xml:"StartCondition"`
	RequestedStartTime     *DateTimeType             `xml:"RequestedStartTime"`
	ActualStartTime        *DateTimeType             `xml:"ActualStartTime"`
	RequestedEndTime       *DateTimeType             `xml:"RequestedEndTime"`
	ActualEndTime          *DateTimeType             `xml:"ActualEndTime"`
	BatchPriority          *BatchPriorityType        `xml:"BatchPriority"`
	RequestedBatchSize     *RequestedBatchSizeType   `xml:"RequestedBatchSize"`
	ActualBatchSize        *ActualBatchSizeType      `xml:"ActualBatchSize"`
	UnitOfMeasure          *UnitOfMeasureType        `xml:"UnitOfMeasure"`
	Note                   []*NoteType               `xml:"Note"`
	Parameter              []*BatchParameterType     `xml:"Parameter"`
	EquipmentID            []*IdentifierType         `xml:"EquipmentID"`
	EquipmentClassID       []*IdentifierType         `xml:"EquipmentClassID"`
	ActualEquipmentID      []*IdentifierType         `xml:"ActualEquipmentID"`
	BatchListEntry         []*BatchListEntryTypeType `xml:"BatchListEntry"`
}

// BatchListType ...
type BatchListType struct {
	ExtendedBatchList []*BatchListType
	ListHeader        *ListHeaderType           `xml:"ListHeader"`
	Description       []*DescriptionType        `xml:"Description"`
	BatchListEntry    []*BatchListEntryTypeType `xml:"BatchListEntry"`
}

// BatchPriorityType ...
type BatchPriorityType struct {
}

// BatchSizeType ...
type BatchSizeType struct {
	ExtendedBatchSize []*BatchSizeType
	Nominal           *NominalType        `xml:"Nominal"`
	Min               *MinType            `xml:"Min"`
	Max               *MaxType            `xml:"Max"`
	ScaleReference    *ScaleReferenceType `xml:"ScaleReference"`
	ScaledSize        *ScaledSizeType     `xml:"ScaledSize"`
	UnitOfMeasure     *UnitOfMeasureType  `xml:"UnitOfMeasure"`
}

// ClassInstanceAssociationType ...
type ClassInstanceAssociationType struct {
	ExtendedClassInstanceAssociation []*ClassInstanceAssociationType
	ClassEquipmentID                 *IdentifierType    `xml:"ClassEquipmentID"`
	MemberEquipmentID                *IdentifierType    `xml:"MemberEquipmentID"`
	Description                      []*DescriptionType `xml:"Description"`
}

// ConditionType ...
type ConditionType struct {
}

// ConditionAnnotationType ...
type ConditionAnnotationType struct {
}

// ConnectionType1Type ...
type ConnectionType1Type struct {
}

// ConnectionTypeType ...
type ConnectionTypeType struct {
	OtherValueAttr *string `xml:"OtherValue,attr"`
	*ConnectionType1Type
}

// ConstraintType ...
type ConstraintType struct {
	ExtendedConstraint []*ConstraintType
	ID                 *IdentifierType `xml:"ID"`
	Condition          *ConditionType  `xml:"Condition"`
}

// ControlRecipeType ...
type ControlRecipeType struct {
	ExtendedControlRecipe []*ControlRecipeType
	ID                    *IdentifierType                  `xml:"ID"`
	Version               *IdentifierType                  `xml:"Version"`
	VersionDate           *DateTimeType                    `xml:"VersionDate"`
	Description           []*DescriptionType               `xml:"Description"`
	BatchID               *IdentifierType                  `xml:"BatchID"`
	Header                *HeaderType                      `xml:"Header"`
	EquipmentRequirement  []*BatchEquipmentRequirementType `xml:"EquipmentRequirement"`
	Formula               *FormulaType                     `xml:"Formula"`
	ProcedureLogic        *ProcedureLogicType              `xml:"ProcedureLogic"`
	RecipeElement         []*RecipeElementTypeType         `xml:"RecipeElement"`
	OtherInformation      []*OtherInformationType          `xml:"OtherInformation"`
}

// DataInterpretation1Type ...
type DataInterpretation1Type struct {
}

// DataInterpretationType ...
type DataInterpretationType struct {
	OtherValueAttr *string `xml:"OtherValue,attr"`
	*DataInterpretation1Type
}

// DefaultValueType ...
type DefaultValueType struct {
}

// Depiction1Type ...
type Depiction1Type struct {
}

// DepictionType ...
type DepictionType struct {
	OtherValueAttr *string `xml:"OtherValue,attr"`
	*Depiction1Type
}

// EnumerationNumberType ...
type EnumerationNumberType struct {
}

// EnumerationSetType ...
type EnumerationSetType struct {
	ExtendedEnumerationSet []*EnumerationSetType
	ID                     *IdentifierType    `xml:"ID"`
	Description            []*DescriptionType `xml:"Description"`
	Enumeration            []*EnumerationType `xml:"Enumeration"`
}

// EnumerationStringType ...
type EnumerationStringType struct {
}

// EnumerationType ...
type EnumerationType struct {
	ExtendedEnumeration []*EnumerationType
	EnumerationNumber   *EnumerationNumberType `xml:"EnumerationNumber"`
	EnumerationString   *EnumerationStringType `xml:"EnumerationString"`
	Description         []*DescriptionType     `xml:"Description"`
}

// EquipmentConnectionType ...
type EquipmentConnectionType struct {
	ExtendedEquipmentConnection []*EquipmentConnectionType
	ID                          *IdentifierType     `xml:"ID"`
	Description                 []*DescriptionType  `xml:"Description"`
	ConnectionType              *ConnectionTypeType `xml:"ConnectionType"`
	FromEquipmentID             []*IdentifierType   `xml:"FromEquipmentID"`
	ToEquipmentID               []*IdentifierType   `xml:"ToEquipmentID"`
}

// EquipmentElementType ...
type EquipmentElementType struct {
	ExtendedEquipmentElement        []*EquipmentElementTypeType
	ID                              *IdentifierType                        `xml:"ID"`
	Description                     []*DescriptionType                     `xml:"Description"`
	EquipmentElementType            *EquipmentElementTypeType              `xml:"EquipmentElementType"`
	EquipmentElementLevel           *EquipmentLevelType                    `xml:"EquipmentElementLevel"`
	ClassInstanceAssociation        []*ClassInstanceAssociationType        `xml:"ClassInstanceAssociation"`
	Property                        []*EquipmentElementPropertyType        `xml:"Property"`
	EquipmentProceduralElementClass []*EquipmentProceduralElementClassType `xml:"EquipmentProceduralElementClass"`
	EquipmentProceduralElement      []*EquipmentProceduralElementTypeType  `xml:"EquipmentProceduralElement"`
	EquipmentConnection             []*EquipmentConnectionType             `xml:"EquipmentConnection"`
	EquipmentElement                []*EquipmentElementTypeType            `xml:"EquipmentElement"`
	EquipmentElementID              []*IdentifierType                      `xml:"EquipmentElementID"`
}

// EquipmentElementType1Type ...
type EquipmentElementType1Type struct {
}

// EquipmentElementTypeType ...
type EquipmentElementTypeType struct {
	OtherValueAttr *string `xml:"OtherValue,attr"`
	*EquipmentElementType1Type
}

// BatchEquipmentIDType ...
type BatchEquipmentIDType struct {
	ExtendedBatchEquipmentID []*BatchEquipmentID
	Property                 *EquipmentElementPropertyType `xml:"Property"`
	Condition                *ConditionType                `xml:"Condition"`
	Value                    *BatchValueType               `xml:"Value"`
}

// EquipmentProceduralElementClassType ...
type EquipmentProceduralElementClassType struct {
	ExtendedEquipmentProceduralElementClass []*EquipmentProceduralElementClassType
	ID                                      *IdentifierType                     `xml:"ID"`
	Description                             []*DescriptionType                  `xml:"Description"`
	EquipmentProceduralElementType          *EquipmentProceduralElementTypeType `xml:"EquipmentProceduralElementType"`
	Parameter                               []*BatchParameterType               `xml:"Parameter"`
}

// EquipmentProceduralElementType ...
type EquipmentProceduralElementType struct {
	ExtendedEquipmentProceduralElement []*EquipmentProceduralElementTypeType
	ID                                 *IdentifierType                     `xml:"ID"`
	Description                        []*DescriptionType                  `xml:"Description"`
	EquipmentProceduralElementType     *EquipmentProceduralElementTypeType `xml:"EquipmentProceduralElementType"`
	EquipmentProceduralElementClassID  *IdentifierType                     `xml:"EquipmentProceduralElementClassID"`
	Parameter                          []*BatchParameterType               `xml:"Parameter"`
}

// EquipmentProceduralElementType1Type ...
type EquipmentProceduralElementType1Type struct {
}

// EquipmentProceduralElementTypeType ...
type EquipmentProceduralElementTypeType struct {
	OtherValueAttr *string `xml:"OtherValue,attr"`
	*EquipmentProceduralElementType1Type
}

// BatchEquipmentRequirementType ...
type BatchEquipmentRequirementType struct {
	ExtendedBatchEquipmentRequirement []*BatchEquipmentRequirement
	ID                                *IdentifierType   `xml:"ID"`
	Constraint                        []*ConstraintType `xml:"Constraint"`
	Description                       *DescriptionType  `xml:"Description"`
}

// EvaluationOrderType ...
type EvaluationOrderType struct {
}

// FormulaType ...
type FormulaType struct {
	ExtendedFormula []*FormulaType
	Parameter       []*BatchParameterType `xml:"Parameter"`
}

// FromIDType ...
type FromIDType struct {
	ExtendedFromID []*FromIDType
	FromIDValue    string        `xml:"FromIDValue"`
	FromType       *FromTypeType `xml:"FromType"`
	IDScope        *IDScopeType  `xml:"IDScope"`
}

// FromType1Type ...
type FromType1Type struct {
}

// FromTypeType ...
type FromTypeType struct {
	OtherValueAttr *string `xml:"OtherValue,attr"`
	*FromType1Type
}

// HeaderType ...
type HeaderType struct {
	ExtendedHeader        []*HeaderType
	ModificationLog       []*ModificationLogType       `xml:"ModificationLog"`
	ApprovalHistory       []*ApprovalHistoryType       `xml:"ApprovalHistory"`
	EffectiveDate         *DateTimeType                `xml:"EffectiveDate"`
	ExpirationDate        *DateTimeType                `xml:"ExpirationDate"`
	ProductID             *IdentifierType              `xml:"ProductID"`
	ProductName           *IdentifierType              `xml:"ProductName"`
	BatchSize             *BatchSizeType               `xml:"BatchSize"`
	ActualProductProduced []*ActualProductProducedType `xml:"ActualProductProduced"`
	Status                *BatchStatusType             `xml:"Status"`
}

// IDScope1Type ...
type IDScope1Type struct {
}

// IDScopeType ...
type IDScopeType struct {
	OtherValueAttr *string `xml:"OtherValue,attr"`
	*IDScope1Type
}

// IndividualApprovalType ...
type IndividualApprovalType struct {
	ExtendedIndividualApproval []*IndividualApprovalType
	ApprovedBy                 *ApprovedByType    `xml:"ApprovedBy"`
	ApprovalDate               *DateTimeType      `xml:"ApprovalDate"`
	Description                []*DescriptionType `xml:"Description"`
}

// LinkType ...
type LinkType struct {
	ExtendedLink    []*LinkTypeType
	ID              *IdentifierType      `xml:"ID"`
	FromID          []*FromIDType        `xml:"FromID"`
	ToID            []*ToIDType          `xml:"ToID"`
	LinkType        *LinkTypeType        `xml:"LinkType"`
	Depiction       *DepictionType       `xml:"Depiction"`
	EvaluationOrder *EvaluationOrderType `xml:"EvaluationOrder"`
	Description     []*DescriptionType   `xml:"Description"`
}

// LinkType1Type ...
type LinkType1Type struct {
}

// LinkTypeType ...
type LinkTypeType struct {
	OtherValueAttr *string `xml:"OtherValue,attr"`
	*LinkType1Type
}

// ListHeaderType ...
type ListHeaderType struct {
	ExtendedListHeader []*ListHeaderType
	ID                 *IdentifierType        `xml:"ID"`
	Version            *IdentifierType        `xml:"Version"`
	Description        []*DescriptionType     `xml:"Description"`
	Origin             *OriginType            `xml:"Origin"`
	CreateDate         *DateTimeType          `xml:"CreateDate"`
	ModificationLog    []*ModificationLogType `xml:"ModificationLog"`
}

// MasterRecipeType ...
type MasterRecipeType struct {
	ExtendedMasterRecipe []*MasterRecipeType
	ID                   *IdentifierType                  `xml:"ID"`
	Version              *IdentifierType                  `xml:"Version"`
	VersionDate          *DateTimeType                    `xml:"VersionDate"`
	Description          []*DescriptionType               `xml:"Description"`
	Header               *HeaderType                      `xml:"Header"`
	EquipmentRequirement []*BatchEquipmentRequirementType `xml:"EquipmentRequirement"`
	Formula              *FormulaType                     `xml:"Formula"`
	ProcedureLogic       *ProcedureLogicType              `xml:"ProcedureLogic"`
	RecipeElement        []*RecipeElementTypeType         `xml:"RecipeElement"`
	OtherInformation     []*OtherInformationType          `xml:"OtherInformation"`
}

// MaxType ...
type MaxType struct {
}

// MinType ...
type MinType struct {
}

// Mode1Type ...
type Mode1Type struct {
}

// ModeType ...
type ModeType struct {
	OtherValueAttr *string `xml:"OtherValue,attr"`
	*Mode1Type
}

// ModificationLogType ...
type ModificationLogType struct {
	ExtendedModificationLog []*ModificationLogType
	ModifiedDate            *DateTimeType      `xml:"ModifiedDate"`
	Description             []*DescriptionType `xml:"Description"`
	Author                  *AuthorType        `xml:"Author"`
}

// NominalType ...
type NominalType struct {
}

// NoteType ...
type NoteType struct {
}

// OriginType ...
type OriginType struct {
}

// OtherInformationType ...
type OtherInformationType struct {
	ExtendedOtherInformation []*OtherInformationType
	ID                       *IdentifierType    `xml:"ID"`
	Value                    []*BatchValueType  `xml:"Value"`
	Description              []*DescriptionType `xml:"Description"`
}

// ParameterSubTypeType ...
type ParameterSubTypeType struct {
}

// BatchParameterType ...
type BatchParameterType struct {
	ExtendedBatchParameter []*BatchParameter
	ID                     *IdentifierType         `xml:"ID"`
	Description            *DescriptionType        `xml:"Description"`
	ParameterType          *ParameterTypeType      `xml:"ParameterType"`
	ParameterSubType       []*ParameterSubTypeType `xml:"ParameterSubType"`
	Value                  []*BatchValueType       `xml:"Value"`
	Scaled                 *ScaledType             `xml:"Scaled"`
	ScaleReference         *ScaleReferenceType     `xml:"ScaleReference"`
	Parameter              []*BatchParameterType   `xml:"Parameter"`
}

// ParameterType1Type ...
type ParameterType1Type struct {
}

// ParameterTypeType ...
type ParameterTypeType struct {
	OtherValueAttr *string `xml:"OtherValue,attr"`
	*ParameterType1Type
}

// ProcedureLogicType ...
type ProcedureLogicType struct {
	ExtendedProcedureLogic []*ProcedureLogicType
	Link                   []*LinkTypeType   `xml:"Link"`
	Step                   []*StepType       `xml:"Step"`
	Transition             []*TransitionType `xml:"Transition"`
}

// EquipmentElementPropertyType ...
type EquipmentElementPropertyType struct {
	ExtendedProperty []*EquipmentElementPropertyType
	ID               *IdentifierType                 `xml:"ID"`
	Description      []*DescriptionType              `xml:"Description"`
	Value            *BatchValueType                 `xml:"Value"`
	Property         []*EquipmentElementPropertyType `xml:"Property"`
}

// RecipeBuildingBlockType ...
type RecipeBuildingBlockType struct {
	ExtendedRecipeBuildingBlock []*RecipeBuildingBlockType
	Description                 []*DescriptionType       `xml:"Description"`
	RecipeElement               []*RecipeElementTypeType `xml:"RecipeElement"`
}

// RecipeElementType ...
type RecipeElementType struct {
	ExtendedRecipeElement       []*RecipeElementTypeType
	ID                          *IdentifierType                  `xml:"ID"`
	Version                     *IdentifierType                  `xml:"Version"`
	VersionDate                 *DateTimeType                    `xml:"VersionDate"`
	Description                 []*DescriptionType               `xml:"Description"`
	RecipeElementType           *RecipeElementTypeType           `xml:"RecipeElementType"`
	BuildingBlockElementID      *IdentifierType                  `xml:"BuildingBlockElementID"`
	BuildingBlockElementVersion *IdentifierType                  `xml:"BuildingBlockElementVersion"`
	ActualEquipmentID           []*IdentifierType                `xml:"ActualEquipmentID"`
	Header                      *HeaderType                      `xml:"Header"`
	EquipmentRequirement        []*BatchEquipmentRequirementType `xml:"EquipmentRequirement"`
	Parameter                   []*BatchParameterType            `xml:"Parameter"`
	ProcedureLogic              *ProcedureLogicType              `xml:"ProcedureLogic"`
	RecipeElement               []*RecipeElementTypeType         `xml:"RecipeElement"`
	OtherInformation            []*OtherInformationType          `xml:"OtherInformation"`
}

// RecipeElementType1Type ...
type RecipeElementType1Type struct {
}

// RecipeElementTypeType ...
type RecipeElementTypeType struct {
	OtherValueAttr *string `xml:"OtherValue,attr"`
	*RecipeElementType1Type
}

// RecipeElementVersionType ...
type RecipeElementVersionType struct {
}

// RequestedBatchSizeType ...
type RequestedBatchSizeType struct {
}

// ScaledSizeType ...
type ScaledSizeType struct {
}

// ScaledType ...
type ScaledType struct {
}

// ScaleReferenceType ...
type ScaleReferenceType struct {
}

// ScheduleEntryNoteType ...
type ScheduleEntryNoteType struct {
}

// BatchStatus1Type ...
type BatchStatus1Type struct {
}

// BatchStatusType ...
type BatchStatusType struct {
	OtherValueAttr *string `xml:"OtherValue,attr"`
	*BatchStatus1Type
}

// StepType ...
type StepType struct {
	ExtendedStep         []*StepType
	ID                   *IdentifierType    `xml:"ID"`
	RecipeElementID      *IdentifierType    `xml:"RecipeElementID"`
	RecipeElementVersion *IdentifierType    `xml:"RecipeElementVersion"`
	Description          []*DescriptionType `xml:"Description"`
}

// ToIDType ...
type ToIDType struct {
	ExtendedToID []*ToIDType
	ToIDValue    string       `xml:"ToIDValue"`
	ToType       *ToTypeType  `xml:"ToType"`
	IDScope      *IDScopeType `xml:"IDScope"`
}

// ToType1Type ...
type ToType1Type struct {
}

// ToTypeType ...
type ToTypeType struct {
	OtherValueAttr *string `xml:"OtherValue,attr"`
	*ToType1Type
}

// TransitionType ...
type TransitionType struct {
	ExtendedTransition  []*TransitionType
	ID                  *IdentifierType          `xml:"ID"`
	Condition           *ConditionType           `xml:"Condition"`
	ConditionAnnotation *ConditionAnnotationType `xml:"ConditionAnnotation"`
	Description         []*DescriptionType       `xml:"Description"`
}

// BatchValueType ...
type BatchValueType struct {
	ExtendedBatchValue []*BatchValue
	ValueString        []*ValueStringType      `xml:"ValueString"`
	DataInterpretation *DataInterpretationType `xml:"DataInterpretation"`
	DataType           *DataTypeType           `xml:"DataType"`
	UnitOfMeasure      *UnitOfMeasureType      `xml:"UnitOfMeasure"`
	EnumerationSetID   []*IdentifierType       `xml:"EnumerationSetID"`
}

// BatchInformation ...
// type BatchInformation *BatchInformationType

// MasterRecipe ...
// type MasterRecipe *MasterRecipeType

// ControlRecipe ...
// type ControlRecipe *ControlRecipeType

// RecipeBuildingBlock ...
// type RecipeBuildingBlock *RecipeBuildingBlockType

// EquipmentElement ...
// type EquipmentElement *EquipmentElementTypeType

// BatchList ...
// type BatchList *BatchListType

// ActualBatchSize ...
type ActualBatchSize *ActualBatchSizeType

// ActualEquipmentID ...
type ActualEquipmentID *IdentifierType

// ActualEndTime ...
type ActualEndTime *DateTimeType

// ActualStartTime ...
type ActualStartTime *DateTimeType

// ApprovedBy ...
type ApprovedBy *ApprovedByType

// ApprovalDate ...
type ApprovalDate *DateTimeType

// ApprovalHistory ...
// type ApprovalHistory *ApprovalHistoryType

// Author ...
type Author *AuthorType

// BatchID ...
type BatchID *IdentifierType

// BatchListEntry ...
// type BatchListEntry *BatchListEntryTypeType

// BatchPriority ...
type BatchPriority *BatchPriorityType

// BatchSize ...
// type BatchSize *BatchSizeType

// BuildingBlockElementID ...
type BuildingBlockElementID *IdentifierType

// BuildingBlockElementVersion ...
type BuildingBlockElementVersion *IdentifierType

// CampaignID ...
type CampaignID *IdentifierType

// ClassEquipmentID ...
type ClassEquipmentID *IdentifierType

// ClassInstanceAssociation ...
// type ClassInstanceAssociation *ClassInstanceAssociationType

// Condition ...
type Condition *ConditionType

// ConditionAnnotation ...
type ConditionAnnotation *ConditionAnnotationType

// ConnectionType ...
type ConnectionType *ConnectionTypeType

// Constraint ...
// type Constraint *ConstraintType

// CreateDate ...
type CreateDate *DateTimeType

// DataInterpretation ...
type DataInterpretation *DataInterpretationType

// DataType ...
type DataType *DataTypeType

// DefaultValue ...
type DefaultValue *DefaultValueType

// Depiction ...
type Depiction *DepictionType

// Description ...
type Description *DescriptionType

// EffectiveDate ...
type EffectiveDate *DateTimeType

// Enumeration ...
// type Enumeration *EnumerationType

// EnumerationNumber ...
type EnumerationNumber *EnumerationNumberType

// EnumerationSet ...
// type EnumerationSet *EnumerationSetType

// EnumerationSetID ...
type EnumerationSetID *IdentifierType

// EnumerationString ...
type EnumerationString *EnumerationStringType

// EquipmentClassID ...
type EquipmentClassID *IdentifierType

// EquipmentConnection ...
// type EquipmentConnection *EquipmentConnectionType

// EquipmentElementID ...
type EquipmentElementID *IdentifierType

// EquipmentElementLevel ...
type EquipmentElementLevel *EquipmentLevelType

// EquipmentID ...
type EquipmentID *BatchEquipmentIDType

// EquipmentProceduralElement ...
// type EquipmentProceduralElement *EquipmentProceduralElementTypeType

// EquipmentProceduralElementClass ...
// type EquipmentProceduralElementClass *EquipmentProceduralElementClassType

// EquipmentProceduralElementClassID ...
type EquipmentProceduralElementClassID *IdentifierType

// EquipmentRequirement ...
// type EquipmentRequirement *BatchEquipmentRequirementType

// EvaluationOrder ...
type EvaluationOrder *EvaluationOrderType

// ExpirationDate ...
type ExpirationDate *DateTimeType

// ExternalID ...
type ExternalID *IdentifierType

// FinalApprovalDate ...
type FinalApprovalDate *DateTimeType

// Formula ...
// type Formula *FormulaType

// FromEquipmentID ...
// type FromEquipmentID *IdentifierType

// FromID ...
// type FromID *FromIDType

// Header ...
// type Header *HeaderType

// ID ...
type ID *IdentifierType

// IndividualApproval ...
// type IndividualApproval *IndividualApprovalType

// Link ...
// type Link *LinkTypeType

// ListHeader ...
// type ListHeader *ListHeaderType

// LotID ...
type LotID *IdentifierType

// Max ...
type Max *MaxType

// MemberEquipmentID ...
type MemberEquipmentID *IdentifierType

// Min ...
type Min *MinType

// Mode ...
type Mode *ModeType

// ModificationLog ...
// type ModificationLog *ModificationLogType

// ModifiedDate ...
type ModifiedDate *DateTimeType

// Nominal ...
type Nominal *NominalType

// Note ...
type Note *NoteType

// OrderID ...
type OrderID *IdentifierType

// Origin ...
type Origin *OriginType

// OtherInformation ...
// type OtherInformation *OtherInformationType

// Parameter ...
// type Parameter *BatchParameterType

// ParameterSubType ...
type ParameterSubType *ParameterSubTypeType

// ParameterType ...
// type ParameterType *ParameterTypeType

// ProcedureLogic ...
// type ProcedureLogic *ProcedureLogicType

// ProductID ...
type ProductID *IdentifierType

// ProductName ...
type ProductName *IdentifierType

// Property ...
// type Property *EquipmentElementPropertyType

// RecipeElement ...
// type RecipeElement *RecipeElementTypeType

// RecipeElementID ...
type RecipeElementID *IdentifierType

// RecipeElementVersion ...
type RecipeElementVersion *IdentifierType

// RecipeID ...
type RecipeID *IdentifierType

// RecipeVersion ...
type RecipeVersion *IdentifierType

// RequestedBatchSize ...
type RequestedBatchSize *RequestedBatchSizeType

// RequestedEndTime ...
type RequestedEndTime *DateTimeType

// RequestedStartTime ...
type RequestedStartTime *DateTimeType

// ScaleReference ...
type ScaleReference *ScaleReferenceType

// Scaled ...
type Scaled *ScaledType

// ScaledSize ...
type ScaledSize *ScaledSizeType

// Status ...
type Status *StatusType

// ScheduleEndTime ...
type ScheduleEndTime *DateTimeType

// ScheduleEntryNote ...
type ScheduleEntryNote *ScheduleEntryNoteType

// ScheduleStartTime ...
type ScheduleStartTime *DateTimeType

// StartCondition ...
type StartCondition *DateTimeType

// Step ...
// type Step *StepType

// ToEquipmentID ...
type ToEquipmentID *IdentifierType

// ToID ...
// type ToID *ToIDType

// Transition ...
// type Transition *TransitionType

// UnitOfMeasure ...
type UnitOfMeasure *UnitOfMeasureType

// Value ...
// type Value *BatchValueType

// ValueString ...
type ValueString *ValueStringType

// Version ...
type Version *IdentifierType

// VersionDate ...
type VersionDate *DateTimeType
