// Code generated by xgen. DO NOT EDIT.

package b2mml

// DirectedLink ...
type DirectedLink struct {
}

// ResourceConstraint ...
type ResourceConstraint struct {
}

// ResourceConstraintLibrary ...
type ResourceConstraintLibrary struct {
}

// ResourceConstraintProperty ...
type ResourceConstraintProperty struct {
}

// GRecipeFormula ...
type GRecipeFormula struct {
}

// GRecipeHeader ...
type GRecipeHeader struct {
}

// HeaderProperty ...
type HeaderProperty struct {
}

// GRecipeMaterial ...
type GRecipeMaterial struct {
}

// GRecipeMaterials ...
type GRecipeMaterials struct {
}

// GROtherInformation ...
type GROtherInformation struct {
}

// ProcessElementParameter ...
type ProcessElementParameter struct {
}

// ProcessElement ...
type ProcessElement struct {
}

// ProcessElementLibrary ...
type ProcessElementLibrary struct {
}

// ProcedureChartElement ...
type ProcedureChartElement struct {
}

// GRecipe ...
type GRecipe struct {
}

// GRecipeInformation ...
type GRecipeInformation struct {
}
