// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: equipment.sql

package postgres

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const addEquipmentToClass = `-- name: AddEquipmentToClass :one

INSERT INTO equipment_class_mappings (
    equipment_id,
    equipment_class_id
) VALUES ($1, $2)
RETURNING
    id,
    equipment_id,
    equipment_class_id,
    created_at
`

type AddEquipmentToClassParams struct {
	EquipmentID      uuid.UUID `db:"equipment_id" json:"equipment_id"`
	EquipmentClassID uuid.UUID `db:"equipment_class_id" json:"equipment_class_id"`
}

// Equipment Class Mappings queries
func (q *Queries) AddEquipmentToClass(ctx context.Context, arg *AddEquipmentToClassParams) (*EquipmentClassMapping, error) {
	row := q.db.QueryRowContext(ctx, addEquipmentToClass, arg.EquipmentID, arg.EquipmentClassID)
	var i EquipmentClassMapping
	err := row.Scan(
		&i.ID,
		&i.EquipmentID,
		&i.EquipmentClassID,
		&i.CreatedAt,
	)
	return &i, err
}

const createEquipment = `-- name: CreateEquipment :one

INSERT INTO equipment (
    external_id,
    version,
    description,
    published_date,
    effective_start_date,
    effective_end_date,
    hierarchy_scope_id,
    equipment_level,
    operating_status,
    physical_asset_id,
    operational_location_id,
    parent_equipment_id,
    b2mml_data
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
RETURNING
    id,
    external_id,
    version,
    description,
    published_date,
    effective_start_date,
    effective_end_date,
    hierarchy_scope_id,
    equipment_level,
    operating_status,
    physical_asset_id,
    operational_location_id,
    parent_equipment_id,
    b2mml_data,
    created_at,
    updated_at,
    deleted_at,
    record_version
`

type CreateEquipmentParams struct {
	ExternalID            string                `db:"external_id" json:"external_id"`
	Version               sql.NullString        `db:"version" json:"version"`
	Description           sql.NullString        `db:"description" json:"description"`
	PublishedDate         sql.NullTime          `db:"published_date" json:"published_date"`
	EffectiveStartDate    sql.NullTime          `db:"effective_start_date" json:"effective_start_date"`
	EffectiveEndDate      sql.NullTime          `db:"effective_end_date" json:"effective_end_date"`
	HierarchyScopeID      sql.NullString        `db:"hierarchy_scope_id" json:"hierarchy_scope_id"`
	EquipmentLevel        sql.NullString        `db:"equipment_level" json:"equipment_level"`
	OperatingStatus       sql.NullString        `db:"operating_status" json:"operating_status"`
	PhysicalAssetID       sql.NullString        `db:"physical_asset_id" json:"physical_asset_id"`
	OperationalLocationID sql.NullString        `db:"operational_location_id" json:"operational_location_id"`
	ParentEquipmentID     uuid.NullUUID         `db:"parent_equipment_id" json:"parent_equipment_id"`
	B2mmlData             pqtype.NullRawMessage `db:"b2mml_data" json:"b2mml_data"`
}

// Equipment queries
func (q *Queries) CreateEquipment(ctx context.Context, arg *CreateEquipmentParams) (*Equipment, error) {
	row := q.db.QueryRowContext(ctx, createEquipment,
		arg.ExternalID,
		arg.Version,
		arg.Description,
		arg.PublishedDate,
		arg.EffectiveStartDate,
		arg.EffectiveEndDate,
		arg.HierarchyScopeID,
		arg.EquipmentLevel,
		arg.OperatingStatus,
		arg.PhysicalAssetID,
		arg.OperationalLocationID,
		arg.ParentEquipmentID,
		arg.B2mmlData,
	)
	var i Equipment
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Version,
		&i.Description,
		&i.PublishedDate,
		&i.EffectiveStartDate,
		&i.EffectiveEndDate,
		&i.HierarchyScopeID,
		&i.EquipmentLevel,
		&i.OperatingStatus,
		&i.PhysicalAssetID,
		&i.OperationalLocationID,
		&i.ParentEquipmentID,
		&i.B2mmlData,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RecordVersion,
	)
	return &i, err
}

const createEquipmentClass = `-- name: CreateEquipmentClass :one

INSERT INTO equipment_classes (
    external_id,
    version,
    description,
    published_date,
    effective_start_date,
    effective_end_date,
    hierarchy_scope_id,
    equipment_level,
    parent_class_id,
    b2mml_data
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING
    id,
    external_id,
    version,
    description,
    published_date,
    effective_start_date,
    effective_end_date,
    hierarchy_scope_id,
    equipment_level,
    parent_class_id,
    b2mml_data,
    created_at,
    updated_at,
    deleted_at
`

type CreateEquipmentClassParams struct {
	ExternalID         string                `db:"external_id" json:"external_id"`
	Version            sql.NullString        `db:"version" json:"version"`
	Description        sql.NullString        `db:"description" json:"description"`
	PublishedDate      sql.NullTime          `db:"published_date" json:"published_date"`
	EffectiveStartDate sql.NullTime          `db:"effective_start_date" json:"effective_start_date"`
	EffectiveEndDate   sql.NullTime          `db:"effective_end_date" json:"effective_end_date"`
	HierarchyScopeID   sql.NullString        `db:"hierarchy_scope_id" json:"hierarchy_scope_id"`
	EquipmentLevel     sql.NullString        `db:"equipment_level" json:"equipment_level"`
	ParentClassID      uuid.NullUUID         `db:"parent_class_id" json:"parent_class_id"`
	B2mmlData          pqtype.NullRawMessage `db:"b2mml_data" json:"b2mml_data"`
}

// Equipment Classes queries
func (q *Queries) CreateEquipmentClass(ctx context.Context, arg *CreateEquipmentClassParams) (*EquipmentClass, error) {
	row := q.db.QueryRowContext(ctx, createEquipmentClass,
		arg.ExternalID,
		arg.Version,
		arg.Description,
		arg.PublishedDate,
		arg.EffectiveStartDate,
		arg.EffectiveEndDate,
		arg.HierarchyScopeID,
		arg.EquipmentLevel,
		arg.ParentClassID,
		arg.B2mmlData,
	)
	var i EquipmentClass
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Version,
		&i.Description,
		&i.PublishedDate,
		&i.EffectiveStartDate,
		&i.EffectiveEndDate,
		&i.HierarchyScopeID,
		&i.EquipmentLevel,
		&i.ParentClassID,
		&i.B2mmlData,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const createEquipmentClassProperty = `-- name: CreateEquipmentClassProperty :one

INSERT INTO equipment_class_properties (
    equipment_class_id,
    external_id,
    description,
    property_type,
    parent_property_id,
    b2mml_data
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING
    id,
    equipment_class_id,
    external_id,
    description,
    property_type,
    parent_property_id,
    b2mml_data,
    created_at,
    updated_at
`

type CreateEquipmentClassPropertyParams struct {
	EquipmentClassID uuid.UUID             `db:"equipment_class_id" json:"equipment_class_id"`
	ExternalID       string                `db:"external_id" json:"external_id"`
	Description      sql.NullString        `db:"description" json:"description"`
	PropertyType     sql.NullString        `db:"property_type" json:"property_type"`
	ParentPropertyID uuid.NullUUID         `db:"parent_property_id" json:"parent_property_id"`
	B2mmlData        pqtype.NullRawMessage `db:"b2mml_data" json:"b2mml_data"`
}

// Equipment Class Properties queries
func (q *Queries) CreateEquipmentClassProperty(ctx context.Context, arg *CreateEquipmentClassPropertyParams) (*EquipmentClassProperty, error) {
	row := q.db.QueryRowContext(ctx, createEquipmentClassProperty,
		arg.EquipmentClassID,
		arg.ExternalID,
		arg.Description,
		arg.PropertyType,
		arg.ParentPropertyID,
		arg.B2mmlData,
	)
	var i EquipmentClassProperty
	err := row.Scan(
		&i.ID,
		&i.EquipmentClassID,
		&i.ExternalID,
		&i.Description,
		&i.PropertyType,
		&i.ParentPropertyID,
		&i.B2mmlData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const createEquipmentProperty = `-- name: CreateEquipmentProperty :one

INSERT INTO equipment_properties (
    equipment_id,
    external_id,
    class_property_id,
    property_value,
    property_data_type,
    property_unit,
    description,
    b2mml_data
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING
    id,
    equipment_id,
    external_id,
    class_property_id,
    property_value,
    property_data_type,
    property_unit,
    description,
    b2mml_data,
    created_at,
    updated_at
`

type CreateEquipmentPropertyParams struct {
	EquipmentID      uuid.UUID             `db:"equipment_id" json:"equipment_id"`
	ExternalID       string                `db:"external_id" json:"external_id"`
	ClassPropertyID  uuid.NullUUID         `db:"class_property_id" json:"class_property_id"`
	PropertyValue    sql.NullString        `db:"property_value" json:"property_value"`
	PropertyDataType sql.NullString        `db:"property_data_type" json:"property_data_type"`
	PropertyUnit     sql.NullString        `db:"property_unit" json:"property_unit"`
	Description      sql.NullString        `db:"description" json:"description"`
	B2mmlData        pqtype.NullRawMessage `db:"b2mml_data" json:"b2mml_data"`
}

// Equipment Properties queries
func (q *Queries) CreateEquipmentProperty(ctx context.Context, arg *CreateEquipmentPropertyParams) (*EquipmentProperty, error) {
	row := q.db.QueryRowContext(ctx, createEquipmentProperty,
		arg.EquipmentID,
		arg.ExternalID,
		arg.ClassPropertyID,
		arg.PropertyValue,
		arg.PropertyDataType,
		arg.PropertyUnit,
		arg.Description,
		arg.B2mmlData,
	)
	var i EquipmentProperty
	err := row.Scan(
		&i.ID,
		&i.EquipmentID,
		&i.ExternalID,
		&i.ClassPropertyID,
		&i.PropertyValue,
		&i.PropertyDataType,
		&i.PropertyUnit,
		&i.Description,
		&i.B2mmlData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteEquipment = `-- name: DeleteEquipment :exec
UPDATE equipment
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteEquipment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteEquipment, id)
	return err
}

const deleteEquipmentClass = `-- name: DeleteEquipmentClass :exec
UPDATE equipment_classes
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteEquipmentClass(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteEquipmentClass, id)
	return err
}

const deleteEquipmentProperty = `-- name: DeleteEquipmentProperty :exec
DELETE FROM equipment_properties
WHERE id = $1
`

func (q *Queries) DeleteEquipmentProperty(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteEquipmentProperty, id)
	return err
}

const getEquipmentByExternalID = `-- name: GetEquipmentByExternalID :one
SELECT
    id,
    external_id,
    version,
    description,
    published_date,
    effective_start_date,
    effective_end_date,
    hierarchy_scope_id,
    equipment_level,
    operating_status,
    physical_asset_id,
    operational_location_id,
    parent_equipment_id,
    b2mml_data,
    created_at,
    updated_at,
    deleted_at,
    record_version
FROM equipment
WHERE external_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetEquipmentByExternalID(ctx context.Context, externalID string) (*Equipment, error) {
	row := q.db.QueryRowContext(ctx, getEquipmentByExternalID, externalID)
	var i Equipment
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Version,
		&i.Description,
		&i.PublishedDate,
		&i.EffectiveStartDate,
		&i.EffectiveEndDate,
		&i.HierarchyScopeID,
		&i.EquipmentLevel,
		&i.OperatingStatus,
		&i.PhysicalAssetID,
		&i.OperationalLocationID,
		&i.ParentEquipmentID,
		&i.B2mmlData,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RecordVersion,
	)
	return &i, err
}

const getEquipmentByID = `-- name: GetEquipmentByID :one
SELECT
    id,
    external_id,
    version,
    description,
    published_date,
    effective_start_date,
    effective_end_date,
    hierarchy_scope_id,
    equipment_level,
    operating_status,
    physical_asset_id,
    operational_location_id,
    parent_equipment_id,
    b2mml_data,
    created_at,
    updated_at,
    deleted_at,
    record_version
FROM equipment
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetEquipmentByID(ctx context.Context, id uuid.UUID) (*Equipment, error) {
	row := q.db.QueryRowContext(ctx, getEquipmentByID, id)
	var i Equipment
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Version,
		&i.Description,
		&i.PublishedDate,
		&i.EffectiveStartDate,
		&i.EffectiveEndDate,
		&i.HierarchyScopeID,
		&i.EquipmentLevel,
		&i.OperatingStatus,
		&i.PhysicalAssetID,
		&i.OperationalLocationID,
		&i.ParentEquipmentID,
		&i.B2mmlData,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RecordVersion,
	)
	return &i, err
}

const getEquipmentClassByExternalID = `-- name: GetEquipmentClassByExternalID :one
SELECT
    id,
    external_id,
    version,
    description,
    published_date,
    effective_start_date,
    effective_end_date,
    hierarchy_scope_id,
    equipment_level,
    parent_class_id,
    b2mml_data,
    created_at,
    updated_at,
    deleted_at
FROM equipment_classes
WHERE external_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetEquipmentClassByExternalID(ctx context.Context, externalID string) (*EquipmentClass, error) {
	row := q.db.QueryRowContext(ctx, getEquipmentClassByExternalID, externalID)
	var i EquipmentClass
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Version,
		&i.Description,
		&i.PublishedDate,
		&i.EffectiveStartDate,
		&i.EffectiveEndDate,
		&i.HierarchyScopeID,
		&i.EquipmentLevel,
		&i.ParentClassID,
		&i.B2mmlData,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const getEquipmentClassByID = `-- name: GetEquipmentClassByID :one
SELECT
    id,
    external_id,
    version,
    description,
    published_date,
    effective_start_date,
    effective_end_date,
    hierarchy_scope_id,
    equipment_level,
    parent_class_id,
    b2mml_data,
    created_at,
    updated_at,
    deleted_at
FROM equipment_classes
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetEquipmentClassByID(ctx context.Context, id uuid.UUID) (*EquipmentClass, error) {
	row := q.db.QueryRowContext(ctx, getEquipmentClassByID, id)
	var i EquipmentClass
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Version,
		&i.Description,
		&i.PublishedDate,
		&i.EffectiveStartDate,
		&i.EffectiveEndDate,
		&i.HierarchyScopeID,
		&i.EquipmentLevel,
		&i.ParentClassID,
		&i.B2mmlData,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const listAllEquipmentClasses = `-- name: ListAllEquipmentClasses :many
SELECT
    id,
    external_id,
    version,
    description,
    published_date,
    effective_start_date,
    effective_end_date,
    hierarchy_scope_id,
    equipment_level,
    parent_class_id,
    b2mml_data,
    created_at,
    updated_at,
    deleted_at
FROM equipment_classes
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAllEquipmentClassesParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListAllEquipmentClasses(ctx context.Context, arg *ListAllEquipmentClassesParams) ([]*EquipmentClass, error) {
	rows, err := q.db.QueryContext(ctx, listAllEquipmentClasses, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*EquipmentClass{}
	for rows.Next() {
		var i EquipmentClass
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Version,
			&i.Description,
			&i.PublishedDate,
			&i.EffectiveStartDate,
			&i.EffectiveEndDate,
			&i.HierarchyScopeID,
			&i.EquipmentLevel,
			&i.ParentClassID,
			&i.B2mmlData,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChildEquipment = `-- name: ListChildEquipment :many
SELECT
    id,
    external_id,
    version,
    description,
    published_date,
    effective_start_date,
    effective_end_date,
    hierarchy_scope_id,
    equipment_level,
    operating_status,
    physical_asset_id,
    operational_location_id,
    parent_equipment_id,
    b2mml_data,
    created_at,
    updated_at,
    deleted_at,
    record_version
FROM equipment
WHERE parent_equipment_id = $1 AND deleted_at IS NULL
ORDER BY created_at
`

func (q *Queries) ListChildEquipment(ctx context.Context, parentEquipmentID uuid.NullUUID) ([]*Equipment, error) {
	rows, err := q.db.QueryContext(ctx, listChildEquipment, parentEquipmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Equipment{}
	for rows.Next() {
		var i Equipment
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Version,
			&i.Description,
			&i.PublishedDate,
			&i.EffectiveStartDate,
			&i.EffectiveEndDate,
			&i.HierarchyScopeID,
			&i.EquipmentLevel,
			&i.OperatingStatus,
			&i.PhysicalAssetID,
			&i.OperationalLocationID,
			&i.ParentEquipmentID,
			&i.B2mmlData,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.RecordVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEquipment = `-- name: ListEquipment :many
SELECT
    id,
    external_id,
    version,
    description,
    published_date,
    effective_start_date,
    effective_end_date,
    hierarchy_scope_id,
    equipment_level,
    operating_status,
    physical_asset_id,
    operational_location_id,
    parent_equipment_id,
    b2mml_data,
    created_at,
    updated_at,
    deleted_at,
    record_version
FROM equipment
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListEquipmentParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListEquipment(ctx context.Context, arg *ListEquipmentParams) ([]*Equipment, error) {
	rows, err := q.db.QueryContext(ctx, listEquipment, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Equipment{}
	for rows.Next() {
		var i Equipment
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Version,
			&i.Description,
			&i.PublishedDate,
			&i.EffectiveStartDate,
			&i.EffectiveEndDate,
			&i.HierarchyScopeID,
			&i.EquipmentLevel,
			&i.OperatingStatus,
			&i.PhysicalAssetID,
			&i.OperationalLocationID,
			&i.ParentEquipmentID,
			&i.B2mmlData,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.RecordVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEquipmentByClass = `-- name: ListEquipmentByClass :many
SELECT
    e.id,
    e.external_id,
    e.version,
    e.description,
    e.published_date,
    e.effective_start_date,
    e.effective_end_date,
    e.hierarchy_scope_id,
    e.equipment_level,
    e.operating_status,
    e.physical_asset_id,
    e.operational_location_id,
    e.parent_equipment_id,
    e.b2mml_data,
    e.created_at,
    e.updated_at,
    e.deleted_at,
    e.record_version
FROM equipment e
JOIN equipment_class_mappings ecm ON e.id = ecm.equipment_id
WHERE ecm.equipment_class_id = $1 AND e.deleted_at IS NULL
ORDER BY e.created_at DESC
`

func (q *Queries) ListEquipmentByClass(ctx context.Context, equipmentClassID uuid.UUID) ([]*Equipment, error) {
	rows, err := q.db.QueryContext(ctx, listEquipmentByClass, equipmentClassID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Equipment{}
	for rows.Next() {
		var i Equipment
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Version,
			&i.Description,
			&i.PublishedDate,
			&i.EffectiveStartDate,
			&i.EffectiveEndDate,
			&i.HierarchyScopeID,
			&i.EquipmentLevel,
			&i.OperatingStatus,
			&i.PhysicalAssetID,
			&i.OperationalLocationID,
			&i.ParentEquipmentID,
			&i.B2mmlData,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.RecordVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEquipmentByStatus = `-- name: ListEquipmentByStatus :many
SELECT
    id,
    external_id,
    version,
    description,
    published_date,
    effective_start_date,
    effective_end_date,
    hierarchy_scope_id,
    equipment_level,
    operating_status,
    physical_asset_id,
    operational_location_id,
    parent_equipment_id,
    b2mml_data,
    created_at,
    updated_at,
    deleted_at,
    record_version
FROM equipment
WHERE operating_status = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListEquipmentByStatusParams struct {
	OperatingStatus sql.NullString `db:"operating_status" json:"operating_status"`
	Limit           int32          `db:"limit" json:"limit"`
	Offset          int32          `db:"offset" json:"offset"`
}

func (q *Queries) ListEquipmentByStatus(ctx context.Context, arg *ListEquipmentByStatusParams) ([]*Equipment, error) {
	rows, err := q.db.QueryContext(ctx, listEquipmentByStatus, arg.OperatingStatus, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Equipment{}
	for rows.Next() {
		var i Equipment
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Version,
			&i.Description,
			&i.PublishedDate,
			&i.EffectiveStartDate,
			&i.EffectiveEndDate,
			&i.HierarchyScopeID,
			&i.EquipmentLevel,
			&i.OperatingStatus,
			&i.PhysicalAssetID,
			&i.OperationalLocationID,
			&i.ParentEquipmentID,
			&i.B2mmlData,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.RecordVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEquipmentClassProperties = `-- name: ListEquipmentClassProperties :many
SELECT
    id,
    equipment_class_id,
    external_id,
    description,
    property_type,
    parent_property_id,
    b2mml_data,
    created_at,
    updated_at
FROM equipment_class_properties
WHERE equipment_class_id = $1
ORDER BY created_at
`

func (q *Queries) ListEquipmentClassProperties(ctx context.Context, equipmentClassID uuid.UUID) ([]*EquipmentClassProperty, error) {
	rows, err := q.db.QueryContext(ctx, listEquipmentClassProperties, equipmentClassID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*EquipmentClassProperty{}
	for rows.Next() {
		var i EquipmentClassProperty
		if err := rows.Scan(
			&i.ID,
			&i.EquipmentClassID,
			&i.ExternalID,
			&i.Description,
			&i.PropertyType,
			&i.ParentPropertyID,
			&i.B2mmlData,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEquipmentClassesForEquipment = `-- name: ListEquipmentClassesForEquipment :many
SELECT
    ec.id,
    ec.external_id,
    ec.version,
    ec.description,
    ec.published_date,
    ec.effective_start_date,
    ec.effective_end_date,
    ec.hierarchy_scope_id,
    ec.equipment_level,
    ec.parent_class_id,
    ec.b2mml_data,
    ec.created_at,
    ec.updated_at,
    ec.deleted_at
FROM equipment_class_mappings ecm
JOIN equipment_classes ec ON ecm.equipment_class_id = ec.id
WHERE ecm.equipment_id = $1 AND ec.deleted_at IS NULL
ORDER BY ec.created_at
`

func (q *Queries) ListEquipmentClassesForEquipment(ctx context.Context, equipmentID uuid.UUID) ([]*EquipmentClass, error) {
	rows, err := q.db.QueryContext(ctx, listEquipmentClassesForEquipment, equipmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*EquipmentClass{}
	for rows.Next() {
		var i EquipmentClass
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Version,
			&i.Description,
			&i.PublishedDate,
			&i.EffectiveStartDate,
			&i.EffectiveEndDate,
			&i.HierarchyScopeID,
			&i.EquipmentLevel,
			&i.ParentClassID,
			&i.B2mmlData,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEquipmentProperties = `-- name: ListEquipmentProperties :many
SELECT
    id,
    equipment_id,
    external_id,
    class_property_id,
    property_value,
    property_data_type,
    property_unit,
    description,
    b2mml_data,
    created_at,
    updated_at
FROM equipment_properties
WHERE equipment_id = $1
ORDER BY created_at
`

func (q *Queries) ListEquipmentProperties(ctx context.Context, equipmentID uuid.UUID) ([]*EquipmentProperty, error) {
	rows, err := q.db.QueryContext(ctx, listEquipmentProperties, equipmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*EquipmentProperty{}
	for rows.Next() {
		var i EquipmentProperty
		if err := rows.Scan(
			&i.ID,
			&i.EquipmentID,
			&i.ExternalID,
			&i.ClassPropertyID,
			&i.PropertyValue,
			&i.PropertyDataType,
			&i.PropertyUnit,
			&i.Description,
			&i.B2mmlData,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeEquipmentFromClass = `-- name: RemoveEquipmentFromClass :exec
DELETE FROM equipment_class_mappings
WHERE equipment_id = $1 AND equipment_class_id = $2
`

type RemoveEquipmentFromClassParams struct {
	EquipmentID      uuid.UUID `db:"equipment_id" json:"equipment_id"`
	EquipmentClassID uuid.UUID `db:"equipment_class_id" json:"equipment_class_id"`
}

func (q *Queries) RemoveEquipmentFromClass(ctx context.Context, arg *RemoveEquipmentFromClassParams) error {
	_, err := q.db.ExecContext(ctx, removeEquipmentFromClass, arg.EquipmentID, arg.EquipmentClassID)
	return err
}

const updateEquipmentClass = `-- name: UpdateEquipmentClass :one
UPDATE equipment_classes
SET
    version = $2,
    description = $3,
    published_date = $4,
    effective_start_date = $5,
    effective_end_date = $6,
    hierarchy_scope_id = $7,
    equipment_level = $8,
    b2mml_data = $9,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING
    id,
    external_id,
    version,
    description,
    published_date,
    effective_start_date,
    effective_end_date,
    hierarchy_scope_id,
    equipment_level,
    parent_class_id,
    b2mml_data,
    created_at,
    updated_at,
    deleted_at
`

type UpdateEquipmentClassParams struct {
	ID                 uuid.UUID             `db:"id" json:"id"`
	Version            sql.NullString        `db:"version" json:"version"`
	Description        sql.NullString        `db:"description" json:"description"`
	PublishedDate      sql.NullTime          `db:"published_date" json:"published_date"`
	EffectiveStartDate sql.NullTime          `db:"effective_start_date" json:"effective_start_date"`
	EffectiveEndDate   sql.NullTime          `db:"effective_end_date" json:"effective_end_date"`
	HierarchyScopeID   sql.NullString        `db:"hierarchy_scope_id" json:"hierarchy_scope_id"`
	EquipmentLevel     sql.NullString        `db:"equipment_level" json:"equipment_level"`
	B2mmlData          pqtype.NullRawMessage `db:"b2mml_data" json:"b2mml_data"`
}

func (q *Queries) UpdateEquipmentClass(ctx context.Context, arg *UpdateEquipmentClassParams) (*EquipmentClass, error) {
	row := q.db.QueryRowContext(ctx, updateEquipmentClass,
		arg.ID,
		arg.Version,
		arg.Description,
		arg.PublishedDate,
		arg.EffectiveStartDate,
		arg.EffectiveEndDate,
		arg.HierarchyScopeID,
		arg.EquipmentLevel,
		arg.B2mmlData,
	)
	var i EquipmentClass
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Version,
		&i.Description,
		&i.PublishedDate,
		&i.EffectiveStartDate,
		&i.EffectiveEndDate,
		&i.HierarchyScopeID,
		&i.EquipmentLevel,
		&i.ParentClassID,
		&i.B2mmlData,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const updateEquipmentProperty = `-- name: UpdateEquipmentProperty :one
UPDATE equipment_properties
SET
    property_value = $2,
    property_data_type = $3,
    property_unit = $4,
    description = $5,
    b2mml_data = $6,
    updated_at = NOW()
WHERE id = $1
RETURNING
    id,
    equipment_id,
    external_id,
    class_property_id,
    property_value,
    property_data_type,
    property_unit,
    description,
    b2mml_data,
    created_at,
    updated_at
`

type UpdateEquipmentPropertyParams struct {
	ID               uuid.UUID             `db:"id" json:"id"`
	PropertyValue    sql.NullString        `db:"property_value" json:"property_value"`
	PropertyDataType sql.NullString        `db:"property_data_type" json:"property_data_type"`
	PropertyUnit     sql.NullString        `db:"property_unit" json:"property_unit"`
	Description      sql.NullString        `db:"description" json:"description"`
	B2mmlData        pqtype.NullRawMessage `db:"b2mml_data" json:"b2mml_data"`
}

func (q *Queries) UpdateEquipmentProperty(ctx context.Context, arg *UpdateEquipmentPropertyParams) (*EquipmentProperty, error) {
	row := q.db.QueryRowContext(ctx, updateEquipmentProperty,
		arg.ID,
		arg.PropertyValue,
		arg.PropertyDataType,
		arg.PropertyUnit,
		arg.Description,
		arg.B2mmlData,
	)
	var i EquipmentProperty
	err := row.Scan(
		&i.ID,
		&i.EquipmentID,
		&i.ExternalID,
		&i.ClassPropertyID,
		&i.PropertyValue,
		&i.PropertyDataType,
		&i.PropertyUnit,
		&i.Description,
		&i.B2mmlData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateEquipmentStatus = `-- name: UpdateEquipmentStatus :one
UPDATE equipment
SET
    operating_status = $2,
    updated_at = NOW(),
    record_version = record_version + 1
WHERE id = $1 AND deleted_at IS NULL
RETURNING
    id,
    external_id,
    version,
    description,
    published_date,
    effective_start_date,
    effective_end_date,
    hierarchy_scope_id,
    equipment_level,
    operating_status,
    physical_asset_id,
    operational_location_id,
    parent_equipment_id,
    b2mml_data,
    created_at,
    updated_at,
    deleted_at,
    record_version
`

type UpdateEquipmentStatusParams struct {
	ID              uuid.UUID      `db:"id" json:"id"`
	OperatingStatus sql.NullString `db:"operating_status" json:"operating_status"`
}

func (q *Queries) UpdateEquipmentStatus(ctx context.Context, arg *UpdateEquipmentStatusParams) (*Equipment, error) {
	row := q.db.QueryRowContext(ctx, updateEquipmentStatus, arg.ID, arg.OperatingStatus)
	var i Equipment
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Version,
		&i.Description,
		&i.PublishedDate,
		&i.EffectiveStartDate,
		&i.EffectiveEndDate,
		&i.HierarchyScopeID,
		&i.EquipmentLevel,
		&i.OperatingStatus,
		&i.PhysicalAssetID,
		&i.OperationalLocationID,
		&i.ParentEquipmentID,
		&i.B2mmlData,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RecordVersion,
	)
	return &i, err
}
